# Data Preparation

## Import Libraries

In [1]:
import numpy as np
import pandas as pd

## Import Data
The dataset contains all available data for more than 800,000 consumer loans issued from 2007 to 2015 by Lending Club: a large US peer-to-peer lending company. There are several different versions of this dataset. We have used a version available on kaggle.com. You can find it here: https://www.kaggle.com/wendykan/lending-club-loan-data/version/1
We divided the data into two periods because we assume that some data are available at the moment when we need to build Expected Loss models, and some data comes from applications after. Later, we investigate whether the applications we have after we built the Probability of Default (PD) model have similar characteristics with the applications we used to build the PD model.

In [2]:
loan_data_backup = pd.read_csv('loan_data_2007_2014.csv')

C:\Users\Sanket\Anaconda4\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (20) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
loan_data = loan_data_backup.copy()

## Explore Data

In [4]:
loan_data

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466280,466280,8598660,1440975,18400,18400,18400.0,60 months,14.47,432.64,C,...,NaN,NaN,NaN,NaN,NaN,NaN,29900.0,NaN,NaN,NaN
466281,466281,9684700,11536848,22000,22000,22000.0,60 months,19.97,582.50,D,...,NaN,NaN,NaN,NaN,NaN,NaN,39400.0,NaN,NaN,NaN
466282,466282,9584776,11436914,20700,20700,20700.0,60 months,16.99,514.34,D,...,NaN,NaN,NaN,NaN,NaN,NaN,13100.0,NaN,NaN,NaN
466283,466283,9604874,11457002,2000,2000,2000.0,36 months,7.90,62.59,A,...,NaN,NaN,NaN,NaN,NaN,NaN,53100.0,NaN,NaN,NaN
466284,466284,9199665,11061576,10000,10000,9975.0,36 months,19.20,367.58,D,...,NaN,NaN,NaN,NaN,NaN,NaN,16000.0,NaN,NaN,NaN

In [5]:
pd.options.display.max_columns = None
#pd.options.display.max_rows = None
# Sets the pandas dataframe options to display all columns/ rows.

In [6]:
loan_data

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.7,9.0,f,0.00,0.00,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.4,4.0,f,0.00,0.00,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.5,10.0,f,0.00,0.00,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.0,37.0,f,0.00,0.00,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.9,38.0,f,766.90,766.90,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466280,466280,8598660,1440975,18400,18400,18400.0,60 months,14.47,432.64,C,C2,Financial Advisor,4 years,MORTGAGE,110000.0,Source Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,773xx,TX,19.85,0.0,Apr-03,2.0,NaN,NaN,18.0,0.0,23208,77.6,36.0,w,12574.00,12574.00,10383.360000,10383.36,5826.00,4557.36,0.00,0.00,0.00,Jan-16,432.64,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,294998.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29900.0,NaN,NaN,NaN
466281,466281,9684700,11536848,22000,22000,22000.0,60 months,19.97,582.50,D,D5,Chief of Interpretation (Park Ranger),10+ years,MORTGAGE,78000.0,Verified,Jan-14,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,377xx,TN,18.45,0.0,Jun-97,5.0,NaN,116.0,18.0,1.0,18238,46.3,30.0,f,0.00,0.00,4677.920000,4677.92,1837.04,2840.88,0.00,0.00,0.00,Dec-14,17.50,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,221830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39400.0,NaN,NaN,NaN
466282,466282,9584776,11436914,20700,20700,20700.0,60 months,16.99,514.34,D,D1,patrol,7 years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/06/13 > I am going to c...,debt_consolidation,Debt consolidation,458xx,OH,25.65,0.0,Dec-01,2.0,65.0,NaN,18.0,0.0,6688,51.1,43.0,f,14428.31,14428.31,12343.980000,12343.98,6271.69,6072.29,0.00,0.00,0.00,Jan-16,514.34,Feb-16,Dec-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,73598.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13100.0,NaN,NaN,NaN
466283,466283,9604874,11457002,2000,2000,2000.0,36 months,7.90,62.59,A,A4,Server Engineer Lead,3 years,OWN,83000.0,Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,Credit card refinancing,913xx,CA,5.39,3.0,Feb-03,1.0,13.0,NaN,21.0,0.0,11404,21.5,27.0,w,0.00,0.00,2126.579838,2126.58,2000.00,126.58,0.00,0.00,0.00,Dec-14,1500.68,NaN,Apr-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,591610.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53100.0,NaN,NaN,NaN
466284,466284,9199665,11061576,10000,10000,9975.0,36 months,19.20,367.58,D,D3,NaN,10+ years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/04/13 > I will like a l...,other,Other,950xx,CA,22.78,1.0,Feb-00,0.0,9.0,NaN,6.0,0.0,11325,70.8,22.0,f,3984.38,3974.41,8821.620000,8799.57,6015.62,2806.00,0.00,0.00,0.00,Jan-16,367.58,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,57477.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000.0,NaN,NaN,NaN

In [7]:
loan_data.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.7,9.0,f,0.0,0.0,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.4,4.0,f,0.0,0.0,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.5,10.0,f,0.0,0.0,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.0,37.0,f,0.0,0.0,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.9,38.0,f,766.9,766.9,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
loan_data.tail()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
466280,466280,8598660,1440975,18400,18400,18400.0,60 months,14.47,432.64,C,C2,Financial Advisor,4 years,MORTGAGE,110000.0,Source Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,773xx,TX,19.85,0.0,Apr-03,2.0,NaN,NaN,18.0,0.0,23208,77.6,36.0,w,12574.00,12574.00,10383.360000,10383.36,5826.00,4557.36,0.0,0.0,0.0,Jan-16,432.64,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,294998.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29900.0,NaN,NaN,NaN
466281,466281,9684700,11536848,22000,22000,22000.0,60 months,19.97,582.50,D,D5,Chief of Interpretation (Park Ranger),10+ years,MORTGAGE,78000.0,Verified,Jan-14,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,377xx,TN,18.45,0.0,Jun-97,5.0,NaN,116.0,18.0,1.0,18238,46.3,30.0,f,0.00,0.00,4677.920000,4677.92,1837.04,2840.88,0.0,0.0,0.0,Dec-14,17.50,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,221830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39400.0,NaN,NaN,NaN
466282,466282,9584776,11436914,20700,20700,20700.0,60 months,16.99,514.34,D,D1,patrol,7 years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/06/13 > I am going to c...,debt_consolidation,Debt consolidation,458xx,OH,25.65,0.0,Dec-01,2.0,65.0,NaN,18.0,0.0,6688,51.1,43.0,f,14428.31,14428.31,12343.980000,12343.98,6271.69,6072.29,0.0,0.0,0.0,Jan-16,514.34,Feb-16,Dec-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,73598.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13100.0,NaN,NaN,NaN
466283,466283,9604874,11457002,2000,2000,2000.0,36 months,7.90,62.59,A,A4,Server Engineer Lead,3 years,OWN,83000.0,Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,Credit card refinancing,913xx,CA,5.39,3.0,Feb-03,1.0,13.0,NaN,21.0,0.0,11404,21.5,27.0,w,0.00,0.00,2126.579838,2126.58,2000.00,126.58,0.0,0.0,0.0,Dec-14,1500.68,NaN,Apr-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,591610.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53100.0,NaN,NaN,NaN
466284,466284,9199665,11061576,10000,10000,9975.0,36 months,19.20,367.58,D,D3,NaN,10+ years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/04/13 > I will like a l...,other,Other,950xx,CA,22.78,1.0,Feb-00,0.0,9.0,NaN,6.0,0.0,11325,70.8,22.0,f,3984.38,3974.41,8821.620000,8799.57,6015.62,2806.00,0.0,0.0,0.0,Jan-16,367.58,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,57477.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000.0,NaN,NaN,NaN

In [9]:
loan_data.columns.values
# Displays all column names.

array(['Unnamed: 0', 'id', 'member_id', 'loan_amnt', 'funded_amnt',
       'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'emp_title', 'emp_length', 'home_ownership',
       'annual_inc', 'verification_status', 'issue_d', 'loan_status',
       'pymnt_plan', 'url', 'desc', 'purpose', 'title', 'zip_code',
       'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
       'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee',
       'recoveries', 'collection_recovery_fee', 'last_pymnt_d',
       'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'policy_code', 'application_type', 'annual_inc_joint', 'dti_joint',
       'verification_status_joint', 'acc_now_delinq', 'tot_coll_amt',
       'tot_cur_bal', 'open_acc_6m', 'open_il_6m', 'open_il_12m',
       'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util',
       'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m'],
      dtype=object)

In [10]:
loan_data.info()
# Displays column names, complete (non-missing) cases per column, and datatype per column.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 75 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   466285 non-null  int64
 1   id                           466285 non-null  int64
 2   member_id                    466285 non-null  int64
 3   loan_amnt                    466285 non-null  int64
 4   funded_amnt                  466285 non-null  int64
 5   funded_amnt_inv              466285 non-null  float64
 6   term                         466285 non-null  object
 7   int_rate                     466285 non-null  float64
 8   installment                  466285 non-null  float64
 9   grade                        466285 non-null  object
 10  sub_grade                    466285 non-null  object
 11  emp_title                    438697 non-null  object
 12  emp_length                   445277 non-null  object
 13  home_ownership               466285 non-null  object
 14  annual_inc                   466281 non-null  float64
 15  verification_status          466285 non-null  object
 16  issue_d                      466285 non-null  object
 17  loan_status                  466285 non-null  object
 18  pymnt_plan                   466285 non-null  object
 19  url                          466285 non-null  object
 20  desc                         125983 non-null  object
 21  purpose                      466285 non-null  object
 22  title                        466265 non-null  object
 23  zip_code                     466285 non-null  object
 24  addr_state                   466285 non-null  object
 25  dti                          466285 non-null  float64
 26  delinq_2yrs                  466256 non-null  float64
 27  earliest_cr_line             466256 non-null  object
 28  inq_last_6mths               466256 non-null  float64
 29  mths_since_last_delinq       215934 non-null  float64
 30  mths_since_last_record       62638 non-null   float64
 31  open_acc                     466256 non-null  float64
 32  pub_rec                      466256 non-null  float64
 33  revol_bal                    466285 non-null  int64
 34  revol_util                   465945 non-null  float64
 35  total_acc                    466256 non-null  float64
 36  initial_list_status          466285 non-null  object
 37  out_prncp                    466285 non-null  float64
 38  out_prncp_inv                466285 non-null  float64
 39  total_pymnt                  466285 non-null  float64
 40  total_pymnt_inv              466285 non-null  float64
 41  total_rec_prncp              466285 non-null  float64
 42  total_rec_int                466285 non-null  float64
 43  total_rec_late_fee           466285 non-null  float64
 44  recoveries                   466285 non-null  float64
 45  collection_recovery_fee      466285 non-null  float64
 46  last_pymnt_d                 465909 non-null  object
 47  last_pymnt_amnt              466285 non-null  float64
 48  next_pymnt_d                 239071 non-null  object
 49  last_credit_pull_d           466243 non-null  object
 50  collections_12_mths_ex_med   466140 non-null  float64
 51  mths_since_last_major_derog  98974 non-null   float64
 52  policy_code                  466285 non-null  int64
 53  application_type             466285 non-null  object
 54  annual_inc_joint             0 non-null       float64
 55  dti_joint                    0 non-null       float64
 56  verification_status_joint    0 non-null       float64
 57  acc_now_delinq               466256 non-null  float64
 58  tot_coll_amt                 396009 non-null  float64
 59  tot_cur_bal                  396009 non-null  float64
 60  open_acc_6m                  0 non-null       float64
 61  open_il_6m                   0 non-null       float64
 62  open_il_12m                  0 non-null       float64
 63  open_il_24m                  0 non-null       float64
 64  mths_since_rcnt_il           0 non-null       float64
 65  total_bal_il                 0 non-null       float64
 66  il_util                      0 non-null       float64
 67  open_rv_12m                  0 non-null       float64
 68  open_rv_24m                  0 non-null       float64
 69  max_bal_bc                   0 non-null       float64
 70  all_util                     0 non-null       float64
 71  total_rev_hi_lim             396009 non-null  float64
 72  inq_fi                       0 non-null       float64
 73  total_cu_tl                  0 non-null       float64
 74  inq_last_12m                 0 non-null       float64
dtypes: float64(46), int64(7), object(22)
memory usage: 266.8+ MB

## General Preprocessing

### Preprocessing few continuous variables

In [11]:
loan_data['emp_length'].unique()
# Displays unique values of a column.

array(['10+ years', '< 1 year', '1 year', '3 years', '8 years', '9 years',
       '4 years', '5 years', '6 years', '2 years', '7 years', nan],
      dtype=object)

In [12]:
loan_data['emp_length_int'] = loan_data['emp_length'].str.replace('\+ years', '')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('< 1 year', str(0))
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('n/a',  str(0))
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' years', '')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' year', '')
# We store the preprocessed ‘employment length’ variable in a new variable called ‘employment length int’,
# We assign the new ‘employment length int’ to be equal to the ‘employment length’ variable with the string ‘+ years’
# replaced with nothing. Next, we replace the whole string ‘less than 1 year’ with the string ‘0’.
# Then, we replace the ‘n/a’ string with the string ‘0’. Then, we replace the string ‘space years’ with nothing.
# Finally, we replace the string ‘space year’ with nothing.

In [13]:
type(loan_data['emp_length_int'][0])
# Checks the datatype of a single element of a column.

str

In [14]:
loan_data['emp_length_int'] = pd.to_numeric(loan_data['emp_length_int'])
# Transforms the values to numeric.

In [15]:
type(loan_data['emp_length_int'][0])
# Checks the datatype of a single element of a column.

numpy.float64

In [16]:
loan_data['earliest_cr_line']
# Displays a column.

0         Jan-85
1         Apr-99
2         Nov-01
3         Feb-96
4         Jan-96
           ...
466280    Apr-03
466281    Jun-97
466282    Dec-01
466283    Feb-03
466284    Feb-00
Name: earliest_cr_line, Length: 466285, dtype: object

In [17]:
loan_data['earliest_cr_line_date'] = pd.to_datetime(loan_data['earliest_cr_line'], format = '%b-%y')
# Extracts the date and the time from a string variable that is in a given format.

In [18]:
type(loan_data['earliest_cr_line_date'][0])
# Checks the datatype of a single element of a column.

pandas._libs.tslibs.timestamps.Timestamp

In [19]:
pd.to_datetime('2017-12-01') - loan_data['earliest_cr_line_date']
# Calculates the difference between two dates and times.

0        12022 days
1         6819 days
2         5874 days
3         7974 days
4         8005 days
            ...
466280    5358 days
466281    7488 days
466282    5844 days
466283    5417 days
466284    6513 days
Name: earliest_cr_line_date, Length: 466285, dtype: timedelta64[ns]

In [20]:
# Assume we are now in December 2017
loan_data['mths_since_earliest_cr_line'] = round(pd.to_numeric((pd.to_datetime('2017-12-01') - loan_data['earliest_cr_line_date']) / np.timedelta64(1, 'M')))
# We calculate the difference between two dates in months, turn it to numeric datatype and round it.
# We save the result in a new variable.

In [21]:
loan_data['mths_since_earliest_cr_line'].describe()
# Shows some descriptive statisics for the values of a column.
# Dates from 1969 and before are not being converted well, i.e., they have become 2069 and similar,
# and negative differences are being calculated.

count    466256.000000
mean        239.482430
std          93.974829
min        -612.000000
25%         183.000000
50%         225.000000
75%         285.000000
max         587.000000
Name: mths_since_earliest_cr_line, dtype: float64

In [22]:
loan_data.loc[: , ['earliest_cr_line', 'earliest_cr_line_date', 'mths_since_earliest_cr_line']][loan_data['mths_since_earliest_cr_line'] < 0]
# We take three columns from the dataframe. Then, we display them only for the rows where a variable has negative value.
# There are 2303 strange negative values.

       earliest_cr_line earliest_cr_line_date  mths_since_earliest_cr_line
1580             Sep-62            2062-09-01                       -537.0
1770             Sep-68            2068-09-01                       -609.0
2799             Sep-64            2064-09-01                       -561.0
3282             Sep-67            2067-09-01                       -597.0
3359             Feb-65            2065-02-01                       -566.0
...                 ...                   ...                          ...
464003           Jan-68            2068-01-01                       -601.0
464260           Jul-66            2066-07-01                       -583.0
465100           Oct-67            2067-10-01                       -598.0
465500           Sep-67            2067-09-01                       -597.0
465655           Jan-56            2056-01-01                       -457.0

[1169 rows x 3 columns]

In [23]:
loan_data['mths_since_earliest_cr_line'][loan_data['mths_since_earliest_cr_line'] < 0] = loan_data['mths_since_earliest_cr_line'].max()
# We set the rows that had negative differences to the maximum value.

C:\Users\Sanket\Anaconda4\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [24]:
min(loan_data['mths_since_earliest_cr_line'])
# Calculates and shows the minimum value of a column.

73.0

### Homework

In [25]:
loan_data['term']

0          36 months
1          60 months
2          36 months
3          36 months
4          60 months
             ...
466280     60 months
466281     60 months
466282     60 months
466283     36 months
466284     36 months
Name: term, Length: 466285, dtype: object

In [26]:
loan_data['term'].describe()
# Shows some descriptive statisics for the values of a column.

count         466285
unique             2
top        36 months
freq          337953
Name: term, dtype: object

In [27]:
loan_data['term_int'] = loan_data['term'].str.replace(' months', '')
# We replace a string with another string, in this case, with an empty strng (i.e. with nothing).

In [28]:
loan_data['term_int']

0          36
1          60
2          36
3          36
4          60
         ...
466280     60
466281     60
466282     60
466283     36
466284     36
Name: term_int, Length: 466285, dtype: object

In [29]:
type(loan_data['term_int'][25])
# Checks the datatype of a single element of a column.

str

In [30]:
loan_data['term_int'] = pd.to_numeric(loan_data['term'].str.replace(' months', ''))
# We remplace a string from a variable with another string, in this case, with an empty strng (i.e. with nothing).
# We turn the result to numeric datatype and save it in another variable.
loan_data['term_int']

0         36
1         60
2         36
3         36
4         60
          ..
466280    60
466281    60
466282    60
466283    36
466284    36
Name: term_int, Length: 466285, dtype: int64

In [31]:
type(loan_data['term_int'][0])
# Checks the datatype of a single element of a column.

numpy.int64

In [32]:
loan_data['issue_d']

0         Dec-11
1         Dec-11
2         Dec-11
3         Dec-11
4         Dec-11
           ...
466280    Jan-14
466281    Jan-14
466282    Jan-14
466283    Jan-14
466284    Jan-14
Name: issue_d, Length: 466285, dtype: object

In [33]:
# Assume we are now in December 2017
loan_data['issue_d_date'] = pd.to_datetime(loan_data['issue_d'], format = '%b-%y')
# Extracts the date and the time from a string variable that is in a given format.
loan_data['mths_since_issue_d'] = round(pd.to_numeric((pd.to_datetime('2017-12-01') - loan_data['issue_d_date']) / np.timedelta64(1, 'M')))
# We calculate the difference between two dates in months, turn it to numeric datatype and round it.
# We save the result in a new variable.
loan_data['mths_since_issue_d'].describe()
# Shows some descriptive statisics for the values of a column.

count    466285.000000
mean         51.255187
std          14.340154
min          36.000000
25%          41.000000
50%          47.000000
75%          57.000000
max         126.000000
Name: mths_since_issue_d, dtype: float64

### Preprocessing few discrete variables

In [34]:
loan_data.info()
# Displays column names, complete (non-missing) cases per column, and datatype per column.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 81 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   466285 non-null  int64
 1   id                           466285 non-null  int64
 2   member_id                    466285 non-null  int64
 3   loan_amnt                    466285 non-null  int64
 4   funded_amnt                  466285 non-null  int64
 5   funded_amnt_inv              466285 non-null  float64
 6   term                         466285 non-null  object
 7   int_rate                     466285 non-null  float64
 8   installment                  466285 non-null  float64
 9   grade                        466285 non-null  object
 10  sub_grade                    466285 non-null  object
 11  emp_title                    438697 non-null  object
 12  emp_length                   445277 non-null  object
 13  home_ownership               466285 non-null  object
 14  annual_inc                   466281 non-null  float64
 15  verification_status          466285 non-null  object
 16  issue_d                      466285 non-null  object
 17  loan_status                  466285 non-null  object
 18  pymnt_plan                   466285 non-null  object
 19  url                          466285 non-null  object
 20  desc                         125983 non-null  object
 21  purpose                      466285 non-null  object
 22  title                        466265 non-null  object
 23  zip_code                     466285 non-null  object
 24  addr_state                   466285 non-null  object
 25  dti                          466285 non-null  float64
 26  delinq_2yrs                  466256 non-null  float64
 27  earliest_cr_line             466256 non-null  object
 28  inq_last_6mths               466256 non-null  float64
 29  mths_since_last_delinq       215934 non-null  float64
 30  mths_since_last_record       62638 non-null   float64
 31  open_acc                     466256 non-null  float64
 32  pub_rec                      466256 non-null  float64
 33  revol_bal                    466285 non-null  int64
 34  revol_util                   465945 non-null  float64
 35  total_acc                    466256 non-null  float64
 36  initial_list_status          466285 non-null  object
 37  out_prncp                    466285 non-null  float64
 38  out_prncp_inv                466285 non-null  float64
 39  total_pymnt                  466285 non-null  float64
 40  total_pymnt_inv              466285 non-null  float64
 41  total_rec_prncp              466285 non-null  float64
 42  total_rec_int                466285 non-null  float64
 43  total_rec_late_fee           466285 non-null  float64
 44  recoveries                   466285 non-null  float64
 45  collection_recovery_fee      466285 non-null  float64
 46  last_pymnt_d                 465909 non-null  object
 47  last_pymnt_amnt              466285 non-null  float64
 48  next_pymnt_d                 239071 non-null  object
 49  last_credit_pull_d           466243 non-null  object
 50  collections_12_mths_ex_med   466140 non-null  float64
 51  mths_since_last_major_derog  98974 non-null   float64
 52  policy_code                  466285 non-null  int64
 53  application_type             466285 non-null  object
 54  annual_inc_joint             0 non-null       float64
 55  dti_joint                    0 non-null       float64
 56  verification_status_joint    0 non-null       float64
 57  acc_now_delinq               466256 non-null  float64
 58  tot_coll_amt                 396009 non-null  float64
 59  tot_cur_bal                  396009 non-null  float64
 60  open_acc_6m                  0 non-null       float64
 61  open_il_6m                   0 non-null       float64
 62  open_il_12m                  0 non-null       float64
 63  open_il_24m                  0 non-null       float64
 64  mths_since_rcnt_il           0 non-null       float64
 65  total_bal_il                 0 non-null       float64
 66  il_util                      0 non-null       float64
 67  open_rv_12m                  0 non-null       float64
 68  open_rv_24m                  0 non-null       float64
 69  max_bal_bc                   0 non-null       float64
 70  all_util                     0 non-null       float64
 71  total_rev_hi_lim             396009 non-null  float64
 72  inq_fi                       0 non-null       float64
 73  total_cu_tl                  0 non-null       float64
 74  inq_last_12m                 0 non-null       float64
 75  emp_length_int               445277 non-null  float64
 76  earliest_cr_line_date        466256 non-null  datetime64[ns]
 77  mths_since_earliest_cr_line  466256 non-null  float64
 78  term_int                     466285 non-null  int64
 79  issue_d_date                 466285 non-null  datetime64[ns]
 80  mths_since_issue_d           466285 non-null  float64
dtypes: datetime64[ns](2), float64(49), int64(8), object(22)
memory usage: 288.2+ MB

We are going to preprocess the following discrete variables: grade, sub_grade, home_ownership, verification_status, loan_status, purpose, addr_state, initial_list_status. Most likely, we are not going to use sub_grade, as it overlaps with grade.

In [35]:
pd.get_dummies(loan_data['grade'])
# Create dummy variables from a variable.

        A  B  C  D  E  F  G
0       0  1  0  0  0  0  0
1       0  0  1  0  0  0  0
2       0  0  1  0  0  0  0
3       0  0  1  0  0  0  0
4       0  1  0  0  0  0  0
...    .. .. .. .. .. .. ..
466280  0  0  1  0  0  0  0
466281  0  0  0  1  0  0  0
466282  0  0  0  1  0  0  0
466283  1  0  0  0  0  0  0
466284  0  0  0  1  0  0  0

[466285 rows x 7 columns]

In [36]:
pd.get_dummies(loan_data['grade'], prefix = 'grade', prefix_sep = ':')
# Create dummy variables from a variable.

        grade:A  grade:B  grade:C  grade:D  grade:E  grade:F  grade:G
0             0        1        0        0        0        0        0
1             0        0        1        0        0        0        0
2             0        0        1        0        0        0        0
3             0        0        1        0        0        0        0
4             0        1        0        0        0        0        0
...         ...      ...      ...      ...      ...      ...      ...
466280        0        0        1        0        0        0        0
466281        0        0        0        1        0        0        0
466282        0        0        0        1        0        0        0
466283        1        0        0        0        0        0        0
466284        0        0        0        1        0        0        0

[466285 rows x 7 columns]

In [37]:
loan_data_dummies = [pd.get_dummies(loan_data['grade'], prefix = 'grade', prefix_sep = ':'),
                     pd.get_dummies(loan_data['sub_grade'], prefix = 'sub_grade', prefix_sep = ':'),
                     pd.get_dummies(loan_data['home_ownership'], prefix = 'home_ownership', prefix_sep = ':'),
                     pd.get_dummies(loan_data['verification_status'], prefix = 'verification_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['loan_status'], prefix = 'loan_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['purpose'], prefix = 'purpose', prefix_sep = ':'),
                     pd.get_dummies(loan_data['addr_state'], prefix = 'addr_state', prefix_sep = ':'),
                     pd.get_dummies(loan_data['initial_list_status'], prefix = 'initial_list_status', prefix_sep = ':')]
# We create dummy variables from all 8 original independent variables, and save them into a list.
# Note that we are using a particular naming convention for all variables: original variable name, colon, category name.

In [38]:
loan_data_dummies = pd.concat(loan_data_dummies, axis = 1)
# We concatenate the dummy variables and this turns them into a dataframe.

In [39]:
type(loan_data_dummies)
# Returns the type of the variable.

pandas.core.frame.DataFrame

In [40]:
loan_data = pd.concat([loan_data, loan_data_dummies], axis = 1)
# Concatenates two dataframes.
# Here we concatenate the dataframe with original data with the dataframe with dummy variables, along the columns.

In [41]:
loan_data.columns.values
# Displays all column names.

array(['Unnamed: 0', 'id', 'member_id', 'loan_amnt', 'funded_amnt',
       'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'emp_title', 'emp_length', 'home_ownership',
       'annual_inc', 'verification_status', 'issue_d', 'loan_status',
       'pymnt_plan', 'url', 'desc', 'purpose', 'title', 'zip_code',
       'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
       'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee',
       'recoveries', 'collection_recovery_fee', 'last_pymnt_d',
       'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'policy_code', 'application_type', 'annual_inc_joint', 'dti_joint',
       'verification_status_joint', 'acc_now_delinq', 'tot_coll_amt',
       'tot_cur_bal', 'open_acc_6m', 'open_il_6m', 'open_il_12m',
       'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util',
       'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'emp_length_int', 'earliest_cr_line_date',
       'mths_since_earliest_cr_line', 'term_int', 'issue_d_date',
       'mths_since_issue_d', 'grade:A', 'grade:B', 'grade:C', 'grade:D',
       'grade:E', 'grade:F', 'grade:G', 'sub_grade:A1', 'sub_grade:A2',
       'sub_grade:A3', 'sub_grade:A4', 'sub_grade:A5', 'sub_grade:B1',
       'sub_grade:B2', 'sub_grade:B3', 'sub_grade:B4', 'sub_grade:B5',
       'sub_grade:C1', 'sub_grade:C2', 'sub_grade:C3', 'sub_grade:C4',
       'sub_grade:C5', 'sub_grade:D1', 'sub_grade:D2', 'sub_grade:D3',
       'sub_grade:D4', 'sub_grade:D5', 'sub_grade:E1', 'sub_grade:E2',
       'sub_grade:E3', 'sub_grade:E4', 'sub_grade:E5', 'sub_grade:F1',
       'sub_grade:F2', 'sub_grade:F3', 'sub_grade:F4', 'sub_grade:F5',
       'sub_grade:G1', 'sub_grade:G2', 'sub_grade:G3', 'sub_grade:G4',
       'sub_grade:G5', 'home_ownership:ANY', 'home_ownership:MORTGAGE',
       'home_ownership:NONE', 'home_ownership:OTHER',
       'home_ownership:OWN', 'home_ownership:RENT',
       'verification_status:Not Verified',
       'verification_status:Source Verified',
       'verification_status:Verified', 'loan_status:Charged Off',
       'loan_status:Current', 'loan_status:Default',
       'loan_status:Does not meet the credit policy. Status:Charged Off',
       'loan_status:Does not meet the credit policy. Status:Fully Paid',
       'loan_status:Fully Paid', 'loan_status:In Grace Period',
       'loan_status:Late (16-30 days)', 'loan_status:Late (31-120 days)',
       'purpose:car', 'purpose:credit_card', 'purpose:debt_consolidation',
       'purpose:educational', 'purpose:home_improvement', 'purpose:house',
       'purpose:major_purchase', 'purpose:medical', 'purpose:moving',
       'purpose:other', 'purpose:renewable_energy',
       'purpose:small_business', 'purpose:vacation', 'purpose:wedding',
       'addr_state:AK', 'addr_state:AL', 'addr_state:AR', 'addr_state:AZ',
       'addr_state:CA', 'addr_state:CO', 'addr_state:CT', 'addr_state:DC',
       'addr_state:DE', 'addr_state:FL', 'addr_state:GA', 'addr_state:HI',
       'addr_state:IA', 'addr_state:ID', 'addr_state:IL', 'addr_state:IN',
       'addr_state:KS', 'addr_state:KY', 'addr_state:LA', 'addr_state:MA',
       'addr_state:MD', 'addr_state:ME', 'addr_state:MI', 'addr_state:MN',
       'addr_state:MO', 'addr_state:MS', 'addr_state:MT', 'addr_state:NC',
       'addr_state:NE', 'addr_state:NH', 'addr_state:NJ', 'addr_state:NM',
       'addr_state:NV', 'addr_state:NY', 'addr_state:OH', 'addr_state:OK',
       'addr_state:OR', 'addr_state:PA', 'addr_state:RI', 'addr_state:SC',
       'addr_state:SD', 'addr_state:TN', 'addr_state:TX', 'addr_state:UT',
       'addr_state:VA', 'addr_state:VT', 'addr_state:WA', 'addr_state:WI',
       'addr_state:WV', 'addr_state:WY', 'initial_list_status:f',
       'initial_list_status:w'], dtype=object)

### Check for missing values and clean

In [42]:
loan_data.isnull()
# It returns 'False' if a value is not missing and 'True' if a value is missing, for each value in a dataframe.

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,emp_length_int,earliest_cr_line_date,mths_since_earliest_cr_line,term_int,issue_d_date,mths_since_issue_d,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,grade:G,sub_grade:A1,sub_grade:A2,sub_grade:A3,sub_grade:A4,sub_grade:A5,sub_grade:B1,sub_grade:B2,sub_grade:B3,sub_grade:B4,sub_grade:B5,sub_grade:C1,sub_grade:C2,sub_grade:C3,sub_grade:C4,sub_grade:C5,sub_grade:D1,sub_grade:D2,sub_grade:D3,sub_grade:D4,sub_grade:D5,sub_grade:E1,sub_grade:E2,sub_grade:E3,sub_grade:E4,sub_grade:E5,sub_grade:F1,sub_grade:F2,sub_grade:F3,sub_grade:F4,sub_grade:F5,sub_grade:G1,sub_grade:G2,sub_grade:G3,sub_grade:G4,sub_grade:G5,home_ownership:ANY,home_ownership:MORTGAGE,home_ownership:NONE,home_ownership:OTHER,home_ownership:OWN,home_ownership:RENT,verification_status:Not Verified,verification_status:Source Verified,verification_status:Verified,loan_status:Charged Off,loan_status:Current,loan_status:Default,loan_status:Does not meet the credit policy. Status:Charged Off,loan_status:Does not meet the credit policy. Status:Fully Paid,loan_status:Fully Paid,loan_status:In Grace Period,loan_status:Late (16-30 days),loan_status:Late (31-120 days),purpose:car,purpose:credit_card,purpose:debt_consolidation,purpose:educational,purpose:home_improvement,purpose:house,purpose:major_purchase,purpose:medical,purpose:moving,purpose:other,purpose:renewable_energy,purpose:small_business,purpose:vacation,purpose:wedding,addr_state:AK,addr_state:AL,addr_state:AR,addr_state:AZ,addr_state:CA,addr_state:CO,addr_state:CT,addr_state:DC,addr_state:DE,addr_state:FL,addr_state:GA,addr_state:HI,addr_state:IA,addr_state:ID,addr_state:IL,addr_state:IN,addr_state:KS,addr_state:KY,addr_state:LA,addr_state:MA,addr_state:MD,addr_state:ME,addr_state:MI,addr_state:MN,addr_state:MO,addr_state:MS,addr_state:MT,addr_state:NC,addr_state:NE,addr_state:NH,addr_state:NJ,addr_state:NM,addr_state:NV,addr_state:NY,addr_state:OH,addr_state:OK,addr_state:OR,addr_state:PA,addr_state:RI,addr_state:SC,addr_state:SD,addr_state:TN,addr_state:TX,addr_state:UT,addr_state:VA,addr_state:VT,addr_state:WA,addr_state:WI,addr_state:WV,addr_state:WY,initial_list_status:f,initial_list_status:w
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466280,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
466281,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
466282,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
466283,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
466284,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [43]:
pd.options.display.max_rows = None
# Sets the pandas dataframe options to display all columns/ rows.
loan_data.isnull().sum()

Unnamed: 0                                                              0
id                                                                      0
member_id                                                               0
loan_amnt                                                               0
funded_amnt                                                             0
funded_amnt_inv                                                         0
term                                                                    0
int_rate                                                                0
installment                                                             0
grade                                                                   0
sub_grade                                                               0
emp_title                                                           27588
emp_length                                                          21008
home_ownership                                                          0
annual_inc                                                              4
verification_status                                                     0
issue_d                                                                 0
loan_status                                                             0
pymnt_plan                                                              0
url                                                                     0
desc                                                               340302
purpose                                                                 0
title                                                                  20
zip_code                                                                0
addr_state                                                              0
dti                                                                     0
delinq_2yrs                                                            29
earliest_cr_line                                                       29
inq_last_6mths                                                         29
mths_since_last_delinq                                             250351
mths_since_last_record                                             403647
open_acc                                                               29
pub_rec                                                                29
revol_bal                                                               0
revol_util                                                            340
total_acc                                                              29
initial_list_status                                                     0
out_prncp                                                               0
out_prncp_inv                                                           0
total_pymnt                                                             0
total_pymnt_inv                                                         0
total_rec_prncp                                                         0
total_rec_int                                                           0
total_rec_late_fee                                                      0
recoveries                                                              0
collection_recovery_fee                                                 0
last_pymnt_d                                                          376
last_pymnt_amnt                                                         0
next_pymnt_d                                                       227214
last_credit_pull_d                                                     42
collections_12_mths_ex_med                                            145
mths_since_last_major_derog                                        367311
policy_code                                                             0
application_type                                                        0
annual_inc_joint                                                   466285
dti_joint                                                          466285
verification_status_joint                                          466285
acc_now_delinq                                                         29
tot_coll_amt                                                        70276
tot_cur_bal                                                         70276
open_acc_6m                                                        466285
open_il_6m                                                         466285
open_il_12m                                                        466285
open_il_24m                                                        466285
mths_since_rcnt_il                                                 466285
total_bal_il                                                       466285
il_util                                                            466285
open_rv_12m                                                        466285
open_rv_24m                                                        466285
max_bal_bc                                                         466285
all_util                                                           466285
total_rev_hi_lim                                                    70276
inq_fi                                                             466285
total_cu_tl                                                        466285
inq_last_12m                                                       466285
emp_length_int                                                      21008
earliest_cr_line_date                                                  29
mths_since_earliest_cr_line                                            29
term_int                                                                0
issue_d_date                                                            0
mths_since_issue_d                                                      0
grade:A                                                                 0
grade:B                                                                 0
grade:C                                                                 0
grade:D                                                                 0
grade:E                                                                 0
grade:F                                                                 0
grade:G                                                                 0
sub_grade:A1                                                            0
sub_grade:A2                                                            0
sub_grade:A3                                                            0
sub_grade:A4                                                            0
sub_grade:A5                                                            0
sub_grade:B1                                                            0
sub_grade:B2                                                            0
sub_grade:B3                                                            0
sub_grade:B4                                                            0
sub_grade:B5                                                            0
sub_grade:C1                                                            0
sub_grade:C2                                                            0
sub_grade:C3                                                            0
sub_grade:C4                                                            0
sub_grade:C5                                                            0
sub_grade:D1                                                            0
sub_grade:D2                                                            0
sub_grade:D3                                                            0
sub_grade:D4                                                            0
sub_grade:D5                                                            0
sub_grade:E1                                                            0
sub_grade:E2                                                            0
sub_grade:E3                                                            0
sub_grade:E4                                                            0
sub_grade:E5                                                            0
sub_grade:F1                                                            0
sub_grade:F2                                                            0
sub_grade:F3                                                            0
sub_grade:F4                                                            0
sub_grade:F5                                                            0
sub_grade:G1                                                            0
sub_grade:G2                                                            0
sub_grade:G3                                                            0
sub_grade:G4                                                            0
sub_grade:G5                                                            0
home_ownership:ANY                                                      0
home_ownership:MORTGAGE                                                 0
home_ownership:NONE                                                     0
home_ownership:OTHER                                                    0
home_ownership:OWN                                                      0
home_ownership:RENT                                                     0
verification_status:Not Verified                                        0
verification_status:Source Verified                                     0
verification_status:Verified                                            0
loan_status:Charged Off                                                 0
loan_status:Current                                                     0
loan_status:Default                                                     0
loan_status:Does not meet the credit policy. Status:Charged Off         0
loan_status:Does not meet the credit policy. Status:Fully Paid          0
loan_status:Fully Paid                                                  0
loan_status:In Grace Period                                             0
loan_status:Late (16-30 days)                                           0
loan_status:Late (31-120 days)                                          0
purpose:car                                                             0
purpose:credit_card                                                     0
purpose:debt_consolidation                                              0
purpose:educational                                                     0
purpose:home_improvement                                                0
purpose:house                                                           0
purpose:major_purchase                                                  0
purpose:medical                                                         0
purpose:moving                                                          0
purpose:other                                                           0
purpose:renewable_energy                                                0
purpose:small_business                                                  0
purpose:vacation                                                        0
purpose:wedding                                                         0
addr_state:AK                                                           0
addr_state:AL                                                           0
addr_state:AR                                                           0
addr_state:AZ                                                           0
addr_state:CA                                                           0
addr_state:CO                                                           0
addr_state:CT                                                           0
addr_state:DC                                                           0
addr_state:DE                                                           0
addr_state:FL                                                           0
addr_state:GA                                                           0
addr_state:HI                                                           0
addr_state:IA                                                           0
addr_state:ID                                                           0
addr_state:IL                                                           0
addr_state:IN                                                           0
addr_state:KS                                                           0
addr_state:KY                                                           0
addr_state:LA                                                           0
addr_state:MA                                                           0
addr_state:MD                                                           0
addr_state:ME                                                           0
addr_state:MI                                                           0
addr_state:MN                                                           0
addr_state:MO                                                           0
addr_state:MS                                                           0
addr_state:MT                                                           0
addr_state:NC                                                           0
addr_state:NE                                                           0
addr_state:NH                                                           0
addr_state:NJ                                                           0
addr_state:NM                                                           0
addr_state:NV                                                           0
addr_state:NY                                                           0
addr_state:OH                                                           0
addr_state:OK                                                           0
addr_state:OR                                                           0
addr_state:PA                                                           0
addr_state:RI                                                           0
addr_state:SC                                                           0
addr_state:SD                                                           0
addr_state:TN                                                           0
addr_state:TX                                                           0
addr_state:UT                                                           0
addr_state:VA                                                           0
addr_state:VT                                                           0
addr_state:WA                                                           0
addr_state:WI                                                           0
addr_state:WV                                                           0
addr_state:WY                                                           0
initial_list_status:f                                                   0
initial_list_status:w                                                   0
dtype: int64

In [44]:
pd.options.display.max_rows = 100
# Sets the pandas dataframe options to display 100 columns/ rows.

In [45]:
# 'Total revolving high credit/ credit limit', so it makes sense that the missing values are equal to funded_amnt.
loan_data['total_rev_hi_lim'].fillna(loan_data['funded_amnt'], inplace=True)
# We fill the missing values with the values of another variable.

In [46]:
loan_data['total_rev_hi_lim'].isnull().sum()

0

### Homework

In [47]:
loan_data['annual_inc'].fillna(loan_data['annual_inc'].mean(), inplace=True)
# We fill the missing values with the mean value of the non-missing values.

In [48]:
loan_data['mths_since_earliest_cr_line'].fillna(0, inplace=True)
loan_data['acc_now_delinq'].fillna(0, inplace=True)
loan_data['total_acc'].fillna(0, inplace=True)
loan_data['pub_rec'].fillna(0, inplace=True)
loan_data['open_acc'].fillna(0, inplace=True)
loan_data['inq_last_6mths'].fillna(0, inplace=True)
loan_data['delinq_2yrs'].fillna(0, inplace=True)
loan_data['emp_length_int'].fillna(0, inplace=True)
# We fill the missing values with zeroes.

# PD model

## Data preparation

### Dependent Variable. Good/ Bad (Default) Definition. Default and Non-default Accounts.

In [49]:
loan_data['loan_status'].unique()
# Displays unique values of a column.

array(['Fully Paid', 'Charged Off', 'Current', 'Default',
       'Late (31-120 days)', 'In Grace Period', 'Late (16-30 days)',
       'Does not meet the credit policy. Status:Fully Paid',
       'Does not meet the credit policy. Status:Charged Off'],
      dtype=object)

In [50]:
loan_data['loan_status'].value_counts()
# Calculates the number of observations for each unique value of a variable.

Current                                                224226
Fully Paid                                             184739
Charged Off                                             42475
Late (31-120 days)                                       6900
In Grace Period                                          3146
Does not meet the credit policy. Status:Fully Paid       1988
Late (16-30 days)                                        1218
Default                                                   832
Does not meet the credit policy. Status:Charged Off       761
Name: loan_status, dtype: int64

In [51]:
loan_data['loan_status'].value_counts() / loan_data['loan_status'].count()
# We divide the number of observations for each unique value of a variable by the total number of observations.
# Thus, we get the proportion of observations for each unique value of a variable.

Current                                                0.480878
Fully Paid                                             0.396193
Charged Off                                            0.091092
Late (31-120 days)                                     0.014798
In Grace Period                                        0.006747
Does not meet the credit policy. Status:Fully Paid     0.004263
Late (16-30 days)                                      0.002612
Default                                                0.001784
Does not meet the credit policy. Status:Charged Off    0.001632
Name: loan_status, dtype: float64

In [52]:
# Good/ Bad Definition
loan_data['good_bad'] = np.where(loan_data['loan_status'].isin(['Charged Off', 'Default',
                                                       'Does not meet the credit policy. Status:Charged Off',
                                                       'Late (31-120 days)']), 0, 1)
# We create a new variable that has the value of '0' if a condition is met, and the value of '1' if it is not met.

In [53]:
loan_data['good_bad']

0         1
1         0
2         1
3         1
4         1
         ..
466280    1
466281    0
466282    1
466283    1
466284    1
Name: good_bad, Length: 466285, dtype: int32

### Splitting Data

In [54]:
from sklearn.model_selection import train_test_split
# Imports the libraries we need.

In [55]:
train_test_split(loan_data.drop('good_bad', axis = 1), loan_data['good_bad'])
# Takes a set of inputs and a set of targets as arguments. Splits the inputs and the targets into four dataframes:
# Inputs - Train, Inputs - Test, Targets - Train, Targets - Test.

[        Unnamed: 0        id  member_id  loan_amnt  funded_amnt  \
 165316      165316   3350312    4153085      22750        22750
 382927      382927  17102967   19225504       8875         8875
 206526      206526   1434791    1686065       2000         2000
 121356      121356   5545614    6917814      10000        10000
 88997        88997   7365182    9027304      32000        32000
 ...            ...       ...        ...        ...          ...
 220536      220536   1233986    1474337      23850        23850
 69644        69644   8597653   10349641      12000        12000
 197644      197644   1537740    1803040      14125        14125
 337794      337794  22392865   24725685      15000        15000
 345001      345001  20782010   23054447      15000        15000

         funded_amnt_inv        term  int_rate  installment grade sub_grade  \
 165316          22750.0   60 months     13.11       518.92     B        B4
 382927           8875.0   36 months     14.99       307.62     C        C5
 206526           2000.0   36 months     14.09        68.45     B        B5
 121356          10000.0   36 months     13.68       340.23     C        C1
 88997           32000.0   36 months     20.20      1192.50     D        D5
 ...                 ...         ...       ...          ...   ...       ...
 220536          23850.0   36 months      9.76       766.89     B        B1
 69644           12000.0   36 months     10.99       392.81     B        B2
 197644          14125.0   36 months     12.12       469.97     B        B3
 337794          15000.0   36 months     10.15       485.07     B        B2
 345001          15000.0   36 months     11.67       495.86     B        B4

                                      emp_title emp_length home_ownership  \
 165316  Georgia Department of Juvenile Justice  10+ years       MORTGAGE
 382927                        Business Analyst    5 years           RENT
 206526                 Department of Workforce    4 years       MORTGAGE
 121356                               Panasonic    5 years       MORTGAGE
 88997                   Metrolplex Dermatology    2 years       MORTGAGE
 ...                                        ...        ...            ...
 220536                     Summer Classics Inc    5 years            OWN
 69644                          Super Intendent    7 years           RENT
 197644                              ING Direct    6 years            OWN
 337794                        Registered Nurse  10+ years           RENT
 345001                             Housekeeper    3 years       MORTGAGE

         annual_inc verification_status issue_d  loan_status pymnt_plan  \
 165316     71000.0            Verified  Feb-13   Fully Paid          n
 382927     52000.0     Source Verified  May-14  Charged Off          n
 206526     27000.0            Verified  Aug-12  Charged Off          n
 121356    160000.0        Not Verified  Jul-13      Current          n
 88997      90000.0     Source Verified  Sep-13   Fully Paid          n
 ...            ...                 ...     ...          ...        ...
 220536     64000.0        Not Verified  Apr-12   Fully Paid          n
 69644      80000.0     Source Verified  Nov-13   Fully Paid          n
 197644     45000.0            Verified  Sep-12   Fully Paid          n
 337794     70000.0        Not Verified  Jul-14   Fully Paid          n
 345001     54000.0        Not Verified  Jul-14      Current          n

                                                       url  \
 165316  https://www.lendingclub.com/browse/loanDetail....
 382927  https://www.lendingclub.com/browse/loanDetail....
 206526  https://www.lendingclub.com/browse/loanDetail....
 121356  https://www.lendingclub.com/browse/loanDetail....
 88997   https://www.lendingclub.com/browse/loanDetail....
 ...                                                   ...
 220536  https://www.lendingclub.com/browse/loanDetail....
 69644   https://www.lendingclub.com/browse/loanDetail....
 197644  https://www.lendingclub.com/browse/loanDetail....
 337794  https://www.lendingclub.com/browse/loanDetail....
 345001  https://www.lendingclub.com/browse/loanDetail....

                                                      desc             purpose  \
 165316                                                NaN  debt_consolidation
 382927                                                NaN               other
 206526    Borrower added on 07/23/12 > I would like to...               other
 121356                                                NaN         credit_card
 88997                                                 NaN  debt_consolidation
 ...                                                   ...                 ...
 220536    Borrower added on 04/11/12 > We are getting ...               house
 69644     Borrower added on 10/28/13 > Trying to conso...  debt_consolidation
 197644                                                NaN  debt_consolidation
 337794                                                NaN  debt_consolidation
 345001                                                NaN  debt_consolidation

                           title zip_code addr_state    dti  delinq_2yrs  \
 165316                  no debt    319xx         GA  12.54          0.0
 382927                    Other    372xx         TN  10.73          0.0
 206526                Surburban    720xx         AR  33.51          0.0
 121356  Credit card refinancing    201xx         VA  10.10          1.0
 88997   debt consolidation loan    750xx         TX  22.53          0.0
 ...                         ...      ...        ...    ...          ...
 220536   Vacation Home Purchase    350xx         AL  28.48          0.0
 69644             Consolidation    983xx         WA  12.77          0.0
 197644                    Title    563xx         MN  29.44          0.0
 337794       Debt consolidation    120xx         NY  17.92          0.0
 345001       Debt consolidation    824xx         WY   8.29          0.0

        earliest_cr_line  inq_last_6mths  mths_since_last_delinq  \
 165316           Mar-94             0.0                    25.0
 382927           Apr-98             3.0                     NaN
 206526           Dec-02             1.0                     NaN
 121356           Dec-94             0.0                    13.0
 88997            Jun-98             2.0                    33.0
 ...                 ...             ...                     ...
 220536           May-96             4.0                     NaN
 69644            Oct-03             0.0                     NaN
 197644           Mar-03             0.0                     NaN
 337794           Jul-94             1.0                     NaN
 345001           Nov-05             0.0                     NaN

         mths_since_last_record  open_acc  pub_rec  revol_bal  revol_util  \
 165316                     NaN      13.0      0.0       5109        12.9
 382927                     NaN       7.0      0.0       4243        81.6
 206526                     NaN       6.0      0.0       2432        86.9
 121356                     NaN       8.0      0.0       5148        87.3
 88997                      NaN      18.0      0.0      47472        75.2
 ...                        ...       ...      ...        ...         ...
 220536                     NaN      22.0      0.0      19058        24.0
 69644                      NaN       9.0      0.0      10746        54.8
 197644                     NaN      13.0      0.0      18787        67.6
 337794                   106.0      13.0      1.0       7494        70.7
 345001                     NaN       8.0      0.0       8051        49.1

         total_acc initial_list_status  out_prncp  out_prncp_inv  total_pymnt  \
 165316       27.0                   w        0.0            0.0  23486.87000
 382927        9.0                   w        0.0            0.0   2153.34000
 206526       13.0                   f        0.0            0.0    885.95000
 121356       30.0                   w     1962.1         1962.1  10206.90000
 88997        30.0                   f        0.0            0.0  34087.79000
 ...           ...                 ...        ...            ...          ...
 220536       61.0                   f        0.0            0.0  27084.95326
 69644        21.0                   w        0.0            0.0  13592.89000
 197644       26.0                   f        0.0            0.0  15398.57000
 337794       22.0                   f        0.0            0.0  16567.58000
 345001       10.0                   f     8151.5         8151.5   8925.48000

         total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  \
 165316         23486.87         22750.00         736.87                 0.0
 382927          2153.34          1334.35         818.99                 0.0
 206526           885.95           624.83         261.12                 0.0
 121356         10206.90          8037.90        2169.00                 0.0
 88997          34087.79         32000.00        2087.79                 0.0
 ...                 ...              ...            ...                 ...
 220536         27084.95         23850.00        3234.95                 0.0
 69644          13592.89         12000.00        1592.89                 0.0
 197644         15398.57         14125.00        1273.57                 0.0
 337794         16567.58         15000.00        1567.58                 0.0
 345001          8925.48          6848.50        2076.98                 0.0

         recoveries  collection_recovery_fee last_pymnt_d  last_pymnt_amnt  \
 165316         0.0                      0.0       May-13         22451.30
 382927         0.0                      0.0       Jan-15           307.62
 206526         0.0                      0.0       Sep-13            68.45
 121356         0.0                      0.0       Jan-16           340.23
 88997          0.0                      0.0       Feb-14         30511.02
 ...            ...                      ...          ...              ...
 220536         0.0                      0.0       Jul-14           163.55
 69644          0.0                      0.0       May-15          6915.12
 197644         0.0                      0.0       Aug-13         11169.93
 337794         0.0                      0.0       Sep-15         10261.67
 345001         0.0                      0.0       Jan-16           495.86

        next_pymnt_d last_credit_pull_d  collections_12_mths_ex_med  \
 165316          NaN             Sep-14                         0.0
 382927          NaN             Jan-16                         0.0
 206526          NaN             Jan-16                         0.0
 121356       Feb-16             Jan-16                         0.0
 88997           NaN             Mar-14                         0.0
 ...             ...                ...                         ...
 220536          NaN             Sep-15                         0.0
 69644           NaN             May-15                         0.0
 197644          NaN             Nov-13                         0.0
 337794          NaN             Jan-16                         0.0
 345001       Feb-16             Jan-16                         0.0

         mths_since_last_major_derog  policy_code application_type  \
 165316                         25.0            1       INDIVIDUAL
 382927                          NaN            1       INDIVIDUAL
 206526                          NaN            1       INDIVIDUAL
 121356                          NaN            1       INDIVIDUAL
 88997                           NaN            1       INDIVIDUAL
 ...                             ...          ...              ...
 220536                          NaN            1       INDIVIDUAL
 69644                           NaN            1       INDIVIDUAL
 197644                          NaN            1       INDIVIDUAL
 337794                          NaN            1       INDIVIDUAL
 345001                          NaN            1       INDIVIDUAL

         annual_inc_joint  dti_joint  verification_status_joint  \
 165316               NaN        NaN                        NaN
 382927               NaN        NaN                        NaN
 206526               NaN        NaN                        NaN
 121356               NaN        NaN                        NaN
 88997                NaN        NaN                        NaN
 ...                  ...        ...                        ...
 220536               NaN        NaN                        NaN
 69644                NaN        NaN                        NaN
 197644               NaN        NaN                        NaN
 337794               NaN        NaN                        NaN
 345001               NaN        NaN                        NaN

         acc_now_delinq  tot_coll_amt  tot_cur_bal  open_acc_6m  open_il_6m  \
 165316             0.0           0.0     150987.0          NaN         NaN
 382927             0.0           0.0      15582.0          NaN         NaN
 206526             0.0           NaN          NaN          NaN         NaN
 121356             0.0           0.0     477257.0          NaN         NaN
 88997              0.0           0.0     174673.0          NaN         NaN
 ...                ...           ...          ...          ...         ...
 220536             0.0           NaN          NaN          NaN         NaN
 69644              0.0           0.0      21046.0          NaN         NaN
 197644             0.0           0.0     175554.0          NaN         NaN
 337794             0.0           0.0      96462.0          NaN         NaN
 345001             0.0           0.0      61355.0          NaN         NaN

         open_il_12m  open_il_24m  mths_since_rcnt_il  total_bal_il  il_util  \
 165316          NaN          NaN                 NaN           NaN      NaN
 382927          NaN          NaN                 NaN           NaN      NaN
 206526          NaN          NaN                 NaN           NaN      NaN
 121356          NaN          NaN                 NaN           NaN      NaN
 88997           NaN          NaN                 NaN           NaN      NaN
 ...             ...          ...                 ...           ...      ...
 220536          NaN          NaN                 NaN           NaN      NaN
 69644           NaN          NaN                 NaN           NaN      NaN
 197644          NaN          NaN                 NaN           NaN      NaN
 337794          NaN          NaN                 NaN           NaN      NaN
 345001          NaN          NaN                 NaN           NaN      NaN

         open_rv_12m  open_rv_24m  max_bal_bc  all_util  total_rev_hi_lim  \
 165316          NaN          NaN         NaN       NaN           39700.0
 382927          NaN          NaN         NaN       NaN            5200.0
 206526          NaN          NaN         NaN       NaN            2000.0
 121356          NaN          NaN         NaN       NaN            5900.0
 88997           NaN          NaN         NaN       NaN           63500.0
 ...             ...          ...         ...       ...               ...
 220536          NaN          NaN         NaN       NaN           23850.0
 69644           NaN          NaN         NaN       NaN           19600.0
 197644          NaN          NaN         NaN       NaN           27800.0
 337794          NaN          NaN         NaN       NaN           10600.0
 345001          NaN          NaN         NaN       NaN           16400.0

         inq_fi  total_cu_tl  inq_last_12m  emp_length_int  \
 165316     NaN          NaN           NaN            10.0
 382927     NaN          NaN           NaN             5.0
 206526     NaN          NaN           NaN             4.0
 121356     NaN          NaN           NaN             5.0
 88997      NaN          NaN           NaN             2.0
 ...        ...          ...           ...             ...
 220536     NaN          NaN           NaN             5.0
 69644      NaN          NaN           NaN             7.0
 197644     NaN          NaN           NaN             6.0
 337794     NaN          NaN           NaN            10.0
 345001     NaN          NaN           NaN             3.0

        earliest_cr_line_date  mths_since_earliest_cr_line  term_int  \
 165316            1994-03-01                        285.0        60
 382927            1998-04-01                        236.0        36
 206526            2002-12-01                        180.0        36
 121356            1994-12-01                        276.0        36
 88997             1998-06-01                        234.0        36
 ...                      ...                          ...       ...
 220536            1996-05-01                        259.0        36
 69644             2003-10-01                        170.0        36
 197644            2003-03-01                        177.0        36
 337794            1994-07-01                        281.0        36
 345001            2005-11-01                        145.0        36

        issue_d_date  mths_since_issue_d  grade:A  grade:B  grade:C  grade:D  \
 165316   2013-02-01                58.0        0        1        0        0
 382927   2014-05-01                43.0        0        0        1        0
 206526   2012-08-01                64.0        0        1        0        0
 121356   2013-07-01                53.0        0        0        1        0
 88997    2013-09-01                51.0        0        0        0        1
 ...             ...                 ...      ...      ...      ...      ...
 220536   2012-04-01                68.0        0        1        0        0
 69644    2013-11-01                49.0        0        1        0        0
 197644   2012-09-01                63.0        0        1        0        0
 337794   2014-07-01                41.0        0        1        0        0
 345001   2014-07-01                41.0        0        1        0        0

         grade:E  grade:F  grade:G  sub_grade:A1  sub_grade:A2  sub_grade:A3  \
 165316        0        0        0             0             0             0
 382927        0        0        0             0             0             0
 206526        0        0        0             0             0             0
 121356        0        0        0             0             0             0
 88997         0        0        0             0             0             0
 ...         ...      ...      ...           ...           ...           ...
 220536        0        0        0             0             0             0
 69644         0        0        0             0             0             0
 197644        0        0        0             0             0             0
 337794        0        0        0             0             0             0
 345001        0        0        0             0             0             0

         sub_grade:A4  sub_grade:A5  sub_grade:B1  sub_grade:B2  sub_grade:B3  \
 165316             0             0             0             0             0
 382927             0             0             0             0             0
 206526             0             0             0             0             0
 121356             0             0             0             0             0
 88997              0             0             0             0             0
 ...              ...           ...           ...           ...           ...
 220536             0             0             1             0             0
 69644              0             0             0             1             0
 197644             0             0             0             0             1
 337794             0             0             0             1             0
 345001             0             0             0             0             0


In [56]:
loan_data_inputs_train, loan_data_inputs_test, loan_data_targets_train, loan_data_targets_test = train_test_split(loan_data.drop('good_bad', axis = 1), loan_data['good_bad'])
# We split two dataframes with inputs and targets, each into a train and test dataframe, and store them in variables.

In [57]:
loan_data_inputs_train.shape
# Displays the size of the dataframe.

(349713, 207)

In [58]:
loan_data_targets_train.shape
# Displays the size of the dataframe.

(349713,)

In [59]:
loan_data_inputs_test.shape
# Displays the size of the dataframe.

(116572, 207)

In [60]:
loan_data_targets_test.shape
# Displays the size of the dataframe.

(116572,)

In [61]:
loan_data_inputs_train, loan_data_inputs_test, loan_data_targets_train, loan_data_targets_test = train_test_split(loan_data.drop('good_bad', axis = 1), loan_data['good_bad'], test_size = 0.2, random_state = 42)
# We split two dataframes with inputs and targets, each into a train and test dataframe, and store them in variables.
# This time we set the size of the test dataset to be 20%.
# Respectively, the size of the train dataset becomes 80%.
# We also set a specific random state.
# This would allow us to perform the exact same split multimple times.
# This means, to assign the exact same observations to the train and test datasets.

In [62]:
loan_data_inputs_train.shape
# Displays the size of the dataframe.

(373028, 207)

In [63]:
loan_data_targets_train.shape
# Displays the size of the dataframe.

(373028,)

In [64]:
loan_data_inputs_test.shape
# Displays the size of the dataframe.

(93257, 207)

In [65]:
loan_data_targets_test.shape
# Displays the size of the dataframe.

(93257,)

### Data Preparation: An Example

In [66]:
#####
#df_inputs_prepr = loan_data_inputs_train
#df_targets_prepr = loan_data_targets_train
#####
df_inputs_prepr = loan_data_inputs_test
df_targets_prepr = loan_data_targets_test

In [67]:
df_inputs_prepr['grade'].unique()
# Displays unique values of a column.

array(['C', 'E', 'A', 'D', 'B', 'F', 'G'], dtype=object)

In [68]:
df1 = pd.concat([df_inputs_prepr['grade'], df_targets_prepr], axis = 1)
# Concatenates two dataframes along the columns.
df1.head()

       grade  good_bad
362514     C         1
288564     E         1
213591     C         1
263083     C         1
165001     A         1

In [69]:
df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].count()
# Groups the data according to a criterion contained in one column.
# Does not turn the names of the values of the criterion as indexes.
# Aggregates the data in another column, using a selected function.
# In this specific case, we group by the column with index 0 and we aggregate the values of the column with index 1.
# More specifically, we count them.
# In other words, we count the values in the column with index 1 for each value of the column with index 0.

  grade  good_bad
0     A     15108
1     B     27199
2     C     25048
3     D     15390
4     E      7145
5     F      2699
6     G       668

In [70]:
df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].mean()
# Groups the data according to a criterion contained in one column.
# Does not turn the names of the values of the criterion as indexes.
# Aggregates the data in another column, using a selected function.
# Here we calculate the mean of the values in the column with index 1 for each value of the column with index 0.

  grade  good_bad
0     A  0.962338
1     B  0.923085
2     C  0.882905
3     D  0.844314
4     E  0.805178
5     F  0.775472
6     G  0.697605

In [71]:
df1 = pd.concat([df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].count(),
                df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].mean()], axis = 1)
# Concatenates two dataframes along the columns.

In [72]:
df1

  grade  good_bad grade  good_bad
0     A     15108     A  0.962338
1     B     27199     B  0.923085
2     C     25048     C  0.882905
3     D     15390     D  0.844314
4     E      7145     E  0.805178
5     F      2699     F  0.775472
6     G       668     G  0.697605

In [73]:
df1 = df1.iloc[:, [0, 1, 3]]
# Selects only columns with specific indexes.
df1

  grade  good_bad  good_bad
0     A     15108  0.962338
1     B     27199  0.923085
2     C     25048  0.882905
3     D     15390  0.844314
4     E      7145  0.805178
5     F      2699  0.775472
6     G       668  0.697605

In [74]:
df1.columns = [df1.columns.values[0], 'n_obs', 'prop_good']
# Changes the names of the columns of a dataframe.
df1

  grade  n_obs  prop_good
0     A  15108   0.962338
1     B  27199   0.923085
2     C  25048   0.882905
3     D  15390   0.844314
4     E   7145   0.805178
5     F   2699   0.775472
6     G    668   0.697605

In [75]:
df1['prop_n_obs'] = df1['n_obs'] / df1['n_obs'].sum()
# We divide the values of one column by he values of another column and save the result in a new variable.
df1

  grade  n_obs  prop_good  prop_n_obs
0     A  15108   0.962338    0.162004
1     B  27199   0.923085    0.291656
2     C  25048   0.882905    0.268591
3     D  15390   0.844314    0.165028
4     E   7145   0.805178    0.076616
5     F   2699   0.775472    0.028942
6     G    668   0.697605    0.007163

In [76]:
df1['n_good'] = df1['prop_good'] * df1['n_obs']
# We multiply the values of one column by he values of another column and save the result in a new variable.
df1['n_bad'] = (1 - df1['prop_good']) * df1['n_obs']
df1

  grade  n_obs  prop_good  prop_n_obs   n_good   n_bad
0     A  15108   0.962338    0.162004  14539.0   569.0
1     B  27199   0.923085    0.291656  25107.0  2092.0
2     C  25048   0.882905    0.268591  22115.0  2933.0
3     D  15390   0.844314    0.165028  12994.0  2396.0
4     E   7145   0.805178    0.076616   5753.0  1392.0
5     F   2699   0.775472    0.028942   2093.0   606.0
6     G    668   0.697605    0.007163    466.0   202.0

In [77]:
df1['prop_n_good'] = df1['n_good'] / df1['n_good'].sum()
df1['prop_n_bad'] = df1['n_bad'] / df1['n_bad'].sum()
df1

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad
0,A,15108,0.962338,0.162004,14539.0,569.0,0.175027,0.055839
1,B,27199,0.923085,0.291656,25107.0,2092.0,0.302250,0.205299
2,C,25048,0.882905,0.268591,22115.0,2933.0,0.266231,0.287831
3,D,15390,0.844314,0.165028,12994.0,2396.0,0.156428,0.235132
4,E,7145,0.805178,0.076616,5753.0,1392.0,0.069257,0.136605
5,F,2699,0.775472,0.028942,2093.0,606.0,0.025197,0.059470
6,G,668,0.697605,0.007163,466.0,202.0,0.005610,0.019823

In [78]:
df1['WoE'] = np.log(df1['prop_n_good'] / df1['prop_n_bad'])
# We take the natural logarithm of a variable and save the result in a nex variable.
df1

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE
0,A,15108,0.962338,0.162004,14539.0,569.0,0.175027,0.055839,1.142469
1,B,27199,0.923085,0.291656,25107.0,2092.0,0.302250,0.205299,0.386785
2,C,25048,0.882905,0.268591,22115.0,2933.0,0.266231,0.287831,-0.078010
3,D,15390,0.844314,0.165028,12994.0,2396.0,0.156428,0.235132,-0.407554
4,E,7145,0.805178,0.076616,5753.0,1392.0,0.069257,0.136605,-0.679261
5,F,2699,0.775472,0.028942,2093.0,606.0,0.025197,0.059470,-0.858767
6,G,668,0.697605,0.007163,466.0,202.0,0.005610,0.019823,-1.262323

In [79]:
df1 = df1.sort_values(['WoE'])
# Sorts a dataframe by the values of a given column.
df1 = df1.reset_index(drop = True)
# We reset the index of a dataframe and overwrite it.
df1

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE
0,G,668,0.697605,0.007163,466.0,202.0,0.005610,0.019823,-1.262323
1,F,2699,0.775472,0.028942,2093.0,606.0,0.025197,0.059470,-0.858767
2,E,7145,0.805178,0.076616,5753.0,1392.0,0.069257,0.136605,-0.679261
3,D,15390,0.844314,0.165028,12994.0,2396.0,0.156428,0.235132,-0.407554
4,C,25048,0.882905,0.268591,22115.0,2933.0,0.266231,0.287831,-0.078010
5,B,27199,0.923085,0.291656,25107.0,2092.0,0.302250,0.205299,0.386785
6,A,15108,0.962338,0.162004,14539.0,569.0,0.175027,0.055839,1.142469

In [80]:
df1['diff_prop_good'] = df1['prop_good'].diff().abs()
# We take the difference between two subsequent values of a column. Then, we take the absolute value of the result.
df1['diff_WoE'] = df1['WoE'].diff().abs()
# We take the difference between two subsequent values of a column. Then, we take the absolute value of the result.
df1

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE
0,G,668,0.697605,0.007163,466.0,202.0,0.005610,0.019823,-1.262323,NaN,NaN
1,F,2699,0.775472,0.028942,2093.0,606.0,0.025197,0.059470,-0.858767,0.077868,0.403556
2,E,7145,0.805178,0.076616,5753.0,1392.0,0.069257,0.136605,-0.679261,0.029706,0.179506
3,D,15390,0.844314,0.165028,12994.0,2396.0,0.156428,0.235132,-0.407554,0.039136,0.271707
4,C,25048,0.882905,0.268591,22115.0,2933.0,0.266231,0.287831,-0.078010,0.038590,0.329543
5,B,27199,0.923085,0.291656,25107.0,2092.0,0.302250,0.205299,0.386785,0.040181,0.464796
6,A,15108,0.962338,0.162004,14539.0,569.0,0.175027,0.055839,1.142469,0.039252,0.755683

In [81]:
df1['IV'] = (df1['prop_n_good'] - df1['prop_n_bad']) * df1['WoE']
df1['IV'] = df1['IV'].sum()
# We sum all values of a given column.
df1

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,G,668,0.697605,0.007163,466.0,202.0,0.005610,0.019823,-1.262323,NaN,NaN,0.300551
1,F,2699,0.775472,0.028942,2093.0,606.0,0.025197,0.059470,-0.858767,0.077868,0.403556,0.300551
2,E,7145,0.805178,0.076616,5753.0,1392.0,0.069257,0.136605,-0.679261,0.029706,0.179506,0.300551
3,D,15390,0.844314,0.165028,12994.0,2396.0,0.156428,0.235132,-0.407554,0.039136,0.271707,0.300551
4,C,25048,0.882905,0.268591,22115.0,2933.0,0.266231,0.287831,-0.078010,0.038590,0.329543,0.300551
5,B,27199,0.923085,0.291656,25107.0,2092.0,0.302250,0.205299,0.386785,0.040181,0.464796,0.300551
6,A,15108,0.962338,0.162004,14539.0,569.0,0.175027,0.055839,1.142469,0.039252,0.755683,0.300551

### Preprocessing Discrete Variables: Automating Calculaions

In [82]:
# WoE function for discrete unordered variables
def woe_discrete(df, discrete_variabe_name, good_bad_variable_df):
    df = pd.concat([df[discrete_variabe_name], good_bad_variable_df], axis = 1)
    df = pd.concat([df.groupby(df.columns.values[0], as_index = False)[df.columns.values[1]].count(),
                    df.groupby(df.columns.values[0], as_index = False)[df.columns.values[1]].mean()], axis = 1)
    df = df.iloc[:, [0, 1, 3]]
    df.columns = [df.columns.values[0], 'n_obs', 'prop_good']
    df['prop_n_obs'] = df['n_obs'] / df['n_obs'].sum()
    df['n_good'] = df['prop_good'] * df['n_obs']
    df['n_bad'] = (1 - df['prop_good']) * df['n_obs']
    df['prop_n_good'] = df['n_good'] / df['n_good'].sum()
    df['prop_n_bad'] = df['n_bad'] / df['n_bad'].sum()
    df['WoE'] = np.log(df['prop_n_good'] / df['prop_n_bad'])
    df = df.sort_values(['WoE'])
    df = df.reset_index(drop = True)
    df['diff_prop_good'] = df['prop_good'].diff().abs()
    df['diff_WoE'] = df['WoE'].diff().abs()
    df['IV'] = (df['prop_n_good'] - df['prop_n_bad']) * df['WoE']
    df['IV'] = df['IV'].sum()
    return df
# Here we combine all of the operations above in a function.
# The function takes 3 arguments: a dataframe, a string, and a dataframe. The function returns a dataframe as a result.

In [83]:
# 'grade'
df_temp = woe_discrete(df_inputs_prepr, 'grade', df_targets_prepr)
# We execute the function we defined with the necessary arguments: a dataframe, a string, and a dataframe.
# We store the result in a dataframe.
df_temp

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,G,668,0.697605,0.007163,466.0,202.0,0.005610,0.019823,-1.262323,NaN,NaN,0.300551
1,F,2699,0.775472,0.028942,2093.0,606.0,0.025197,0.059470,-0.858767,0.077868,0.403556,0.300551
2,E,7145,0.805178,0.076616,5753.0,1392.0,0.069257,0.136605,-0.679261,0.029706,0.179506,0.300551
3,D,15390,0.844314,0.165028,12994.0,2396.0,0.156428,0.235132,-0.407554,0.039136,0.271707,0.300551
4,C,25048,0.882905,0.268591,22115.0,2933.0,0.266231,0.287831,-0.078010,0.038590,0.329543,0.300551
5,B,27199,0.923085,0.291656,25107.0,2092.0,0.302250,0.205299,0.386785,0.040181,0.464796,0.300551
6,A,15108,0.962338,0.162004,14539.0,569.0,0.175027,0.055839,1.142469,0.039252,0.755683,0.300551

### Preprocessing Discrete Variables: Visualizing Results

In [84]:
import matplotlib.pyplot as plt
import seaborn as sns
# Imports the libraries we need.
sns.set()
# We set the default style of the graphs to the seaborn style.

In [85]:
# Below we define a function that takes 2 arguments: a dataframe and a number.
# The number parameter has a default value of 0.
# This means that if we call the function and omit the number parameter, it will be executed with it having a value of 0.
# The function displays a graph.
def plot_by_woe(df_WoE, rotation_of_x_axis_labels = 0):
    x = np.array(df_WoE.iloc[:, 0].apply(str))
    # Turns the values of the column with index 0 to strings, makes an array from these strings, and passes it to variable x.
    y = df_WoE['WoE']
    # Selects a column with label 'WoE' and passes it to variable y.
    plt.figure(figsize=(18, 6))
    # Sets the graph size to width 18 x height 6.
    plt.plot(x, y, marker = 'o', linestyle = '--', color = 'k')
    # Plots the datapoints with coordiantes variable x on the x-axis and variable y on the y-axis.
    # Sets the marker for each datapoint to a circle, the style line between the points to dashed, and the color to black.
    plt.xlabel(df_WoE.columns[0])
    # Names the x-axis with the name of the column with index 0.
    plt.ylabel('Weight of Evidence')
    # Names the y-axis 'Weight of Evidence'.
    plt.title(str('Weight of Evidence by ' + df_WoE.columns[0]))
    # Names the grapth 'Weight of Evidence by ' the name of the column with index 0.
    plt.xticks(rotation = rotation_of_x_axis_labels)
    # Rotates the labels of the x-axis a predefined number of degrees.

In [86]:
plot_by_woe(df_temp)
# We execute the function we defined with the necessary arguments: a dataframe.
# We omit the number argument, which means the function will use its default value, 0.

### Preprocessing Discrete Variables: Creating Dummy Variables, Part 1

In [87]:
# 'home_ownership'
df_temp = woe_discrete(df_inputs_prepr, 'home_ownership', df_targets_prepr)
# We calculate weight of evidence.
df_temp

,home_ownership,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,OTHER,45,0.777778,0.000483,35.0,10.0,0.000421,0.000981,-0.845478,NaN,NaN,0.022938
1,NONE,10,0.800000,0.000107,8.0,2.0,0.000096,0.000196,-0.711946,0.022222,0.133531,0.022938
2,RENT,37874,0.874003,0.406125,33102.0,4772.0,0.398498,0.468302,-0.161412,0.074003,0.550534,0.022938
3,OWN,8409,0.888572,0.090170,7472.0,937.0,0.089951,0.091953,-0.022006,0.014568,0.139406,0.022938
4,MORTGAGE,46919,0.904751,0.503115,42450.0,4469.0,0.511033,0.438567,0.152922,0.016179,0.174928,0.022938

In [88]:
plot_by_woe(df_temp)
# We plot the weight of evidence values.

In [89]:
# There are many categories with very few observations and many categories with very different "good" %.
# Therefore, we create a new discrete variable where we combine some of the categories.
# 'OTHERS' and 'NONE' are riskiest but are very few. 'RENT' is the next riskiest.
# 'ANY' are least risky but are too few. Conceptually, they belong to the same category. Also, their inclusion would not change anything.
# We combine them in one category, 'RENT_OTHER_NONE_ANY'.
# We end up with 3 categories: 'RENT_OTHER_NONE_ANY', 'OWN', 'MORTGAGE'.
df_inputs_prepr['home_ownership:RENT_OTHER_NONE_ANY'] = sum([df_inputs_prepr['home_ownership:RENT'], df_inputs_prepr['home_ownership:OTHER'],
                                                      df_inputs_prepr['home_ownership:NONE'],df_inputs_prepr['home_ownership:ANY']])
# 'RENT_OTHER_NONE_ANY' will be the reference category.

# Alternatively:
#loan_data.loc['home_ownership' in ['RENT', 'OTHER', 'NONE', 'ANY'], 'home_ownership:RENT_OTHER_NONE_ANY'] = 1
#loan_data.loc['home_ownership' not in ['RENT', 'OTHER', 'NONE', 'ANY'], 'home_ownership:RENT_OTHER_NONE_ANY'] = 0
#loan_data.loc['loan_status' not in ['OWN'], 'home_ownership:OWN'] = 1
#loan_data.loc['loan_status' not in ['OWN'], 'home_ownership:OWN'] = 0
#loan_data.loc['loan_status' not in ['MORTGAGE'], 'home_ownership:MORTGAGE'] = 1
#loan_data.loc['loan_status' not in ['MORTGAGE'], 'home_ownership:MORTGAGE'] = 0

### Preprocessing Discrete Variables: Creating Dummy Variables, Part 2

In [90]:
# 'addr_state'
df_inputs_prepr['addr_state'].unique()

array(['CA', 'IN', 'AZ', 'MI', 'PA', 'MO', 'CT', 'IL', 'SC', 'VA', 'NY',
       'FL', 'TX', 'NC', 'NM', 'NJ', 'KY', 'DE', 'OK', 'CO', 'OH', 'GA',
       'LA', 'WA', 'AL', 'TN', 'MD', 'NV', 'MN', 'RI', 'NH', 'MA', 'MS',
       'UT', 'WV', 'HI', 'KS', 'OR', 'WY', 'WI', 'AK', 'DC', 'AR', 'MT',
       'SD', 'VT', 'IA', 'ID', 'ME', 'NE'], dtype=object)

In [91]:
df_temp = woe_discrete(df_inputs_prepr, 'addr_state', df_targets_prepr)
# We calculate weight of evidence.
df_temp

C:\Users\Sanket\Anaconda4\lib\site-packages\pandas\core\series.py:679: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\Sanket\Anaconda4\lib\site-packages\pandas\core\algorithms.py:1926: RuntimeWarning: invalid value encountered in subtract
  out_arr[res_indexer] = arr[res_indexer] - arr[lag_indexer]

,addr_state,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,NE,1,0.000000,0.000011,0.0,1.0,0.000000,0.000098,-inf,NaN,NaN,inf
1,ID,2,0.500000,0.000021,1.0,1.0,0.000012,0.000098,-2.098241,0.500000,inf,inf
2,NV,1298,0.855932,0.013919,1111.0,187.0,0.013375,0.018351,-0.316333,0.355932,1.781907,inf
3,HI,486,0.860082,0.005211,418.0,68.0,0.005032,0.006673,-0.282267,0.004150,0.034067,inf
4,FL,6426,0.870059,0.068906,5591.0,835.0,0.067307,0.081943,-0.196759,0.009977,0.085508,inf
5,AL,1182,0.873096,0.012675,1032.0,150.0,0.012424,0.014720,-0.169622,0.003037,0.027137,inf
6,NJ,3676,0.875408,0.039418,3218.0,458.0,0.038740,0.044946,-0.148595,0.002312,0.021027,inf
7,LA,1130,0.876106,0.012117,990.0,140.0,0.011918,0.013739,-0.142178,0.000698,0.006416,inf
8,NY,8031,0.879965,0.086117,7067.0,964.0,0.085076,0.094603,-0.106141,0.003859,0.036038,inf
9,RI,403,0.880893,0.004321,355.0,48.0,0.004274,0.004711,-0.097324,0.000928,0.008817,inf
10,NC,2478,0.881759,0.026572,2185.0,293.0,0.026304,0.028754,-0.089042,0.000866,0.008282,inf
11,MI,2358,0.882103,0.025285,2080.0,278.0,0.025040,0.027282,-0.085739,0.000344,0.003304,inf
12,DE,208,0.884615,0.002230,184.0,24.0,0.002215,0.002355,-0.061359,0.002512,0.024380,inf
13,MD,2203,0.884703,0.023623,1949.0,254.0,0.023463,0.024926,-0.060503,0.000087,0.000856,inf
14,OK,833,0.885954,0.008932,738.0,95.0,0.008884,0.009323,-0.048174,0.001252,0.012330,inf
15,MO,1491,0.885983,0.015988,1321.0,170.0,0.015903,0.016683,-0.047895,0.000028,0.000279,inf
16,AR,728,0.887363,0.007806,646.0,82.0,0.007777,0.008047,-0.034160,0.001380,0.013734,inf
17,PA,3334,0.888122,0.035751,2961.0,373.0,0.035646,0.036605,-0.026537,0.000760,0.007624,inf
18,SD,179,0.888268,0.001919,159.0,20.0,0.001914,0.001963,-0.025069,0.000146,0.001468,inf
19,AZ,2067,0.888728,0.022165,1837.0,230.0,0.022115,0.022571,-0.020431,0.000459,0.004638,inf
20,NM,513,0.888889,0.005501,456.0,57.0,0.005490,0.005594,-0.018799,0.000161,0.001632,inf
21,CA,14251,0.889411,0.152814,12675.0,1576.0,0.152588,0.154661,-0.013499,0.000522,0.005300,inf
22,MA,2214,0.893857,0.023741,1979.0,235.0,0.023824,0.023062,0.032521,0.004446,0.046020,inf
23,GA,3015,0.893864,0.032330,2695.0,320.0,0.032444,0.031403,0.032592,0.000007,0.000071,inf
24,IN,1315,0.894297,0.014101,1176.0,139.0,0.014157,0.013641,0.037160,0.000433,0.004568,inf
25,VA,2856,0.894958,0.030625,2556.0,300.0,0.030770,0.029441,0.044176,0.000661,0.007016,inf
26,NH,402,0.895522,0.004311,360.0,42.0,0.004334,0.004122,0.050194,0.000564,0.006018,inf
27,OH,3102,0.895551,0.033263,2778.0,324.0,0.033443,0.031796,0.050502,0.000029,0.000309,inf
28,UT,672,0.895833,0.007206,602.0,70.0,0.007247,0.006869,0.053522,0.000282,0.003019,inf
29,WI,1171,0.896670,0.012557,1050.0,121.0,0.012640,0.011874,0.062514,0.000836,0.008993,inf
30,MN,1632,0.897059,0.017500,1464.0,168.0,0.017624,0.016487,0.066723,0.000389,0.004209,inf
31,WA,2145,0.899767,0.023001,1930.0,215.0,0.023234,0.021099,0.096397,0.002708,0.029674,inf
32,CO,1916,0.906054,0.020545,1736.0,180.0,0.020899,0.017664,0.168141,0.006287,0.071745,inf
33,TX,7281,0.906057,0.078075,6597.0,684.0,0.079418,0.067125,0.168172,0.000003,0.000030,inf
34,SC,1135,0.906608,0.012171,1029.0,106.0,0.012388,0.010402,0.174663,0.000551,0.006491,inf
35,TN,1139,0.906936,0.012214,1033.0,106.0,0.012436,0.010402,0.178543,0.000328,0.003880,inf
36,OR,1135,0.907489,0.012171,1030.0,105.0,0.012400,0.010304,0.185113,0.000553,0.006570,inf
37,IL,3779,0.908706,0.040522,3434.0,345.0,0.041340,0.033857,0.199696,0.001217,0.014583,inf
38,KY,851,0.909518,0.009125,774.0,77.0,0.009318,0.007556,0.209526,0.000812,0.009830,inf
39,CT,1429,0.909727,0.015323,1300.0,129.0,0.015650,0.012659,0.212066,0.000209,0.002541,inf
40,WV,486,0.917695,0.005211,446.0,40.0,0.005369,0.003925,0.313199,0.007968,0.101132,inf
41,WY,209,0.918660,0.002241,192.0,17.0,0.002311,0.001668,0.326041,0.000965,0.012843,inf
42,AK,248,0.919355,0.002659,228.0,20.0,0.002745,0.001963,0.335373,0.000695,0.009331,inf
43,KS,830,0.920482,0.008900,764.0,66.0,0.009197,0.006477,0.350672,0.001127,0.015300,inf
44,VT,178,0.921348,0.001909,164.0,14.0,0.001974,0.001374,0.362568,0.000866,0.011896,inf
45,DC,297,0.922559,0.003185,274.0,23.0,0.003299,0.002257,0.379393,0.001211,0.016825,inf
46,MS,246,0.922764,0.002638,227.0,19.0,0.002733,0.001865,0.382270,0.000205,0.002877,inf
47,MT,293,0.928328,0.003142,272.0,21.0,0.003274,0.002061,0.463039,0.005563,0.080769,inf
48,ME,2,1.000000,0.000021,2.0,0.0,0.000024,0.000000,inf,0.071672,inf,inf
49,IA,1,1.000000,0.000011,1.0,0.0,0.000012,0.000000,inf,0.000000,NaN,inf

In [92]:
plot_by_woe(df_temp)
# We plot the weight of evidence values.

In [93]:
if ['addr_state:ND'] in df_inputs_prepr.columns.values:
    pass
else:
    df_inputs_prepr['addr_state:ND'] = 0

In [94]:
plot_by_woe(df_temp.iloc[2: -2, : ])
# We plot the weight of evidence values.

In [95]:
plot_by_woe(df_temp.iloc[6: -6, : ])
# We plot the weight of evidence values.

In [96]:
# We create the following categories:
# 'ND' 'NE' 'IA' NV' 'FL' 'HI' 'AL'
# 'NM' 'VA'
# 'NY'
# 'OK' 'TN' 'MO' 'LA' 'MD' 'NC'
# 'CA'
# 'UT' 'KY' 'AZ' 'NJ'
# 'AR' 'MI' 'PA' 'OH' 'MN'
# 'RI' 'MA' 'DE' 'SD' 'IN'
# 'GA' 'WA' 'OR'
# 'WI' 'MT'
# 'TX'
# 'IL' 'CT'
# 'KS' 'SC' 'CO' 'VT' 'AK' 'MS'
# 'WV' 'NH' 'WY' 'DC' 'ME' 'ID'

# 'IA_NV_HI_ID_AL_FL' will be the reference category.

df_inputs_prepr['addr_state:ND_NE_IA_NV_FL_HI_AL'] = sum([df_inputs_prepr['addr_state:ND'], df_inputs_prepr['addr_state:NE'],
                                              df_inputs_prepr['addr_state:IA'], df_inputs_prepr['addr_state:NV'],
                                              df_inputs_prepr['addr_state:FL'], df_inputs_prepr['addr_state:HI'],
                                                          df_inputs_prepr['addr_state:AL']])

df_inputs_prepr['addr_state:NM_VA'] = sum([df_inputs_prepr['addr_state:NM'], df_inputs_prepr['addr_state:VA']])

df_inputs_prepr['addr_state:OK_TN_MO_LA_MD_NC'] = sum([df_inputs_prepr['addr_state:OK'], df_inputs_prepr['addr_state:TN'],
                                              df_inputs_prepr['addr_state:MO'], df_inputs_prepr['addr_state:LA'],
                                              df_inputs_prepr['addr_state:MD'], df_inputs_prepr['addr_state:NC']])

df_inputs_prepr['addr_state:UT_KY_AZ_NJ'] = sum([df_inputs_prepr['addr_state:UT'], df_inputs_prepr['addr_state:KY'],
                                              df_inputs_prepr['addr_state:AZ'], df_inputs_prepr['addr_state:NJ']])

df_inputs_prepr['addr_state:AR_MI_PA_OH_MN'] = sum([df_inputs_prepr['addr_state:AR'], df_inputs_prepr['addr_state:MI'],
                                              df_inputs_prepr['addr_state:PA'], df_inputs_prepr['addr_state:OH'],
                                              df_inputs_prepr['addr_state:MN']])

df_inputs_prepr['addr_state:RI_MA_DE_SD_IN'] = sum([df_inputs_prepr['addr_state:RI'], df_inputs_prepr['addr_state:MA'],
                                              df_inputs_prepr['addr_state:DE'], df_inputs_prepr['addr_state:SD'],
                                              df_inputs_prepr['addr_state:IN']])

df_inputs_prepr['addr_state:GA_WA_OR'] = sum([df_inputs_prepr['addr_state:GA'], df_inputs_prepr['addr_state:WA'],
                                              df_inputs_prepr['addr_state:OR']])

df_inputs_prepr['addr_state:WI_MT'] = sum([df_inputs_prepr['addr_state:WI'], df_inputs_prepr['addr_state:MT']])

df_inputs_prepr['addr_state:IL_CT'] = sum([df_inputs_prepr['addr_state:IL'], df_inputs_prepr['addr_state:CT']])

df_inputs_prepr['addr_state:KS_SC_CO_VT_AK_MS'] = sum([df_inputs_prepr['addr_state:KS'], df_inputs_prepr['addr_state:SC'],
                                              df_inputs_prepr['addr_state:CO'], df_inputs_prepr['addr_state:VT'],
                                              df_inputs_prepr['addr_state:AK'], df_inputs_prepr['addr_state:MS']])

df_inputs_prepr['addr_state:WV_NH_WY_DC_ME_ID'] = sum([df_inputs_prepr['addr_state:WV'], df_inputs_prepr['addr_state:NH'],
                                              df_inputs_prepr['addr_state:WY'], df_inputs_prepr['addr_state:DC'],
                                              df_inputs_prepr['addr_state:ME'], df_inputs_prepr['addr_state:ID']])

### Preprocessing Discrete Variables: Homework

In [97]:
# 'verification_status'
df_temp = woe_discrete(df_inputs_prepr, 'verification_status', df_targets_prepr)
# We calculate weight of evidence.
df_temp

,verification_status,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,Verified,33641,0.872031,0.360734,29336.0,4305.0,0.353161,0.422473,-0.179202,NaN,NaN,0.022684
1,Source Verified,29963,0.895738,0.321295,26839.0,3124.0,0.323101,0.306575,0.052501,0.023707,0.231704,0.022684
2,Not Verified,29653,0.906890,0.317971,26892.0,2761.0,0.323739,0.270952,0.177995,0.011152,0.125494,0.022684

In [98]:
plot_by_woe(df_temp)
# We plot the weight of evidence values.

In [99]:
# 'purpose'
df_temp = woe_discrete(df_inputs_prepr, 'purpose', df_targets_prepr)
# We calculate weight of evidence.
df_temp

,purpose,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,educational,89,0.752809,0.000954,67.0,22.0,0.000807,0.002159,-0.984590,NaN,NaN,0.045124
1,renewable_energy,70,0.771429,0.000751,54.0,16.0,0.000650,0.001570,-0.881845,0.018620,0.102745,0.045124
2,small_business,1431,0.777079,0.015345,1112.0,319.0,0.013387,0.031305,-0.849516,0.005650,0.032329,0.045124
3,medical,918,0.857298,0.009844,787.0,131.0,0.009474,0.012856,-0.305210,0.080220,0.544307,0.045124
4,house,439,0.858770,0.004707,377.0,62.0,0.004539,0.006084,-0.293130,0.001471,0.012080,0.045124
5,other,4806,0.861007,0.051535,4138.0,668.0,0.049815,0.065554,-0.274561,0.002237,0.018569,0.045124
6,wedding,456,0.864035,0.004890,394.0,62.0,0.004743,0.006084,-0.249024,0.003028,0.025537,0.045124
7,moving,602,0.878738,0.006455,529.0,73.0,0.006368,0.007164,-0.117712,0.014702,0.131312,0.045124
8,vacation,496,0.881048,0.005319,437.0,59.0,0.005261,0.005790,-0.095845,0.002311,0.021867,0.045124
9,debt_consolidation,55012,0.885916,0.589897,48736.0,6276.0,0.586707,0.615898,-0.048556,0.004867,0.047289,0.045124
10,major_purchase,1991,0.900552,0.021350,1793.0,198.0,0.021585,0.019431,0.105138,0.014637,0.153693,0.045124
11,home_improvement,5299,0.906397,0.056821,4803.0,496.0,0.057821,0.048675,0.172179,0.005845,0.067042,0.045124
12,car,1072,0.916045,0.011495,982.0,90.0,0.011822,0.008832,0.291541,0.009647,0.119362,0.045124
13,credit_card,20576,0.916505,0.220638,18858.0,1718.0,0.227022,0.168597,0.297536,0.000460,0.005995,0.045124

In [100]:
plot_by_woe(df_temp, 90)
# We plot the weight of evidence values.

In [101]:
# We combine 'educational', 'small_business', 'wedding', 'renewable_energy', 'moving', 'house' in one category: 'educ__sm_b__wedd__ren_en__mov__house'.
# We combine 'other', 'medical', 'vacation' in one category: 'oth__med__vacation'.
# We combine 'major_purchase', 'car', 'home_improvement' in one category: 'major_purch__car__home_impr'.
# We leave 'debt_consolidtion' in a separate category.
# We leave 'credit_card' in a separate category.
# 'educ__sm_b__wedd__ren_en__mov__house' will be the reference category.
df_inputs_prepr['purpose:educ__sm_b__wedd__ren_en__mov__house'] = sum([df_inputs_prepr['purpose:educational'], df_inputs_prepr['purpose:small_business'],
                                                                 df_inputs_prepr['purpose:wedding'], df_inputs_prepr['purpose:renewable_energy'],
                                                                 df_inputs_prepr['purpose:moving'], df_inputs_prepr['purpose:house']])
df_inputs_prepr['purpose:oth__med__vacation'] = sum([df_inputs_prepr['purpose:other'], df_inputs_prepr['purpose:medical'],
                                             df_inputs_prepr['purpose:vacation']])
df_inputs_prepr['purpose:major_purch__car__home_impr'] = sum([df_inputs_prepr['purpose:major_purchase'], df_inputs_prepr['purpose:car'],
                                                        df_inputs_prepr['purpose:home_improvement']])

In [102]:
# 'initial_list_status'
df_temp = woe_discrete(df_inputs_prepr, 'initial_list_status', df_targets_prepr)
df_temp

,initial_list_status,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,f,60491,0.879685,0.648648,53213.0,7278.0,0.640603,0.71423,-0.108794,NaN,NaN,0.024888
1,w,32766,0.911127,0.351352,29854.0,2912.0,0.359397,0.28577,0.229238,0.031443,0.338032,0.024888

In [103]:
plot_by_woe(df_temp)
# We plot the weight of evidence values.

### Preprocessing Continuous Variables: Automating Calculations and Visualizing Results

In [104]:
# WoE function for ordered discrete and continuous variables
def woe_ordered_continuous(df, discrete_variabe_name, good_bad_variable_df):
    df = pd.concat([df[discrete_variabe_name], good_bad_variable_df], axis = 1)
    df = pd.concat([df.groupby(df.columns.values[0], as_index = False)[df.columns.values[1]].count(),
                    df.groupby(df.columns.values[0], as_index = False)[df.columns.values[1]].mean()], axis = 1)
    df = df.iloc[:, [0, 1, 3]]
    df.columns = [df.columns.values[0], 'n_obs', 'prop_good']
    df['prop_n_obs'] = df['n_obs'] / df['n_obs'].sum()
    df['n_good'] = df['prop_good'] * df['n_obs']
    df['n_bad'] = (1 - df['prop_good']) * df['n_obs']
    df['prop_n_good'] = df['n_good'] / df['n_good'].sum()
    df['prop_n_bad'] = df['n_bad'] / df['n_bad'].sum()
    df['WoE'] = np.log(df['prop_n_good'] / df['prop_n_bad'])
    #df = df.sort_values(['WoE'])
    #df = df.reset_index(drop = True)
    df['diff_prop_good'] = df['prop_good'].diff().abs()
    df['diff_WoE'] = df['WoE'].diff().abs()
    df['IV'] = (df['prop_n_good'] - df['prop_n_bad']) * df['WoE']
    df['IV'] = df['IV'].sum()
    return df
# Here we define a function similar to the one above, ...
# ... with one slight difference: we order the results by the values of a different column.
# The function takes 3 arguments: a dataframe, a string, and a dataframe. The function returns a dataframe as a result.

### Preprocessing Continuous Variables: Creating Dummy Variables, Part 1

In [105]:
# term
df_inputs_prepr['term_int'].unique()
# There are only two unique values, 36 and 60.

array([60, 36], dtype=int64)

In [106]:
df_temp = woe_ordered_continuous(df_inputs_prepr, 'term_int', df_targets_prepr)
# We calculate weight of evidence.
df_temp

,term_int,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,36,67534,0.902597,0.724171,60956.0,6578.0,0.733817,0.645535,0.128181,NaN,NaN,0.036603
1,60,25723,0.859581,0.275829,22111.0,3612.0,0.266183,0.354465,-0.286427,0.043016,0.414608,0.036603

In [107]:
plot_by_woe(df_temp)
# We plot the weight of evidence values.

In [108]:
# Leave as is.
# '60' will be the reference category.
df_inputs_prepr['term:36'] = np.where((df_inputs_prepr['term_int'] == 36), 1, 0)
df_inputs_prepr['term:60'] = np.where((df_inputs_prepr['term_int'] == 60), 1, 0)

In [109]:
# emp_length_int
df_inputs_prepr['emp_length_int'].unique()
# Has only 11 levels: from 0 to 10. Hence, we turn it into a factor with 11 levels.

array([ 0., 10.,  1.,  2.,  9.,  3.,  6.,  4.,  7.,  8.,  5.])

In [110]:
df_temp = woe_ordered_continuous(df_inputs_prepr, 'emp_length_int', df_targets_prepr)
# We calculate weight of evidence.
df_temp

,emp_length_int,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,0.0,11553,0.874491,0.123883,10103.0,1450.0,0.121625,0.142296,-0.156972,NaN,NaN,0.007766
1,1.0,5968,0.892594,0.063995,5327.0,641.0,0.064129,0.062905,0.019273,0.018102,0.176245,0.007766
2,2.0,8295,0.887402,0.088948,7361.0,934.0,0.088615,0.091658,-0.033766,0.005192,0.053039,0.007766
3,3.0,7391,0.889325,0.079254,6573.0,818.0,0.079129,0.080275,-0.014377,0.001923,0.019389,0.007766
4,4.0,5555,0.889469,0.059567,4941.0,614.0,0.059482,0.060255,-0.012913,0.000144,0.001465,0.007766
5,5.0,6172,0.886261,0.066183,5470.0,702.0,0.065850,0.068891,-0.045140,0.003208,0.032228,0.007766
6,6.0,5225,0.878852,0.056028,4592.0,633.0,0.055281,0.062120,-0.116640,0.007409,0.071500,0.007766
7,7.0,5131,0.893588,0.055020,4585.0,546.0,0.055196,0.053582,0.029686,0.014736,0.146326,0.007766
8,8.0,4542,0.890137,0.048704,4043.0,499.0,0.048672,0.048970,-0.006104,0.003451,0.035790,0.007766
9,9.0,3621,0.892847,0.038828,3233.0,388.0,0.038920,0.038077,0.021920,0.002711,0.028024,0.007766
10,10.0,29804,0.900517,0.319590,26839.0,2965.0,0.323101,0.290972,0.104738,0.007669,0.082819,0.007766

In [111]:
plot_by_woe(df_temp)
# We plot the weight of evidence values.

In [112]:
# We create the following categories: '0', '1', '2 - 4', '5 - 6', '7 - 9', '10'
# '0' will be the reference category
df_inputs_prepr['emp_length:0'] = np.where(df_inputs_prepr['emp_length_int'].isin([0]), 1, 0)
df_inputs_prepr['emp_length:1'] = np.where(df_inputs_prepr['emp_length_int'].isin([1]), 1, 0)
df_inputs_prepr['emp_length:2-4'] = np.where(df_inputs_prepr['emp_length_int'].isin(range(2, 5)), 1, 0)
df_inputs_prepr['emp_length:5-6'] = np.where(df_inputs_prepr['emp_length_int'].isin(range(5, 7)), 1, 0)
df_inputs_prepr['emp_length:7-9'] = np.where(df_inputs_prepr['emp_length_int'].isin(range(7, 10)), 1, 0)
df_inputs_prepr['emp_length:10'] = np.where(df_inputs_prepr['emp_length_int'].isin([10]), 1, 0)

### Preprocessing Continuous Variables: Creating Dummy Variables, Part 2

In [113]:
df_inputs_prepr['mths_since_issue_d'].unique()

array([ 41.,  38.,  66.,  37.,  58.,  50.,  86.,  51.,  48.,  59.,  72.,
        77.,  47.,  46.,  56.,  55., 119.,  63., 102.,  39.,  53.,  40.,
        52.,  43.,  49.,  57.,  45.,  36.,  54.,  74.,  44.,  73., 103.,
        70.,  95.,  89.,  68.,  82.,  71.,  76., 104.,  65.,  80.,  91.,
        75.,  67.,  42.,  61.,  64.,  60.,  85.,  88., 110.,  96.,  78.,
        83.,  69.,  90.,  62., 108.,  79.,  92., 118.,  99.,  81., 115.,
        97., 114., 116., 100.,  93., 117., 106., 124., 101., 125.,  87.,
        84.,  94., 105., 109.,  98., 107., 112., 113., 122., 111., 120.,
       121., 123., 126.])

In [114]:
df_inputs_prepr['mths_since_issue_d_factor'] = pd.cut(df_inputs_prepr['mths_since_issue_d'], 50)
# Here we do fine-classing: using the 'cut' method, we split the variable into 50 categories by its values.

In [115]:
df_inputs_prepr['mths_since_issue_d_factor']

362514     (39.6, 41.4]
288564     (37.8, 39.6]
213591     (64.8, 66.6]
263083    (35.91, 37.8]
165001     (57.6, 59.4]
              ...
115        (70.2, 72.0]
296284     (37.8, 39.6]
61777      (48.6, 50.4]
91763      (50.4, 52.2]
167512     (57.6, 59.4]
Name: mths_since_issue_d_factor, Length: 93257, dtype: category
Categories (50, interval[float64]): [(35.91, 37.8] < (37.8, 39.6] < (39.6, 41.4] < (41.4, 43.2] ... (118.8, 120.6] < (120.6, 122.4] < (122.4, 124.2] < (124.2, 126.0]]

In [116]:
# mths_since_issue_d
df_temp = woe_ordered_continuous(df_inputs_prepr, 'mths_since_issue_d_factor', df_targets_prepr)
# We calculate weight of evidence.
df_temp

,mths_since_issue_d_factor,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,"(35.91, 37.8]",7191,0.945766,0.077109,6801.0,390.0,0.081874,0.038273,0.760438,NaN,NaN,0.126297
1,"(37.8, 39.6]",9752,0.930373,0.104571,9073.0,679.0,0.109225,0.066634,0.494196,0.015392,0.266241,0.126297
2,"(39.6, 41.4]",9506,0.919945,0.101933,8745.0,761.0,0.105276,0.074681,0.343363,0.010428,0.150833,0.126297
3,"(41.4, 43.2]",7240,0.909116,0.077635,6582.0,658.0,0.079237,0.064573,0.204648,0.010829,0.138715,0.126297
4,"(43.2, 45.0]",7217,0.902868,0.077388,6516.0,701.0,0.078443,0.068793,0.131267,0.006248,0.073381,0.126297
5,"(45.0, 46.8]",3104,0.895296,0.033284,2779.0,325.0,0.033455,0.031894,0.047781,0.007572,0.083487,0.126297
6,"(46.8, 48.6]",6197,0.890269,0.066451,5517.0,680.0,0.066416,0.066732,-0.004744,0.005027,0.052525,0.126297
7,"(48.6, 50.4]",5821,0.885930,0.062419,5157.0,664.0,0.062082,0.065162,-0.048413,0.004339,0.043669,0.126297
8,"(50.4, 52.2]",5021,0.878909,0.053840,4413.0,608.0,0.053126,0.059666,-0.116106,0.007022,0.067693,0.126297
9,"(52.2, 54.0]",4497,0.874138,0.048222,3931.0,566.0,0.047323,0.055545,-0.160186,0.004770,0.044080,0.126297
10,"(54.0, 55.8]",2064,0.866279,0.022132,1788.0,276.0,0.021525,0.027085,-0.229789,0.007859,0.069603,0.126297
11,"(55.8, 57.6]",3572,0.861422,0.038303,3077.0,495.0,0.037042,0.048577,-0.271088,0.004857,0.041299,0.126297
12,"(57.6, 59.4]",2904,0.850895,0.031140,2471.0,433.0,0.029747,0.042493,-0.356600,0.010527,0.085512,0.126297
13,"(59.4, 61.2]",2474,0.847615,0.026529,2097.0,377.0,0.025245,0.036997,-0.382223,0.003280,0.025623,0.126297
14,"(61.2, 63.0]",2539,0.851910,0.027226,2163.0,376.0,0.026039,0.036899,-0.348578,0.004295,0.033644,0.126297
15,"(63.0, 64.8]",1115,0.837668,0.011956,934.0,181.0,0.011244,0.017763,-0.457261,0.014242,0.108683,0.126297
16,"(64.8, 66.6]",1721,0.816967,0.018454,1406.0,315.0,0.016926,0.030913,-0.602309,0.020701,0.145048,0.126297
17,"(66.6, 68.4]",1296,0.852623,0.013897,1105.0,191.0,0.013303,0.018744,-0.342913,0.035657,0.259396,0.126297
18,"(68.4, 70.2]",1097,0.839562,0.011763,921.0,176.0,0.011087,0.017272,-0.443265,0.013061,0.100351,0.126297
19,"(70.2, 72.0]",1001,0.816184,0.010734,817.0,184.0,0.009835,0.018057,-0.607537,0.023379,0.164273,0.126297
20,"(72.0, 73.8]",447,0.829978,0.004793,371.0,76.0,0.004466,0.007458,-0.512772,0.013794,0.094765,0.126297
21,"(73.8, 75.6]",790,0.853165,0.008471,674.0,116.0,0.008114,0.011384,-0.338601,0.023187,0.174171,0.126297
22,"(75.6, 77.4]",754,0.867374,0.008085,654.0,100.0,0.007873,0.009814,-0.220303,0.014209,0.118297,0.126297
23,"(77.4, 79.2]",690,0.844928,0.007399,583.0,107.0,0.007018,0.010500,-0.402882,0.022446,0.182579,0.126297
24,"(79.2, 81.0]",599,0.876461,0.006423,525.0,74.0,0.006320,0.007262,-0.138907,0.031533,0.263975,0.126297
25,"(81.0, 82.8]",254,0.870079,0.002724,221.0,33.0,0.002661,0.003238,-0.196586,0.006382,0.057678,0.126297
26,"(82.8, 84.6]",533,0.878049,0.005715,468.0,65.0,0.005634,0.006379,-0.124160,0.007970,0.072426,0.126297
27,"(84.6, 86.4]",459,0.836601,0.004922,384.0,75.0,0.004623,0.007360,-0.465086,0.041447,0.340927,0.126297
28,"(86.4, 88.2]",443,0.864560,0.004750,383.0,60.0,0.004611,0.005888,-0.244550,0.027959,0.220536,0.126297
29,"(88.2, 90.0]",439,0.863326,0.004707,379.0,60.0,0.004563,0.005888,-0.255049,0.001234,0.010499,0.126297
30,"(90.0, 91.8]",194,0.835052,0.002080,162.0,32.0,0.001950,0.003140,-0.476380,0.028274,0.221331,0.126297
31,"(91.8, 93.6]",367,0.896458,0.003935,329.0,38.0,0.003961,0.003729,0.060231,0.061406,0.536611,0.126297
32,"(93.6, 95.4]",257,0.879377,0.002756,226.0,31.0,0.002721,0.003042,-0.111693,0.017080,0.171924,0.126297
33,"(95.4, 97.2]",276,0.836957,0.002960,231.0,45.0,0.002781,0.004416,-0.462485,0.042421,0.350793,0.126297
34,"(97.2, 99.0]",234,0.829060,0.002509,194.0,40.0,0.002335,0.003925,-0.519262,0.007897,0.056777,0.126297
35,"(99.0, 100.8]",100,0.920000,0.001072,92.0,8.0,0.001108,0.000785,0.344106,0.090940,0.863368,0.126297
36,"(100.8, 102.6]",170,0.835294,0.001823,142.0,28.0,0.001709,0.002748,-0.474618,0.084706,0.818724,0.126297
37,"(102.6, 104.4]",150,0.873333,0.001608,131.0,19.0,0.001577,0.001865,-0.167482,0.038039,0.307136,0.126297
38,"(104.4, 106.2]",129,0.868217,0.001383,112.0,17.0,0.001348,0.001668,-0.212955,0.005116,0.045473,0.126297
39,"(106.2, 108.0]",119,0.815126,0.001276,97.0,22.0,0.001168,0.002159,-0.614572,0.053091,0.401617,0.126297
40,"(108.0, 109.8]",36,0.861111,0.000386,31.0,5.0,0.000373,0.000491,-0.273691,0.045985,0.340881,0.126297
41,"(109.8, 111.6]",40,0.800000,0.000429,32.0,8.0,0.000385,0.000785,-0.711946,0.061111,0.438255,0.126297
42,"(111.6, 113.4]",37,0.972973,0.000397,36.0,1.0,0.000433,0.000098,1.485278,0.172973,2.197225,0.126297
43,"(113.4, 115.2]",57,0.824561,0.000611,47.0,10.0,0.000566,0.000981,-0.550678,0.148412,2.035956,0.126297
44,"(115.2, 117.0]",131,0.801527,0.001405,105.0,26.0,0.001264,0.002552,-0.702377,0.023035,0.151699,0.126297
45,"(117.0, 118.8]",59,0.813559,0.000633,48.0,11.0,0.000578,0.001079,-0.624935,0.012033,0.077442,0.126297
46,"(118.8, 120.6]",83,0.734940,0.000890,61.0,22.0,0.000734,0.002159,-1.078409,0.078620,0.453474,0.126297
47,"(120.6, 122.4]",41,0.609756,0.000440,25.0,16.0,0.000301,0.001570,-1.651954,0.125184,0.573544,0.126297
48,"(122.4, 124.2]",23,0.695652,0.000247,16.0,7.0,0.000193,0.000687,-1.271562,0.085896,0.380391,0.126297
49,"(124.2, 126.0]",17,0.882353,0.000182,15.0,2.0,0.000181,0.000196,-0.083338,0.186701,1.188224,0.126297

In [117]:
plot_by_woe(df_temp)
# We plot the weight of evidence values.
# We have to rotate the labels because we cannot read them otherwise.

In [118]:
plot_by_woe(df_temp, 90)
# We plot the weight of evidence values, rotating the labels 90 degrees.

In [119]:
plot_by_woe(df_temp.iloc[3: , : ], 90)
# We plot the weight of evidence values.

In [120]:
# We create the following categories:
# < 38, 38 - 39, 40 - 41, 42 - 48, 49 - 52, 53 - 64, 65 - 84, > 84.
df_inputs_prepr['mths_since_issue_d:<38'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(38)), 1, 0)
df_inputs_prepr['mths_since_issue_d:38-39'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(38, 40)), 1, 0)
df_inputs_prepr['mths_since_issue_d:40-41'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(40, 42)), 1, 0)
df_inputs_prepr['mths_since_issue_d:42-48'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(42, 49)), 1, 0)
df_inputs_prepr['mths_since_issue_d:49-52'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(49, 53)), 1, 0)
df_inputs_prepr['mths_since_issue_d:53-64'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(53, 65)), 1, 0)
df_inputs_prepr['mths_since_issue_d:65-84'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(65, 85)), 1, 0)
df_inputs_prepr['mths_since_issue_d:>84'] = np.where(df_inputs_prepr['mths_since_issue_d'].isin(range(85, int(df_inputs_prepr['mths_since_issue_d'].max()))), 1, 0)

In [121]:
# int_rate
df_inputs_prepr['int_rate_factor'] = pd.cut(df_inputs_prepr['int_rate'], 50)
# Here we do fine-classing: using the 'cut' method, we split the variable into 50 categories by its values.

In [122]:
df_temp = woe_ordered_continuous(df_inputs_prepr, 'int_rate_factor', df_targets_prepr)
# We calculate weight of evidence.
df_temp

,int_rate_factor,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,"(5.399, 5.833]",198,0.969697,0.002123,192.0,6.0,0.002311,0.000589,1.367495,NaN,NaN,0.371465
1,"(5.833, 6.246]",2086,0.979866,0.022368,2044.0,42.0,0.024607,0.004122,1.786754,0.010169,0.419258,0.371465
2,"(6.246, 6.658]",1974,0.972138,0.021167,1919.0,55.0,0.023102,0.005397,1.453986,0.007728,0.332768,0.371465
3,"(6.658, 7.071]",477,0.951782,0.005115,454.0,23.0,0.005465,0.002257,0.884362,0.020356,0.569623,0.371465
4,"(7.071, 7.484]",804,0.981343,0.008621,789.0,15.0,0.009498,0.001472,1.864475,0.029561,0.980113,0.371465
5,"(7.484, 7.897]",3245,0.965485,0.034796,3133.0,112.0,0.037717,0.010991,1.233007,0.015858,0.631469,0.371465
6,"(7.897, 8.31]",2429,0.951009,0.026046,2310.0,119.0,0.027809,0.011678,0.867639,0.014477,0.365368,0.371465
7,"(8.31, 8.722]",1680,0.965476,0.018015,1622.0,58.0,0.019526,0.005692,1.232732,0.014468,0.365093,0.371465
8,"(8.722, 9.135]",2384,0.942114,0.025564,2246.0,138.0,0.027038,0.013543,0.691412,0.023362,0.541320,0.371465
9,"(9.135, 9.548]",1590,0.976730,0.017050,1553.0,37.0,0.018696,0.003631,1.638785,0.034615,0.947373,0.371465
10,"(9.548, 9.961]",1881,0.931419,0.020170,1752.0,129.0,0.021091,0.012659,0.510460,0.045310,1.128325,0.371465
11,"(9.961, 10.374]",2766,0.936370,0.029660,2590.0,176.0,0.031180,0.017272,0.590688,0.004951,0.080228,0.371465
12,"(10.374, 10.786]",1390,0.917986,0.014905,1276.0,114.0,0.015361,0.011187,0.317046,0.018385,0.273642,0.371465
13,"(10.786, 11.199]",4464,0.937500,0.047868,4185.0,279.0,0.050381,0.027380,0.609810,0.019514,0.292763,0.371465
14,"(11.199, 11.612]",1213,0.916735,0.013007,1112.0,101.0,0.013387,0.009912,0.300554,0.020765,0.309255,0.371465
15,"(11.612, 12.025]",3737,0.931496,0.040072,3481.0,256.0,0.041906,0.025123,0.511657,0.014760,0.211102,0.371465
16,"(12.025, 12.438]",3077,0.905752,0.032995,2787.0,290.0,0.033551,0.028459,0.164599,0.025743,0.347057,0.371465
17,"(12.438, 12.85]",2754,0.920116,0.029531,2534.0,220.0,0.030505,0.021590,0.345686,0.014364,0.181087,0.371465
18,"(12.85, 13.263]",5440,0.904044,0.058333,4918.0,522.0,0.059205,0.051227,0.144749,0.016072,0.200937,0.371465
19,"(13.263, 13.676]",3806,0.897793,0.040812,3417.0,389.0,0.041135,0.038175,0.074698,0.006251,0.070051,0.371465
20,"(13.676, 14.089]",2692,0.894874,0.028866,2409.0,283.0,0.029001,0.027772,0.043279,0.002919,0.031419,0.371465
21,"(14.089, 14.502]",5760,0.887153,0.061765,5110.0,650.0,0.061517,0.063788,-0.036258,0.007721,0.079538,0.371465
22,"(14.502, 14.914]",1187,0.867734,0.012728,1030.0,157.0,0.012400,0.015407,-0.217172,0.019419,0.180914,0.371465
23,"(14.914, 15.327]",4811,0.882145,0.051589,4244.0,567.0,0.051091,0.055643,-0.085338,0.014411,0.131834,0.371465
24,"(15.327, 15.74]",3146,0.886840,0.033735,2790.0,356.0,0.033587,0.034936,-0.039375,0.004695,0.045964,0.371465
25,"(15.74, 16.153]",1869,0.837346,0.020041,1565.0,304.0,0.018840,0.029833,-0.459627,0.049494,0.420253,0.371465
26,"(16.153, 16.566]",3230,0.849226,0.034635,2743.0,487.0,0.033022,0.047792,-0.369697,0.011880,0.089930,0.371465
27,"(16.566, 16.978]",1035,0.852174,0.011098,882.0,153.0,0.010618,0.015015,-0.346487,0.002948,0.023211,0.371465
28,"(16.978, 17.391]",2843,0.848048,0.030486,2411.0,432.0,0.029025,0.042395,-0.378869,0.004126,0.032383,0.371465
29,"(17.391, 17.804]",2992,0.837567,0.032083,2506.0,486.0,0.030168,0.047694,-0.458006,0.010481,0.079137,0.371465
30,"(17.804, 18.217]",286,0.835664,0.003067,239.0,47.0,0.002877,0.004612,-0.471925,0.001903,0.013919,0.371465
31,"(18.217, 18.63]",2729,0.827409,0.029263,2258.0,471.0,0.027183,0.046222,-0.530864,0.008255,0.058939,0.371465
32,"(18.63, 19.042]",1835,0.820163,0.019677,1505.0,330.0,0.018118,0.032385,-0.580785,0.007246,0.049921,0.371465
33,"(19.042, 19.455]",1135,0.786784,0.012171,893.0,242.0,0.010750,0.023749,-0.792592,0.033379,0.211807,0.371465
34,"(19.455, 19.868]",1680,0.816667,0.018015,1372.0,308.0,0.016517,0.030226,-0.604316,0.029883,0.188276,0.371465
35,"(19.868, 20.281]",1244,0.849678,0.013339,1057.0,187.0,0.012725,0.018351,-0.366159,0.033012,0.238156,0.371465
36,"(20.281, 20.694]",805,0.814907,0.008632,656.0,149.0,0.007897,0.014622,-0.616026,0.034772,0.249867,0.371465
37,"(20.694, 21.106]",956,0.791841,0.010251,757.0,199.0,0.009113,0.019529,-0.762182,0.023066,0.146156,0.371465
38,"(21.106, 21.519]",701,0.757489,0.007517,531.0,170.0,0.006392,0.016683,-0.959277,0.034352,0.197095,0.371465
39,"(21.519, 21.932]",222,0.801802,0.002381,178.0,44.0,0.002143,0.004318,-0.700647,0.044313,0.258630,0.371465
40,"(21.932, 22.345]",832,0.775240,0.008922,645.0,187.0,0.007765,0.018351,-0.860099,0.026561,0.159452,0.371465
41,"(22.345, 22.758]",586,0.737201,0.006284,432.0,154.0,0.005201,0.015113,-1.066768,0.038039,0.206669,0.371465
42,"(22.758, 23.17]",375,0.741333,0.004021,278.0,97.0,0.003347,0.009519,-1.045331,0.004132,0.021437,0.371465
43,"(23.17, 23.583]",655,0.778626,0.007024,510.0,145.0,0.006140,0.014230,-0.840564,0.037293,0.204767,0.371465
44,"(23.583, 23.996]",408,0.750000,0.004375,306.0,102.0,0.003684,0.010010,-0.999628,0.028626,0.159065,0.371465
45,"(23.996, 24.409]",393,0.834606,0.004214,328.0,65.0,0.003949,0.006379,-0.479614,0.084606,0.520014,0.371465
46,"(24.409, 24.822]",436,0.786697,0.004675,343.0,93.0,0.004129,0.009127,-0.793110,0.047908,0.313495,0.371465
47,"(24.822, 25.234]",351,0.792023,0.003764,278.0,73.0,0.003347,0.007164,-0.761079,0.005326,0.032031,0.371465
48,"(25.234, 25.647]",194,0.757732,0.002080,147.0,47.0,0.001770,0.004612,-0.957956,0.034291,0.196877,0.371465
49,"(25.647, 26.06]",474,0.738397,0.005083,350.0,124.0,0.004213,0.012169,-1.060589,0.019335,0.102633,0.371465

In [123]:
plot_by_woe(df_temp, 90)
# We plot the weight of evidence values.

In [124]:
# '< 9.548', '9.548 - 12.025', '12.025 - 15.74', '15.74 - 20.281', '> 20.281'

In [125]:
df_inputs_prepr['int_rate:<9.548'] = np.where((df_inputs_prepr['int_rate'] <= 9.548), 1, 0)
df_inputs_prepr['int_rate:9.548-12.025'] = np.where((df_inputs_prepr['int_rate'] > 9.548) & (df_inputs_prepr['int_rate'] <= 12.025), 1, 0)
df_inputs_prepr['int_rate:12.025-15.74'] = np.where((df_inputs_prepr['int_rate'] > 12.025) & (df_inputs_prepr['int_rate'] <= 15.74), 1, 0)
df_inputs_prepr['int_rate:15.74-20.281'] = np.where((df_inputs_prepr['int_rate'] > 15.74) & (df_inputs_prepr['int_rate'] <= 20.281), 1, 0)
df_inputs_prepr['int_rate:>20.281'] = np.where((df_inputs_prepr['int_rate'] > 20.281), 1, 0)

In [126]:
# funded_amnt
df_inputs_prepr['funded_amnt_factor'] = pd.cut(df_inputs_prepr['funded_amnt'], 50)
# Here we do fine-classing: using the 'cut' method, we split the variable into 50 categories by its values.
df_temp = woe_ordered_continuous(df_inputs_prepr, 'funded_amnt_factor', df_targets_prepr)
# We calculate weight of evidence.
df_temp

,funded_amnt_factor,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,"(465.5, 1190.0]",319,0.880878,0.003421,281.0,38.0,0.003383,0.003729,-0.097472,NaN,NaN,0.018663
1,"(1190.0, 1880.0]",800,0.896250,0.008578,717.0,83.0,0.008632,0.008145,0.057995,0.015372,0.155467,0.018663
2,"(1880.0, 2570.0]",1513,0.900198,0.016224,1362.0,151.0,0.016396,0.014818,0.101189,0.003948,0.043194,0.018663
3,"(2570.0, 3260.0]",1817,0.893781,0.019484,1624.0,193.0,0.019550,0.018940,0.031717,0.006417,0.069472,0.018663
4,"(3260.0, 3950.0]",1245,0.891566,0.013350,1110.0,135.0,0.013363,0.013248,0.008600,0.002215,0.023117,0.018663
5,"(3950.0, 4640.0]",2298,0.882942,0.024642,2029.0,269.0,0.024426,0.026398,-0.077654,0.008625,0.086254,0.018663
6,"(4640.0, 5330.0]",3957,0.898155,0.042431,3554.0,403.0,0.042785,0.039549,0.078652,0.015213,0.156305,0.018663
7,"(5330.0, 6020.0]",4186,0.906593,0.044887,3795.0,391.0,0.045686,0.038371,0.174491,0.008438,0.095840,0.018663
8,"(6020.0, 6710.0]",1718,0.881839,0.018422,1515.0,203.0,0.018238,0.019921,-0.088276,0.024754,0.262767,0.018663
9,"(6710.0, 7400.0]",2880,0.893403,0.030882,2573.0,307.0,0.030975,0.030128,0.027739,0.011563,0.116015,0.018663
10,"(7400.0, 8090.0]",4266,0.895218,0.045745,3819.0,447.0,0.045975,0.043867,0.046945,0.001815,0.019205,0.018663
11,"(8090.0, 8780.0]",1617,0.890538,0.017339,1440.0,177.0,0.017335,0.017370,-0.001992,0.004680,0.048937,0.018663
12,"(8780.0, 9470.0]",2320,0.888793,0.024877,2062.0,258.0,0.024823,0.025319,-0.019769,0.001745,0.017777,0.018663
13,"(9470.0, 10160.0]",8552,0.891955,0.091704,7628.0,924.0,0.091829,0.090677,0.012628,0.003162,0.032397,0.018663
14,"(10160.0, 10850.0]",1642,0.872716,0.017607,1433.0,209.0,0.017251,0.020510,-0.173049,0.019239,0.185678,0.018663
15,"(10850.0, 11540.0]",2091,0.880918,0.022422,1842.0,249.0,0.022175,0.024436,-0.097086,0.008202,0.075963,0.018663
16,"(11540.0, 12230.0]",5767,0.906190,0.061840,5226.0,541.0,0.062913,0.053091,0.169742,0.025272,0.266828,0.018663
17,"(12230.0, 12920.0]",1228,0.875407,0.013168,1075.0,153.0,0.012941,0.015015,-0.148603,0.030783,0.318344,0.018663
18,"(12920.0, 13610.0]",1860,0.898925,0.019945,1672.0,188.0,0.020128,0.018449,0.087093,0.023518,0.235696,0.018663
19,"(13610.0, 14300.0]",2087,0.899377,0.022379,1877.0,210.0,0.022596,0.020608,0.092082,0.000452,0.004989,0.018663
20,"(14300.0, 14990.0]",1255,0.886853,0.013457,1113.0,142.0,0.013399,0.013935,-0.039253,0.012525,0.131335,0.018663
21,"(14990.0, 15680.0]",5441,0.903143,0.058344,4914.0,527.0,0.059157,0.051717,0.134402,0.016290,0.173656,0.018663
22,"(15680.0, 16370.0]",2920,0.882534,0.031311,2577.0,343.0,0.031023,0.033660,-0.081590,0.020609,0.215992,0.018663
23,"(16370.0, 17060.0]",1625,0.880000,0.017425,1430.0,195.0,0.017215,0.019136,-0.105810,0.002534,0.024221,0.018663
24,"(17060.0, 17750.0]",921,0.850163,0.009876,783.0,138.0,0.009426,0.013543,-0.362362,0.029837,0.256551,0.018663
25,"(17750.0, 18440.0]",2898,0.885783,0.031075,2567.0,331.0,0.030903,0.032483,-0.049866,0.035620,0.312496,0.018663
26,"(18440.0, 19130.0]",989,0.858443,0.010605,849.0,140.0,0.010221,0.013739,-0.295824,0.027340,0.245958,0.018663
27,"(19130.0, 19820.0]",1057,0.875118,0.011334,925.0,132.0,0.011136,0.012954,-0.151249,0.016675,0.144575,0.018663
28,"(19820.0, 20510.0]",5055,0.896736,0.054205,4533.0,522.0,0.054570,0.051227,0.063231,0.021618,0.214480,0.018663
29,"(20510.0, 21200.0]",1635,0.895413,0.017532,1464.0,171.0,0.017624,0.016781,0.049023,0.001323,0.014208,0.018663
30,"(21200.0, 21890.0]",476,0.834034,0.005104,397.0,79.0,0.004779,0.007753,-0.483752,0.061379,0.532776,0.018663
31,"(21890.0, 22580.0]",1028,0.883268,0.011023,908.0,120.0,0.010931,0.011776,-0.074488,0.049235,0.409264,0.018663
32,"(22580.0, 23270.0]",633,0.892575,0.006788,565.0,68.0,0.006802,0.006673,0.019077,0.009307,0.093565,0.018663
33,"(23270.0, 23960.0]",497,0.837022,0.005329,416.0,81.0,0.005008,0.007949,-0.462005,0.055553,0.481082,0.018663
34,"(23960.0, 24650.0]",2491,0.898033,0.026711,2237.0,254.0,0.026930,0.024926,0.077316,0.061011,0.539321,0.018663
35,"(24650.0, 25340.0]",2500,0.903200,0.026808,2258.0,242.0,0.027183,0.023749,0.135056,0.005167,0.057740,0.018663
36,"(25340.0, 26030.0]",487,0.852156,0.005222,415.0,72.0,0.004996,0.007066,-0.346628,0.051044,0.481685,0.018663
37,"(26030.0, 26720.0]",299,0.822742,0.003206,246.0,53.0,0.002961,0.005201,-0.563201,0.029414,0.216573,0.018663
38,"(26720.0, 27410.0]",410,0.870732,0.004396,357.0,53.0,0.004298,0.005201,-0.190797,0.047989,0.372404,0.018663
39,"(27410.0, 28100.0]",1604,0.895885,0.017200,1437.0,167.0,0.017299,0.016389,0.054078,0.025154,0.244875,0.018663
40,"(28100.0, 28790.0]",204,0.857843,0.002188,175.0,29.0,0.002107,0.002846,-0.300751,0.038042,0.354829,0.018663
41,"(28790.0, 29480.0]",286,0.846154,0.003067,242.0,44.0,0.002913,0.004318,-0.393493,0.011689,0.092742,0.018663
42,"(29480.0, 30170.0]",1762,0.879682,0.018894,1550.0,212.0,0.018660,0.020805,-0.108817,0.033528,0.284676,0.018663
43,"(30170.0, 30860.0]",133,0.827068,0.001426,110.0,23.0,0.001324,0.002257,-0.533255,0.052615,0.424438,0.018663
44,"(30860.0, 31550.0]",218,0.830275,0.002338,181.0,37.0,0.002179,0.003631,-0.510662,0.003208,0.022593,0.018663
45,"(31550.0, 32240.0]",367,0.920981,0.003935,338.0,29.0,0.004069,0.002846,0.357509,0.090706,0.868171,0.018663
46,"(32240.0, 32930.0]",139,0.884892,0.001491,123.0,16.0,0.001481,0.001570,-0.058645,0.036089,0.416154,0.018663
47,"(32930.0, 33620.0]",275,0.901818,0.002949,248.0,27.0,0.002986,0.002650,0.119351,0.016926,0.177996,0.018663
48,"(33620.0, 34310.0]",142,0.894366,0.001523,127.0,15.0,0.001529,0.001472,0.037896,0.007452,0.081455,0.018663
49,"(34310.0, 35000.0]",3347,0.880789,0.035890,2948.0,399.0,0.035489,0.039156,-0.098320,0.013577,0.136216,0.018663

In [127]:
plot_by_woe(df_temp, 90)
# We plot the weight of evidence values.

### Data Preparation: Continuous Variables, Part 1 and 2: Homework

In [128]:
# mths_since_earliest_cr_line
df_inputs_prepr['mths_since_earliest_cr_line_factor'] = pd.cut(df_inputs_prepr['mths_since_earliest_cr_line'], 50)
# Here we do fine-classing: using the 'cut' method, we split the variable into 50 categories by its values.
df_temp = woe_ordered_continuous(df_inputs_prepr, 'mths_since_earliest_cr_line_factor', df_targets_prepr)
# We calculate weight of evidence.
df_temp

,mths_since_earliest_cr_line_factor,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,"(-0.587, 11.74]",5,1.000000,0.000054,5.0,0.0,0.000060,0.000000,inf,NaN,NaN,inf
1,"(11.74, 23.48]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
2,"(23.48, 35.22]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
3,"(35.22, 46.96]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
4,"(46.96, 58.7]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
5,"(58.7, 70.44]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
6,"(70.44, 82.18]",182,0.923077,0.001952,168.0,14.0,0.002022,0.001374,0.386666,NaN,NaN,inf
7,"(82.18, 93.92]",508,0.913386,0.005447,464.0,44.0,0.005586,0.004318,0.257454,0.009691,0.129212,inf
8,"(93.92, 105.66]",715,0.851748,0.007667,609.0,106.0,0.007331,0.010402,-0.349861,0.061638,0.607316,inf
9,"(105.66, 117.4]",1268,0.854890,0.013597,1084.0,184.0,0.013050,0.018057,-0.324763,0.003141,0.025098,inf
10,"(117.4, 129.14]",2314,0.875108,0.024813,2025.0,289.0,0.024378,0.028361,-0.151342,0.020218,0.173421,inf
11,"(129.14, 140.88]",2816,0.860795,0.030196,2424.0,392.0,0.029181,0.038469,-0.276328,0.014313,0.124986,inf
12,"(140.88, 152.62]",3366,0.882353,0.036094,2970.0,396.0,0.035754,0.038862,-0.083338,0.021557,0.192991,inf
13,"(152.62, 164.36]",3989,0.885686,0.042774,3533.0,456.0,0.042532,0.044750,-0.050831,0.003333,0.032507,inf
14,"(164.36, 176.1]",4857,0.886967,0.052082,4308.0,549.0,0.051862,0.053876,-0.038110,0.001282,0.012721,inf
15,"(176.1, 187.84]",5076,0.891450,0.054430,4525.0,551.0,0.054474,0.054073,0.007397,0.004483,0.045507,inf
16,"(187.84, 199.58]",6578,0.882183,0.070536,5803.0,775.0,0.069859,0.076055,-0.084973,0.009267,0.092371,inf
17,"(199.58, 211.32]",7131,0.887393,0.076466,6328.0,803.0,0.076179,0.078803,-0.033856,0.005210,0.051118,inf
18,"(211.32, 223.06]",6775,0.884133,0.072649,5990.0,785.0,0.072110,0.077036,-0.066078,0.003260,0.032222,inf
19,"(223.06, 234.8]",5521,0.889875,0.059202,4913.0,608.0,0.059145,0.059666,-0.008776,0.005742,0.057302,inf
20,"(234.8, 246.54]",4966,0.884213,0.053251,4391.0,575.0,0.052861,0.056428,-0.065298,0.005662,0.056523,inf
21,"(246.54, 258.28]",4549,0.891185,0.048779,4054.0,495.0,0.048804,0.048577,0.004661,0.006972,0.069959,inf
22,"(258.28, 270.02]",4472,0.891547,0.047954,3987.0,485.0,0.047997,0.047596,0.008405,0.000363,0.003744,inf
23,"(270.02, 281.76]",3672,0.896786,0.039375,3293.0,379.0,0.039643,0.037193,0.063777,0.005239,0.055373,inf
24,"(281.76, 293.5]",3640,0.900275,0.039032,3277.0,363.0,0.039450,0.035623,0.102040,0.003488,0.038263,inf
25,"(293.5, 305.24]",2602,0.902767,0.027901,2349.0,253.0,0.028278,0.024828,0.130115,0.002492,0.028075,inf
26,"(305.24, 316.98]",1988,0.908451,0.021317,1806.0,182.0,0.021741,0.017861,0.196622,0.005684,0.066508,inf
27,"(316.98, 328.72]",2020,0.900990,0.021661,1820.0,200.0,0.021910,0.019627,0.110034,0.007461,0.086589,inf
28,"(328.72, 340.46]",2129,0.901362,0.022829,1919.0,210.0,0.023102,0.020608,0.114211,0.000372,0.004178,inf
29,"(340.46, 352.2]",1810,0.899448,0.019409,1628.0,182.0,0.019599,0.017861,0.092860,0.001915,0.021351,inf
30,"(352.2, 363.94]",1477,0.914015,0.015838,1350.0,127.0,0.016252,0.012463,0.265432,0.014567,0.172572,inf
31,"(363.94, 375.68]",1360,0.910294,0.014583,1238.0,122.0,0.014904,0.011973,0.218991,0.003721,0.046441,inf
32,"(375.68, 387.42]",1152,0.905382,0.012353,1043.0,109.0,0.012556,0.010697,0.160268,0.004912,0.058723,inf
33,"(387.42, 399.16]",1051,0.906755,0.011270,953.0,98.0,0.011473,0.009617,0.176407,0.001374,0.016139,inf
34,"(399.16, 410.9]",826,0.917676,0.008857,758.0,68.0,0.009125,0.006673,0.312935,0.010920,0.136528,inf
35,"(410.9, 422.64]",808,0.925743,0.008664,748.0,60.0,0.009005,0.005888,0.424818,0.008067,0.111883,inf
36,"(422.64, 434.38]",524,0.895038,0.005619,469.0,55.0,0.005646,0.005397,0.045029,0.030704,0.379789,inf
37,"(434.38, 446.12]",416,0.918269,0.004461,382.0,34.0,0.004599,0.003337,0.320819,0.023231,0.275791,inf
38,"(446.12, 457.86]",329,0.917933,0.003528,302.0,27.0,0.003636,0.002650,0.316349,0.000336,0.004470,inf
39,"(457.86, 469.6]",376,0.920213,0.004032,346.0,30.0,0.004165,0.002944,0.347001,0.002280,0.030651,inf
40,"(469.6, 481.34]",371,0.916442,0.003978,340.0,31.0,0.004093,0.003042,0.296718,0.003771,0.050283,inf
41,"(481.34, 493.08]",294,0.908163,0.003153,267.0,27.0,0.003214,0.002650,0.193171,0.008279,0.103547,inf
42,"(493.08, 504.82]",229,0.943231,0.002456,216.0,13.0,0.002600,0.001276,0.712088,0.035068,0.518917,inf
43,"(504.82, 516.56]",178,0.915730,0.001909,163.0,15.0,0.001962,0.001472,0.287459,0.027501,0.424629,inf
44,"(516.56, 528.3]",159,0.924528,0.001705,147.0,12.0,0.001770,0.001178,0.407285,0.008798,0.119826,inf
45,"(528.3, 540.04]",140,0.907143,0.001501,127.0,13.0,0.001529,0.001276,0.180997,0.017385,0.226288,inf
46,"(540.04, 551.78]",135,0.903704,0.001448,122.0,13.0,0.001469,0.001276,0.140831,0.003439,0.040166,inf
47,"(551.78, 563.52]",93,0.913978,0.000997,85.0,8.0,0.001023,0.000785,0.264969,0.010275,0.124138,inf
48,"(563.52, 575.26]",80,0.862500,0.000858,69.0,11.0,0.000831,0.001079,-0.262029,0.051478,0.526998,inf
49,"(575.26, 587.0]",310,0.867742,0.003324,269.0,41.0,0.003238,0.004024,-0.217101,0.005242,0.044928,inf

In [129]:
plot_by_woe(df_temp, 90)
# We plot the weight of evidence values.

In [130]:
plot_by_woe(df_temp.iloc[6: , : ], 90)
# We plot the weight of evidence values.

In [131]:
# We create the following categories:
# < 140, # 141 - 164, # 165 - 247, # 248 - 270, # 271 - 352, # > 352
df_inputs_prepr['mths_since_earliest_cr_line:<140'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(140)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:141-164'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(140, 165)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:165-247'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(165, 248)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:248-270'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(248, 271)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:271-352'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(271, 353)), 1, 0)
df_inputs_prepr['mths_since_earliest_cr_line:>352'] = np.where(df_inputs_prepr['mths_since_earliest_cr_line'].isin(range(353, int(df_inputs_prepr['mths_since_earliest_cr_line'].max()))), 1, 0)

In [132]:
# delinq_2yrs
df_temp = woe_ordered_continuous(df_inputs_prepr, 'delinq_2yrs', df_targets_prepr)
# We calculate weight of evidence.
df_temp

C:\Users\Sanket\Anaconda4\lib\site-packages\pandas\core\algorithms.py:1926: RuntimeWarning: invalid value encountered in subtract
  out_arr[res_indexer] = arr[res_indexer] - arr[lag_indexer]

,delinq_2yrs,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,0.0,76566,0.890944,0.821021,68216.0,8350.0,0.821217,0.819431,0.002177,NaN,NaN,inf
1,1.0,11297,0.890413,0.121138,10059.0,1238.0,0.121095,0.121492,-0.003270,0.000530,0.005447,inf
2,2.0,3192,0.885025,0.034228,2825.0,367.0,0.034009,0.036016,-0.057339,0.005388,0.054069,inf
3,3.0,1134,0.893298,0.012160,1013.0,121.0,0.012195,0.011874,0.026640,0.008273,0.083979,inf
4,4.0,510,0.886275,0.005469,452.0,58.0,0.005441,0.005692,-0.045001,0.007024,0.071642,inf
5,5.0,270,0.911111,0.002895,246.0,24.0,0.002961,0.002355,0.229037,0.024837,0.274039,inf
6,6.0,128,0.859375,0.001373,110.0,18.0,0.001324,0.001766,-0.288132,0.051736,0.517169,inf
7,7.0,67,0.925373,0.000718,62.0,5.0,0.000746,0.000491,0.419456,0.065998,0.707588,inf
8,8.0,29,0.896552,0.000311,26.0,3.0,0.000313,0.000294,0.061244,0.028821,0.358212,inf
9,9.0,22,0.954545,0.000236,21.0,1.0,0.000253,0.000098,0.946282,0.057994,0.885038,inf
10,10.0,9,0.888889,0.000097,8.0,1.0,0.000096,0.000098,-0.018799,0.065657,0.965081,inf
11,11.0,10,1.000000,0.000107,10.0,0.0,0.000120,0.000000,inf,0.111111,inf,inf
12,12.0,8,0.625000,0.000086,5.0,3.0,0.000060,0.000294,-1.587415,0.375000,inf,inf
13,13.0,7,0.857143,0.000075,6.0,1.0,0.000072,0.000098,-0.306481,0.232143,1.280934,inf
14,14.0,2,1.000000,0.000021,2.0,0.0,0.000024,0.000000,inf,0.142857,inf,inf
15,15.0,1,1.000000,0.000011,1.0,0.0,0.000012,0.000000,inf,0.000000,NaN,inf
16,16.0,1,1.000000,0.000011,1.0,0.0,0.000012,0.000000,inf,0.000000,NaN,inf
17,18.0,3,1.000000,0.000032,3.0,0.0,0.000036,0.000000,inf,0.000000,NaN,inf
18,19.0,1,1.000000,0.000011,1.0,0.0,0.000012,0.000000,inf,0.000000,NaN,inf

In [133]:
plot_by_woe(df_temp)
# We plot the weight of evidence values.

In [134]:
# Categories: 0, 1-3, >=4
df_inputs_prepr['delinq_2yrs:0'] = np.where((df_inputs_prepr['delinq_2yrs'] == 0), 1, 0)
df_inputs_prepr['delinq_2yrs:1-3'] = np.where((df_inputs_prepr['delinq_2yrs'] >= 1) & (df_inputs_prepr['delinq_2yrs'] <= 3), 1, 0)
df_inputs_prepr['delinq_2yrs:>=4'] = np.where((df_inputs_prepr['delinq_2yrs'] >= 9), 1, 0)

In [135]:
# inq_last_6mths
df_temp = woe_ordered_continuous(df_inputs_prepr, 'inq_last_6mths', df_targets_prepr)
# We calculate weight of evidence.
df_temp

C:\Users\Sanket\Anaconda4\lib\site-packages\pandas\core\series.py:679: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\Sanket\Anaconda4\lib\site-packages\pandas\core\algorithms.py:1926: RuntimeWarning: invalid value encountered in subtract
  out_arr[res_indexer] = arr[res_indexer] - arr[lag_indexer]

,inq_last_6mths,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,0.0,48295,0.910094,0.517870,43953.0,4342.0,0.529127,0.426104,0.216545,NaN,NaN,inf
1,1.0,25985,0.882394,0.278639,22929.0,3056.0,0.276030,0.299902,-0.082945,0.027701,0.299490,inf
2,2.0,11611,0.861252,0.124505,10000.0,1611.0,0.120385,0.158096,-0.272511,0.021141,0.189566,inf
3,3.0,5086,0.846245,0.054537,4304.0,782.0,0.051814,0.076742,-0.392795,0.015008,0.120285,inf
4,4.0,1431,0.841370,0.015345,1204.0,227.0,0.014494,0.022277,-0.429786,0.004875,0.036991,inf
5,5.0,551,0.842105,0.005908,464.0,87.0,0.005586,0.008538,-0.424264,0.000736,0.005522,inf
6,6.0,211,0.763033,0.002263,161.0,50.0,0.001938,0.004907,-0.928859,0.079072,0.504595,inf
7,7.0,36,0.527778,0.000386,19.0,17.0,0.000229,0.001668,-1.987015,0.235255,1.058156,inf
8,8.0,21,0.523810,0.000225,11.0,10.0,0.000132,0.000981,-2.002930,0.003968,0.015915,inf
9,9.0,7,0.428571,0.000075,3.0,4.0,0.000036,0.000393,-2.385923,0.095238,0.382992,inf
10,10.0,7,0.857143,0.000075,6.0,1.0,0.000072,0.000098,-0.306481,0.428571,2.079442,inf
11,11.0,7,1.000000,0.000075,7.0,0.0,0.000084,0.000000,inf,0.142857,inf,inf
12,12.0,3,1.000000,0.000032,3.0,0.0,0.000036,0.000000,inf,0.000000,NaN,inf
13,13.0,1,0.000000,0.000011,0.0,1.0,0.000000,0.000098,-inf,1.000000,inf,inf
14,14.0,1,0.000000,0.000011,0.0,1.0,0.000000,0.000098,-inf,0.000000,NaN,inf
15,18.0,2,0.500000,0.000021,1.0,1.0,0.000012,0.000098,-2.098241,0.500000,inf,inf
16,19.0,1,1.000000,0.000011,1.0,0.0,0.000012,0.000000,inf,0.500000,inf,inf
17,24.0,1,1.000000,0.000011,1.0,0.0,0.000012,0.000000,inf,0.000000,NaN,inf

In [136]:
plot_by_woe(df_temp)
# We plot the weight of evidence values.

In [137]:
# Categories: 0, 1 - 2, 3 - 6, > 6
df_inputs_prepr['inq_last_6mths:0'] = np.where((df_inputs_prepr['inq_last_6mths'] == 0), 1, 0)
df_inputs_prepr['inq_last_6mths:1-2'] = np.where((df_inputs_prepr['inq_last_6mths'] >= 1) & (df_inputs_prepr['inq_last_6mths'] <= 2), 1, 0)
df_inputs_prepr['inq_last_6mths:3-6'] = np.where((df_inputs_prepr['inq_last_6mths'] >= 3) & (df_inputs_prepr['inq_last_6mths'] <= 6), 1, 0)
df_inputs_prepr['inq_last_6mths:>6'] = np.where((df_inputs_prepr['inq_last_6mths'] > 6), 1, 0)

In [138]:
# open_acc
df_temp = woe_ordered_continuous(df_inputs_prepr, 'open_acc', df_targets_prepr)
# We calculate weight of evidence.
df_temp

C:\Users\Sanket\Anaconda4\lib\site-packages\pandas\core\algorithms.py:1926: RuntimeWarning: invalid value encountered in subtract
  out_arr[res_indexer] = arr[res_indexer] - arr[lag_indexer]

,open_acc,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,0.0,7,1.000000,0.000075,7.0,0.0,0.000084,0.000000,inf,NaN,NaN,inf
1,1.0,32,0.875000,0.000343,28.0,4.0,0.000337,0.000393,-0.152331,0.125000,inf,inf
2,2.0,334,0.838323,0.003582,280.0,54.0,0.003371,0.005299,-0.452435,0.036677,0.300105,inf
3,3.0,1122,0.852941,0.012031,957.0,165.0,0.011521,0.016192,-0.340383,0.014618,0.112052,inf
4,4.0,2560,0.892188,0.027451,2284.0,276.0,0.027496,0.027085,0.015042,0.039246,0.355425,inf
5,5.0,4403,0.891438,0.047214,3925.0,478.0,0.047251,0.046909,0.007270,0.000750,0.007772,inf
6,6.0,6216,0.890766,0.066655,5537.0,679.0,0.066657,0.066634,0.000346,0.000672,0.006924,inf
7,7.0,7433,0.886856,0.079704,6592.0,841.0,0.079358,0.082532,-0.039220,0.003910,0.039567,inf
8,8.0,8314,0.893433,0.089151,7428.0,886.0,0.089422,0.086948,0.028054,0.006577,0.067275,inf
9,9.0,8768,0.888230,0.094020,7788.0,980.0,0.093756,0.096173,-0.025454,0.005203,0.053508,inf
10,10.0,8576,0.889109,0.091961,7625.0,951.0,0.091793,0.093327,-0.016567,0.000879,0.008887,inf
11,11.0,7740,0.894444,0.082996,6923.0,817.0,0.083342,0.080177,0.038725,0.005335,0.055292,inf
12,12.0,6886,0.887017,0.073839,6108.0,778.0,0.073531,0.076349,-0.037613,0.007427,0.076337,inf
13,13.0,5914,0.893304,0.063416,5283.0,631.0,0.063599,0.061923,0.026703,0.006287,0.064315,inf
14,14.0,4960,0.895766,0.053186,4443.0,517.0,0.053487,0.050736,0.052802,0.002462,0.026099,inf
15,15.0,4006,0.892162,0.042957,3574.0,432.0,0.043026,0.042395,0.014774,0.003604,0.038027,inf
16,16.0,3269,0.898134,0.035054,2936.0,333.0,0.035345,0.032679,0.078420,0.005972,0.063646,inf
17,17.0,2680,0.886940,0.028738,2377.0,303.0,0.028615,0.029735,-0.038379,0.011194,0.116799,inf
18,18.0,2259,0.902169,0.024223,2038.0,221.0,0.024534,0.021688,0.123321,0.015229,0.161700,inf
19,19.0,1811,0.893429,0.019419,1618.0,193.0,0.019478,0.018940,0.028015,0.008740,0.095306,inf
20,20.0,1444,0.898199,0.015484,1297.0,147.0,0.015614,0.014426,0.079136,0.004770,0.051121,inf
21,21.0,1037,0.880424,0.011120,913.0,124.0,0.010991,0.012169,-0.101786,0.017775,0.180922,inf
22,22.0,784,0.887755,0.008407,696.0,88.0,0.008379,0.008636,-0.030228,0.007331,0.071559,inf
23,23.0,628,0.904459,0.006734,568.0,60.0,0.006838,0.005888,0.149536,0.016703,0.179764,inf
24,24.0,473,0.890063,0.005072,421.0,52.0,0.005068,0.005103,-0.006852,0.014395,0.156388,inf
25,25.0,391,0.882353,0.004193,345.0,46.0,0.004153,0.004514,-0.083338,0.007710,0.076486,inf
26,26.0,250,0.884000,0.002681,221.0,29.0,0.002661,0.002846,-0.067374,0.001647,0.015964,inf
27,27.0,204,0.911765,0.002188,186.0,18.0,0.002239,0.001766,0.237134,0.027765,0.304508,inf
28,28.0,153,0.895425,0.001641,137.0,16.0,0.001649,0.001570,0.049152,0.016340,0.187983,inf
29,29.0,128,0.843750,0.001373,108.0,20.0,0.001300,0.001963,-0.411842,0.051675,0.460993,inf
30,30.0,107,0.906542,0.001147,97.0,10.0,0.001168,0.000981,0.173885,0.062792,0.585727,inf
31,31.0,73,0.890411,0.000783,65.0,8.0,0.000783,0.000785,-0.003295,0.016131,0.177180,inf
32,32.0,62,0.951613,0.000665,59.0,3.0,0.000710,0.000294,0.880684,0.061202,0.883979,inf
33,33.0,47,0.851064,0.000504,40.0,7.0,0.000482,0.000687,-0.355271,0.100549,1.235956,inf
34,34.0,40,0.825000,0.000429,33.0,7.0,0.000397,0.000687,-0.547643,0.026064,0.192372,inf
35,35.0,33,0.939394,0.000354,31.0,2.0,0.000373,0.000196,0.642599,0.114394,1.190243,inf
36,36.0,22,0.772727,0.000236,17.0,5.0,0.000205,0.000491,-0.874465,0.166667,1.517065,inf
37,37.0,21,0.857143,0.000225,18.0,3.0,0.000217,0.000294,-0.306481,0.084416,0.567984,inf
38,38.0,14,0.928571,0.000150,13.0,1.0,0.000157,0.000098,0.466709,0.071429,0.773190,inf
39,39.0,12,0.916667,0.000129,11.0,1.0,0.000132,0.000098,0.299655,0.011905,0.167054,inf
40,40.0,9,0.555556,0.000097,5.0,4.0,0.000060,0.000393,-1.875097,0.361111,2.174752,inf
41,41.0,6,1.000000,0.000064,6.0,0.0,0.000072,0.000000,inf,0.444444,inf,inf
42,42.0,7,1.000000,0.000075,7.0,0.0,0.000084,0.000000,inf,0.000000,NaN,inf
43,43.0,4,1.000000,0.000043,4.0,0.0,0.000048,0.000000,inf,0.000000,NaN,inf
44,45.0,4,1.000000,0.000043,4.0,0.0,0.000048,0.000000,inf,0.000000,NaN,inf
45,46.0,2,1.000000,0.000021,2.0,0.0,0.000024,0.000000,inf,0.000000,NaN,inf
46,48.0,2,1.000000,0.000021,2.0,0.0,0.000024,0.000000,inf,0.000000,NaN,inf
47,49.0,2,1.000000,0.000021,2.0,0.0,0.000024,0.000000,inf,0.000000,NaN,inf
48,50.0,1,1.000000,0.000011,1.0,0.0,0.000012,0.000000,inf,0.000000,NaN,inf
49,52.0,1,1.000000,0.000011,1.0,0.0,0.000012,0.000000,inf,0.000000,NaN,inf
50,53.0,2,1.000000,0.000021,2.0,0.0,0.000024,0.000000,inf,0.000000,NaN,inf
51,58.0,3,1.000000,0.000032,3.0,0.0,0.000036,0.000000,inf,0.000000,NaN,inf
52,61.0,1,1.000000,0.000011,1.0,0.0,0.000012,0.000000,inf,0.000000,NaN,inf

In [139]:
plot_by_woe(df_temp, 90)
# We plot the weight of evidence values.

In [140]:
plot_by_woe(df_temp.iloc[ : 40, :], 90)
# We plot the weight of evidence values.

C:\Users\Sanket\Anaconda4\lib\site-packages\matplotlib\pyplot.py:523: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)

In [141]:
# Categories: '0', '1-3', '4-12', '13-17', '18-22', '23-25', '26-30', '>30'
df_inputs_prepr['open_acc:0'] = np.where((df_inputs_prepr['open_acc'] == 0), 1, 0)
df_inputs_prepr['open_acc:1-3'] = np.where((df_inputs_prepr['open_acc'] >= 1) & (df_inputs_prepr['open_acc'] <= 3), 1, 0)
df_inputs_prepr['open_acc:4-12'] = np.where((df_inputs_prepr['open_acc'] >= 4) & (df_inputs_prepr['open_acc'] <= 12), 1, 0)
df_inputs_prepr['open_acc:13-17'] = np.where((df_inputs_prepr['open_acc'] >= 13) & (df_inputs_prepr['open_acc'] <= 17), 1, 0)
df_inputs_prepr['open_acc:18-22'] = np.where((df_inputs_prepr['open_acc'] >= 18) & (df_inputs_prepr['open_acc'] <= 22), 1, 0)
df_inputs_prepr['open_acc:23-25'] = np.where((df_inputs_prepr['open_acc'] >= 23) & (df_inputs_prepr['open_acc'] <= 25), 1, 0)
df_inputs_prepr['open_acc:26-30'] = np.where((df_inputs_prepr['open_acc'] >= 26) & (df_inputs_prepr['open_acc'] <= 30), 1, 0)
df_inputs_prepr['open_acc:>=31'] = np.where((df_inputs_prepr['open_acc'] >= 31), 1, 0)

In [142]:
# pub_rec
df_temp = woe_ordered_continuous(df_inputs_prepr, 'pub_rec', df_targets_prepr)
# We calculate weight of evidence.
df_temp

C:\Users\Sanket\Anaconda4\lib\site-packages\pandas\core\algorithms.py:1926: RuntimeWarning: invalid value encountered in subtract
  out_arr[res_indexer] = arr[res_indexer] - arr[lag_indexer]

,pub_rec,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,0.0,80923,0.889179,0.867742,71955.0,8968.0,0.866228,0.880079,-0.015862,NaN,NaN,inf
1,1.0,10670,0.901125,0.114415,9615.0,1055.0,0.115750,0.103533,0.111543,0.011946,0.127405,inf
2,2.0,1097,0.904284,0.011763,992.0,105.0,0.011942,0.010304,0.147522,0.003160,0.035979,inf
3,3.0,331,0.900302,0.003549,298.0,33.0,0.003587,0.003238,0.102345,0.003982,0.045177,inf
4,4.0,112,0.857143,0.001201,96.0,16.0,0.001156,0.001570,-0.306481,0.043159,0.408826,inf
5,5.0,73,0.904110,0.000783,66.0,7.0,0.000795,0.000687,0.145504,0.046967,0.451985,inf
6,6.0,19,0.894737,0.000204,17.0,2.0,0.000205,0.000196,0.041825,0.009373,0.103678,inf
7,7.0,14,0.785714,0.000150,11.0,3.0,0.000132,0.000294,-0.798958,0.109023,0.840783,inf
8,8.0,5,0.800000,0.000054,4.0,1.0,0.000048,0.000098,-0.711946,0.014286,0.087011,inf
9,9.0,2,1.000000,0.000021,2.0,0.0,0.000024,0.000000,inf,0.200000,inf,inf
10,10.0,3,1.000000,0.000032,3.0,0.0,0.000036,0.000000,inf,0.000000,NaN,inf
11,11.0,5,1.000000,0.000054,5.0,0.0,0.000060,0.000000,inf,0.000000,NaN,inf
12,12.0,1,1.000000,0.000011,1.0,0.0,0.000012,0.000000,inf,0.000000,NaN,inf
13,14.0,1,1.000000,0.000011,1.0,0.0,0.000012,0.000000,inf,0.000000,NaN,inf
14,49.0,1,1.000000,0.000011,1.0,0.0,0.000012,0.000000,inf,0.000000,NaN,inf

In [143]:
plot_by_woe(df_temp, 90)
# We plot the weight of evidence values.

C:\Users\Sanket\Anaconda4\lib\site-packages\matplotlib\pyplot.py:523: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)

In [144]:
# Categories '0-2', '3-4', '>=5'
df_inputs_prepr['pub_rec:0-2'] = np.where((df_inputs_prepr['pub_rec'] >= 0) & (df_inputs_prepr['pub_rec'] <= 2), 1, 0)
df_inputs_prepr['pub_rec:3-4'] = np.where((df_inputs_prepr['pub_rec'] >= 3) & (df_inputs_prepr['pub_rec'] <= 4), 1, 0)
df_inputs_prepr['pub_rec:>=5'] = np.where((df_inputs_prepr['pub_rec'] >= 5), 1, 0)

In [145]:
# total_acc
df_inputs_prepr['total_acc_factor'] = pd.cut(df_inputs_prepr['total_acc'], 50)
# Here we do fine-classing: using the 'cut' method, we split the variable into 50 categories by its values.
df_temp = woe_ordered_continuous(df_inputs_prepr, 'total_acc_factor', df_targets_prepr)
# We calculate weight of evidence.
df_temp

C:\Users\Sanket\Anaconda4\lib\site-packages\pandas\core\algorithms.py:1926: RuntimeWarning: invalid value encountered in subtract
  out_arr[res_indexer] = arr[res_indexer] - arr[lag_indexer]

,total_acc_factor,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,"(-0.156, 3.12]",125,0.776000,0.001340,97.0,28.0,0.001168,0.002748,-0.855734,NaN,NaN,inf
1,"(3.12, 6.24]",1499,0.850567,0.016074,1275.0,224.0,0.015349,0.021982,-0.359185,0.074567,0.496549,inf
2,"(6.24, 9.36]",3715,0.871871,0.039836,3239.0,476.0,0.038993,0.046712,-0.180639,0.021304,0.178547,inf
3,"(9.36, 12.48]",6288,0.874841,0.067427,5501.0,787.0,0.066224,0.077233,-0.153784,0.002970,0.026855,inf
4,"(12.48, 15.6]",8289,0.888286,0.088883,7363.0,926.0,0.088639,0.090873,-0.024892,0.013445,0.128892,inf
5,"(15.6, 18.72]",9843,0.890176,0.105547,8762.0,1081.0,0.105481,0.106084,-0.005703,0.001890,0.019189,inf
6,"(18.72, 21.84]",10270,0.893866,0.110126,9180.0,1090.0,0.110513,0.106968,0.032609,0.003690,0.038312,inf
7,"(21.84, 24.96]",9971,0.892789,0.106920,8902.0,1069.0,0.107167,0.104907,0.021312,0.001077,0.011297,inf
8,"(24.96, 28.08]",11873,0.892108,0.127315,10592.0,1281.0,0.127512,0.125711,0.014217,0.000681,0.007094,inf
9,"(28.08, 31.2]",7289,0.892715,0.078160,6507.0,782.0,0.078334,0.076742,0.020538,0.000607,0.006321,inf
10,"(31.2, 34.32]",6151,0.902617,0.065958,5552.0,599.0,0.066838,0.058783,0.128411,0.009902,0.107873,inf
11,"(34.32, 37.44]",4745,0.905796,0.050881,4298.0,447.0,0.051741,0.043867,0.165106,0.003178,0.036695,inf
12,"(37.44, 40.56]",3615,0.897372,0.038764,3244.0,371.0,0.039053,0.036408,0.070120,0.008424,0.094986,inf
13,"(40.56, 43.68]",2883,0.890045,0.030915,2566.0,317.0,0.030891,0.031109,-0.007039,0.007327,0.077159,inf
14,"(43.68, 46.8]",1938,0.891641,0.020781,1728.0,210.0,0.020802,0.020608,0.009372,0.001596,0.016411,inf
15,"(46.8, 49.92]",1478,0.905954,0.015849,1339.0,139.0,0.016120,0.013641,0.166964,0.014313,0.157592,inf
16,"(49.92, 53.04]",1309,0.902215,0.014036,1181.0,128.0,0.014217,0.012561,0.123846,0.003739,0.043118,inf
17,"(53.04, 56.16]",640,0.893750,0.006863,572.0,68.0,0.006886,0.006673,0.031391,0.008465,0.092455,inf
18,"(56.16, 59.28]",428,0.873832,0.004589,374.0,54.0,0.004502,0.005299,-0.162969,0.019918,0.194360,inf
19,"(59.28, 62.4]",386,0.878238,0.004139,339.0,47.0,0.004081,0.004612,-0.122388,0.004407,0.040581,inf
20,"(62.4, 65.52]",322,0.844720,0.003453,272.0,50.0,0.003274,0.004907,-0.404462,0.033518,0.282073,inf
21,"(65.52, 68.64]",57,0.947368,0.000611,54.0,3.0,0.000650,0.000294,0.792131,0.102648,1.196593,inf
22,"(68.64, 71.76]",43,0.906977,0.000461,39.0,4.0,0.000470,0.000393,0.179027,0.040392,0.613104,inf
23,"(71.76, 74.88]",24,1.000000,0.000257,24.0,0.0,0.000289,0.000000,inf,0.093023,inf,inf
24,"(74.88, 78.0]",26,0.923077,0.000279,24.0,2.0,0.000289,0.000196,0.386666,0.076923,inf,inf
25,"(78.0, 81.12]",13,0.769231,0.000139,10.0,3.0,0.000120,0.000294,-0.894268,0.153846,1.280934,inf
26,"(81.12, 84.24]",11,0.909091,0.000118,10.0,1.0,0.000120,0.000098,0.204344,0.139860,1.098612,inf
27,"(84.24, 87.36]",8,0.875000,0.000086,7.0,1.0,0.000084,0.000098,-0.152331,0.034091,0.356675,inf
28,"(87.36, 90.48]",6,0.833333,0.000064,5.0,1.0,0.000060,0.000098,-0.488803,0.041667,0.336472,inf
29,"(90.48, 93.6]",7,0.857143,0.000075,6.0,1.0,0.000072,0.000098,-0.306481,0.023810,0.182322,inf
30,"(93.6, 96.72]",1,1.000000,0.000011,1.0,0.0,0.000012,0.000000,inf,0.142857,inf,inf
31,"(96.72, 99.84]",3,1.000000,0.000032,3.0,0.0,0.000036,0.000000,inf,0.000000,NaN,inf
32,"(99.84, 102.96]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
33,"(102.96, 106.08]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
34,"(106.08, 109.2]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
35,"(109.2, 112.32]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
36,"(112.32, 115.44]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
37,"(115.44, 118.56]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
38,"(118.56, 121.68]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
39,"(121.68, 124.8]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
40,"(124.8, 127.92]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
41,"(127.92, 131.04]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
42,"(131.04, 134.16]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
43,"(134.16, 137.28]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
44,"(137.28, 140.4]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
45,"(140.4, 143.52]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
46,"(143.52, 146.64]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
47,"(146.64, 149.76]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
48,"(149.76, 152.88]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
49,"(152.88, 156.0]",1,1.000000,0.000011,1.0,0.0,0.000012,0.000000,inf,NaN,NaN,inf

In [146]:
plot_by_woe(df_temp, 90)
# We plot the weight of evidence values.

C:\Users\Sanket\Anaconda4\lib\site-packages\matplotlib\pyplot.py:523: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)

In [147]:
# Categories: '<=27', '28-51', '>51'
df_inputs_prepr['total_acc:<=27'] = np.where((df_inputs_prepr['total_acc'] <= 27), 1, 0)
df_inputs_prepr['total_acc:28-51'] = np.where((df_inputs_prepr['total_acc'] >= 28) & (df_inputs_prepr['total_acc'] <= 51), 1, 0)
df_inputs_prepr['total_acc:>=52'] = np.where((df_inputs_prepr['total_acc'] >= 52), 1, 0)

In [148]:
# acc_now_delinq
df_temp = woe_ordered_continuous(df_inputs_prepr, 'acc_now_delinq', df_targets_prepr)
# We calculate weight of evidence.
df_temp

,acc_now_delinq,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,0.0,92871,0.890827,0.995861,82732.0,10139.0,0.995967,0.994995,0.000976,NaN,NaN,0.000298
1,1.0,360,0.872222,0.003860,314.0,46.0,0.003780,0.004514,-0.177489,0.018605,0.178466,0.000298
2,2.0,22,0.818182,0.000236,18.0,4.0,0.000217,0.000393,-0.594163,0.054040,0.416674,0.000298
3,3.0,4,0.750000,0.000043,3.0,1.0,0.000036,0.000098,-0.999628,0.068182,0.405465,0.000298

In [149]:
plot_by_woe(df_temp)
# We plot the weight of evidence values.

C:\Users\Sanket\Anaconda4\lib\site-packages\matplotlib\pyplot.py:523: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)

In [150]:
# Categories: '0', '>=1'
df_inputs_prepr['acc_now_delinq:0'] = np.where((df_inputs_prepr['acc_now_delinq'] == 0), 1, 0)
df_inputs_prepr['acc_now_delinq:>=1'] = np.where((df_inputs_prepr['acc_now_delinq'] >= 1), 1, 0)

In [151]:
# total_rev_hi_lim
df_inputs_prepr['total_rev_hi_lim_factor'] = pd.cut(df_inputs_prepr['total_rev_hi_lim'], 2000)
# Here we do fine-classing: using the 'cut' method, we split the variable into 2000 categories by its values.
df_temp = woe_ordered_continuous(df_inputs_prepr, 'total_rev_hi_lim_factor', df_targets_prepr)
# We calculate weight of evidence.
df_temp

C:\Users\Sanket\Anaconda4\lib\site-packages\pandas\core\series.py:679: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\Sanket\Anaconda4\lib\site-packages\pandas\core\algorithms.py:1926: RuntimeWarning: invalid value encountered in subtract
  out_arr[res_indexer] = arr[res_indexer] - arr[lag_indexer]

,total_rev_hi_lim_factor,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,"(-2013.133, 1006.566]",238,0.840336,0.002552,200.0,38.0,0.002408,0.003729,-0.437509,NaN,NaN,inf
1,"(1006.566, 2013.133]",678,0.827434,0.007270,561.0,117.0,0.006754,0.011482,-0.530694,0.012903,0.093184,inf
2,"(2013.133, 3019.7]",1121,0.852810,0.012021,956.0,165.0,0.011509,0.016192,-0.341428,0.025376,0.189265,inf
3,"(3019.7, 4026.266]",1461,0.878166,0.015666,1283.0,178.0,0.015445,0.017468,-0.123068,0.025356,0.218360,inf
4,"(4026.266, 5032.832]",2163,0.867776,0.023194,1877.0,286.0,0.022596,0.028067,-0.216802,0.010389,0.093735,inf
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,"(2008100.168, 2009106.734]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
1996,"(2009106.734, 2010113.301]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
1997,"(2010113.301, 2011119.867]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
1998,"(2011119.867, 2012126.434]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
1999,"(2012126.434, 2013133.0]",1,1.000000,0.000011,1.0,0.0,0.000012,0.000000,inf,NaN,NaN,inf

In [152]:
plot_by_woe(df_temp.iloc[: 50, : ], 90)
# We plot the weight of evidence values.

C:\Users\Sanket\Anaconda4\lib\site-packages\matplotlib\pyplot.py:523: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)

In [153]:
# Categories
# '<=5K', '5K-10K', '10K-20K', '20K-30K', '30K-40K', '40K-55K', '55K-95K', '>95K'
df_inputs_prepr['total_rev_hi_lim:<=5K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] <= 5000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:5K-10K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 5000) & (df_inputs_prepr['total_rev_hi_lim'] <= 10000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:10K-20K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 10000) & (df_inputs_prepr['total_rev_hi_lim'] <= 20000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:20K-30K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 20000) & (df_inputs_prepr['total_rev_hi_lim'] <= 30000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:30K-40K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 30000) & (df_inputs_prepr['total_rev_hi_lim'] <= 40000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:40K-55K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 40000) & (df_inputs_prepr['total_rev_hi_lim'] <= 55000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:55K-95K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 55000) & (df_inputs_prepr['total_rev_hi_lim'] <= 95000), 1, 0)
df_inputs_prepr['total_rev_hi_lim:>95K'] = np.where((df_inputs_prepr['total_rev_hi_lim'] > 95000), 1, 0)

In [154]:
# installment
df_inputs_prepr['installment_factor'] = pd.cut(df_inputs_prepr['installment'], 50)
# Here we do fine-classing: using the 'cut' method, we split the variable into 50 categories by its values.
df_temp = woe_ordered_continuous(df_inputs_prepr, 'installment_factor', df_targets_prepr)
# We calculate weight of evidence.
df_temp

,installment_factor,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,"(14.369, 43.585]",485,0.872165,0.005201,423.0,62.0,0.005092,0.006084,-0.178003,NaN,NaN,inf
1,"(43.585, 71.41]",1246,0.904494,0.013361,1127.0,119.0,0.013567,0.011678,0.149950,0.032329,0.327953,inf
2,"(71.41, 99.235]",1731,0.895436,0.018562,1550.0,181.0,0.018660,0.017763,0.049273,0.009058,0.100678,inf
3,"(99.235, 127.06]",2292,0.896597,0.024577,2055.0,237.0,0.024739,0.023258,0.061730,0.001161,0.012458,inf
4,"(127.06, 154.885]",2602,0.886241,0.027901,2306.0,296.0,0.027761,0.029048,-0.045330,0.010356,0.107061,inf
5,"(154.885, 182.71]",4133,0.897653,0.044318,3710.0,423.0,0.044663,0.041511,0.073174,0.011412,0.118505,inf
6,"(182.71, 210.535]",4109,0.905086,0.044061,3719.0,390.0,0.044771,0.038273,0.156823,0.007433,0.083648,inf
7,"(210.535, 238.36]",3730,0.901877,0.039997,3364.0,366.0,0.040497,0.035918,0.120012,0.003210,0.036811,inf
8,"(238.36, 266.185]",4660,0.899785,0.049969,4193.0,467.0,0.050477,0.045829,0.096602,0.002091,0.023410,inf
9,"(266.185, 294.01]",4975,0.888844,0.053347,4422.0,553.0,0.053234,0.054269,-0.019251,0.010941,0.115853,inf
10,"(294.01, 321.835]",5186,0.906286,0.055610,4700.0,486.0,0.056581,0.047694,0.170868,0.017442,0.190120,inf
11,"(321.835, 349.66]",6432,0.892568,0.068971,5741.0,691.0,0.069113,0.067812,0.019008,0.013718,0.151860,inf
12,"(349.66, 377.485]",4758,0.881673,0.051020,4195.0,563.0,0.050501,0.055250,-0.089872,0.010895,0.108880,inf
13,"(377.485, 405.31]",4352,0.900276,0.046667,3918.0,434.0,0.047167,0.042591,0.102051,0.018603,0.191923,inf
14,"(405.31, 433.135]",3429,0.882765,0.036769,3027.0,402.0,0.036440,0.039450,-0.079365,0.017511,0.181417,inf
15,"(433.135, 460.96]",3225,0.879380,0.034582,2836.0,389.0,0.034141,0.038175,-0.111670,0.003385,0.032305,inf
16,"(460.96, 488.785]",3865,0.894437,0.041445,3457.0,408.0,0.041617,0.040039,0.038649,0.015057,0.150319,inf
17,"(488.785, 516.61]",3861,0.884227,0.041402,3414.0,447.0,0.041099,0.043867,-0.065159,0.010210,0.103808,inf
18,"(516.61, 544.435]",2730,0.868864,0.029274,2372.0,358.0,0.028555,0.035132,-0.207285,0.015362,0.142126,inf
19,"(544.435, 572.26]",2564,0.877535,0.027494,2250.0,314.0,0.027087,0.030815,-0.128948,0.008671,0.078337,inf
20,"(572.26, 600.085]",2434,0.873870,0.026100,2127.0,307.0,0.025606,0.030128,-0.162621,0.003665,0.033672,inf
21,"(600.085, 627.91]",2294,0.901918,0.024599,2069.0,225.0,0.024908,0.022080,0.120480,0.028048,0.283100,inf
22,"(627.91, 655.735]",2091,0.901004,0.022422,1884.0,207.0,0.022680,0.020314,0.110193,0.000914,0.010287,inf
23,"(655.735, 683.56]",2295,0.894989,0.024609,2054.0,241.0,0.024727,0.023651,0.044507,0.006015,0.065686,inf
24,"(683.56, 711.385]",1650,0.876970,0.017693,1447.0,203.0,0.017420,0.019921,-0.134199,0.018019,0.178706,inf
25,"(711.385, 739.21]",1252,0.892173,0.013425,1117.0,135.0,0.013447,0.013248,0.014886,0.015203,0.149085,inf
26,"(739.21, 767.035]",1360,0.897794,0.014583,1221.0,139.0,0.014699,0.013641,0.074711,0.005622,0.059825,inf
27,"(767.035, 794.86]",1160,0.886207,0.012439,1028.0,132.0,0.012376,0.012954,-0.045672,0.011587,0.120383,inf
28,"(794.86, 822.685]",1023,0.888563,0.010970,909.0,114.0,0.010943,0.011187,-0.022094,0.002356,0.023578,inf
29,"(822.685, 850.51]",967,0.885212,0.010369,856.0,111.0,0.010305,0.010893,-0.055500,0.003351,0.033406,inf
30,"(850.51, 878.335]",1046,0.894837,0.011216,936.0,110.0,0.011268,0.010795,0.042894,0.009625,0.098395,inf
31,"(878.335, 906.16]",707,0.861386,0.007581,609.0,98.0,0.007331,0.009617,-0.271390,0.033451,0.314284,inf
32,"(906.16, 933.985]",604,0.855960,0.006477,517.0,87.0,0.006224,0.008538,-0.316106,0.005426,0.044716,inf
33,"(933.985, 961.81]",635,0.861417,0.006809,547.0,88.0,0.006585,0.008636,-0.271129,0.005457,0.044977,inf
34,"(961.81, 989.635]",460,0.850000,0.004933,391.0,69.0,0.004707,0.006771,-0.363640,0.011417,0.092511,inf
35,"(989.635, 1017.46]",441,0.854875,0.004729,377.0,64.0,0.004539,0.006281,-0.324879,0.004875,0.038761,inf
36,"(1017.46, 1045.285]",305,0.875410,0.003271,267.0,38.0,0.003214,0.003729,-0.148578,0.020535,0.176300,inf
37,"(1045.285, 1073.11]",206,0.878641,0.002209,181.0,25.0,0.002179,0.002453,-0.118619,0.003231,0.029959,inf
38,"(1073.11, 1100.935]",228,0.894737,0.002445,204.0,24.0,0.002456,0.002355,0.041825,0.016096,0.160445,inf
39,"(1100.935, 1128.76]",247,0.931174,0.002649,230.0,17.0,0.002769,0.001668,0.506625,0.036437,0.464800,inf
40,"(1128.76, 1156.585]",227,0.916300,0.002434,208.0,19.0,0.002504,0.001865,0.294858,0.014875,0.211767,inf
41,"(1156.585, 1184.41]",287,0.895470,0.003078,257.0,30.0,0.003094,0.002944,0.049638,0.020829,0.245220,inf
42,"(1184.41, 1212.235]",308,0.905844,0.003303,279.0,29.0,0.003359,0.002846,0.165675,0.010374,0.116037,inf
43,"(1212.235, 1240.06]",284,0.901408,0.003045,256.0,28.0,0.003082,0.002748,0.114732,0.004436,0.050943,inf
44,"(1240.06, 1267.885]",159,0.861635,0.001705,137.0,22.0,0.001649,0.002159,-0.269302,0.039773,0.384034,inf
45,"(1267.885, 1295.71]",132,0.833333,0.001415,110.0,22.0,0.001324,0.002159,-0.488803,0.028302,0.219501,inf
46,"(1295.71, 1323.535]",47,0.787234,0.000504,37.0,10.0,0.000445,0.000981,-0.789908,0.046099,0.301105,inf
47,"(1323.535, 1351.36]",21,0.714286,0.000225,15.0,6.0,0.000181,0.000589,-1.181950,0.072948,0.392042,inf
48,"(1351.36, 1379.185]",15,0.733333,0.000161,11.0,4.0,0.000132,0.000393,-1.086640,0.019048,0.095310,inf
49,"(1379.185, 1407.01]",7,1.000000,0.000075,7.0,0.0,0.000084,0.000000,inf,0.266667,inf,inf

In [155]:
plot_by_woe(df_temp, 90)
# We plot the weight of evidence values.

C:\Users\Sanket\Anaconda4\lib\site-packages\matplotlib\pyplot.py:523: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)

### Preprocessing Continuous Variables: Creating Dummy Variables, Part 3

In [156]:
# annual_inc
df_inputs_prepr['annual_inc_factor'] = pd.cut(df_inputs_prepr['annual_inc'], 50)
# Here we do fine-classing: using the 'cut' method, we split the variable into 50 categories by its values.
df_temp = woe_ordered_continuous(df_inputs_prepr, 'annual_inc_factor', df_targets_prepr)
# We calculate weight of evidence.
df_temp

C:\Users\Sanket\Anaconda4\lib\site-packages\pandas\core\algorithms.py:1926: RuntimeWarning: invalid value encountered in subtract
  out_arr[res_indexer] = arr[res_indexer] - arr[lag_indexer]

,annual_inc_factor,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,"(-2695.2, 154704.0]",89203,0.889040,0.956529,79305.0,9898.0,0.954711,0.971344,-0.017272,NaN,NaN,inf
1,"(154704.0, 304608.0]",3626,0.926641,0.038882,3360.0,266.0,0.040449,0.026104,0.437959,0.037601,0.455231,inf
2,"(304608.0, 454512.0]",282,0.929078,0.003024,262.0,20.0,0.003154,0.001963,0.474372,0.002437,0.036412,inf
3,"(454512.0, 604416.0]",86,0.965116,0.000922,83.0,3.0,0.000999,0.000294,1.221988,0.036038,0.747616,inf
4,"(604416.0, 754320.0]",23,0.956522,0.000247,22.0,1.0,0.000265,0.000098,0.992802,0.008595,0.229186,inf
5,"(754320.0, 904224.0]",18,0.944444,0.000193,17.0,1.0,0.000205,0.000098,0.734973,0.012077,0.257829,inf
6,"(904224.0, 1054128.0]",7,1.000000,0.000075,7.0,0.0,0.000084,0.000000,inf,0.055556,inf,inf
7,"(1054128.0, 1204032.0]",6,1.000000,0.000064,6.0,0.0,0.000072,0.000000,inf,0.000000,NaN,inf
8,"(1204032.0, 1353936.0]",2,0.500000,0.000021,1.0,1.0,0.000012,0.000098,-2.098241,0.500000,inf,inf
9,"(1353936.0, 1503840.0]",2,1.000000,0.000021,2.0,0.0,0.000024,0.000000,inf,0.500000,inf,inf
10,"(1503840.0, 1653744.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
11,"(1653744.0, 1803648.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
12,"(1803648.0, 1953552.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
13,"(1953552.0, 2103456.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
14,"(2103456.0, 2253360.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
15,"(2253360.0, 2403264.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
16,"(2403264.0, 2553168.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
17,"(2553168.0, 2703072.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
18,"(2703072.0, 2852976.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
19,"(2852976.0, 3002880.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
20,"(3002880.0, 3152784.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
21,"(3152784.0, 3302688.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
22,"(3302688.0, 3452592.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
23,"(3452592.0, 3602496.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
24,"(3602496.0, 3752400.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
25,"(3752400.0, 3902304.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
26,"(3902304.0, 4052208.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
27,"(4052208.0, 4202112.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
28,"(4202112.0, 4352016.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
29,"(4352016.0, 4501920.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
30,"(4501920.0, 4651824.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
31,"(4651824.0, 4801728.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
32,"(4801728.0, 4951632.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
33,"(4951632.0, 5101536.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
34,"(5101536.0, 5251440.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
35,"(5251440.0, 5401344.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
36,"(5401344.0, 5551248.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
37,"(5551248.0, 5701152.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
38,"(5701152.0, 5851056.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
39,"(5851056.0, 6000960.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
40,"(6000960.0, 6150864.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
41,"(6150864.0, 6300768.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
42,"(6300768.0, 6450672.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
43,"(6450672.0, 6600576.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
44,"(6600576.0, 6750480.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
45,"(6750480.0, 6900384.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
46,"(6900384.0, 7050288.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
47,"(7050288.0, 7200192.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
48,"(7200192.0, 7350096.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
49,"(7350096.0, 7500000.0]",2,1.000000,0.000021,2.0,0.0,0.000024,0.000000,inf,NaN,NaN,inf

In [157]:
df_inputs_prepr['annual_inc_factor'] = pd.cut(df_inputs_prepr['annual_inc'], 100)
# Here we do fine-classing: using the 'cut' method, we split the variable into 100 categories by its values.
df_temp = woe_ordered_continuous(df_inputs_prepr, 'annual_inc_factor', df_targets_prepr)
# We calculate weight of evidence.
df_temp

C:\Users\Sanket\Anaconda4\lib\site-packages\pandas\core\algorithms.py:1926: RuntimeWarning: invalid value encountered in subtract
  out_arr[res_indexer] = arr[res_indexer] - arr[lag_indexer]

,annual_inc_factor,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,"(-2695.2, 79752.0]",62621,0.877932,0.671488,54977.0,7644.0,0.661839,0.750147,-0.125247,NaN,NaN,inf
1,"(79752.0, 154704.0]",26582,0.915206,0.285040,24328.0,2254.0,0.292872,0.221197,0.280681,0.037273,0.405928,inf
2,"(154704.0, 229656.0]",2916,0.926269,0.031268,2701.0,215.0,0.032516,0.021099,0.432499,0.011063,0.151818,inf
3,"(229656.0, 304608.0]",710,0.928169,0.007613,659.0,51.0,0.007933,0.005005,0.460657,0.001900,0.028159,inf
4,"(304608.0, 379560.0]",171,0.929825,0.001834,159.0,12.0,0.001914,0.001178,0.485757,0.001656,0.025100,inf
5,"(379560.0, 454512.0]",111,0.927928,0.001190,103.0,8.0,0.001240,0.000785,0.457047,0.001897,0.028710,inf
6,"(454512.0, 529464.0]",53,0.962264,0.000568,51.0,2.0,0.000614,0.000196,1.140438,0.034336,0.683391,inf
7,"(529464.0, 604416.0]",33,0.969697,0.000354,32.0,1.0,0.000385,0.000098,1.367495,0.007433,0.227057,inf
8,"(604416.0, 679368.0]",10,1.000000,0.000107,10.0,0.0,0.000120,0.000000,inf,0.030303,inf,inf
9,"(679368.0, 754320.0]",13,0.923077,0.000139,12.0,1.0,0.000144,0.000098,0.386666,0.076923,inf,inf
10,"(754320.0, 829272.0]",5,1.000000,0.000054,5.0,0.0,0.000060,0.000000,inf,0.076923,inf,inf
11,"(829272.0, 904224.0]",13,0.923077,0.000139,12.0,1.0,0.000144,0.000098,0.386666,0.076923,inf,inf
12,"(904224.0, 979176.0]",3,1.000000,0.000032,3.0,0.0,0.000036,0.000000,inf,0.076923,inf,inf
13,"(979176.0, 1054128.0]",4,1.000000,0.000043,4.0,0.0,0.000048,0.000000,inf,0.000000,NaN,inf
14,"(1054128.0, 1129080.0]",3,1.000000,0.000032,3.0,0.0,0.000036,0.000000,inf,0.000000,NaN,inf
15,"(1129080.0, 1204032.0]",3,1.000000,0.000032,3.0,0.0,0.000036,0.000000,inf,0.000000,NaN,inf
16,"(1204032.0, 1278984.0]",2,0.500000,0.000021,1.0,1.0,0.000012,0.000098,-2.098241,0.500000,inf,inf
17,"(1278984.0, 1353936.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
18,"(1353936.0, 1428888.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
19,"(1428888.0, 1503840.0]",2,1.000000,0.000021,2.0,0.0,0.000024,0.000000,inf,NaN,NaN,inf
20,"(1503840.0, 1578792.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
21,"(1578792.0, 1653744.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
22,"(1653744.0, 1728696.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
23,"(1728696.0, 1803648.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
24,"(1803648.0, 1878600.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
25,"(1878600.0, 1953552.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
26,"(1953552.0, 2028504.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
27,"(2028504.0, 2103456.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
28,"(2103456.0, 2178408.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
29,"(2178408.0, 2253360.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
30,"(2253360.0, 2328312.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
31,"(2328312.0, 2403264.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
32,"(2403264.0, 2478216.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
33,"(2478216.0, 2553168.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
34,"(2553168.0, 2628120.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
35,"(2628120.0, 2703072.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
36,"(2703072.0, 2778024.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
37,"(2778024.0, 2852976.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
38,"(2852976.0, 2927928.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
39,"(2927928.0, 3002880.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
40,"(3002880.0, 3077832.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
41,"(3077832.0, 3152784.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
42,"(3152784.0, 3227736.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
43,"(3227736.0, 3302688.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
44,"(3302688.0, 3377640.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
45,"(3377640.0, 3452592.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
46,"(3452592.0, 3527544.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
47,"(3527544.0, 3602496.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
48,"(3602496.0, 3677448.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
49,"(3677448.0, 3752400.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
50,"(3752400.0, 3827352.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
51,"(3827352.0, 3902304.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
52,"(3902304.0, 3977256.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
53,"(3977256.0, 4052208.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
54,"(4052208.0, 4127160.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
55,"(4127160.0, 4202112.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
56,"(4202112.0, 4277064.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
57,"(4277064.0, 4352016.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
58,"(4352016.0, 4426968.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
59,"(4426968.0, 4501920.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
60,"(4501920.0, 4576872.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
61,"(4576872.0, 4651824.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
62,"(4651824.0, 4726776.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
63,"(4726776.0, 4801728.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
64,"(4801728.0, 4876680.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
65,"(4876680.0, 4951632.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
66,"(4951632.0, 5026584.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
67,"(5026584.0, 5101536.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
68,"(5101536.0, 5176488.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
69,"(5176488.0, 5251440.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
70,"(5251440.0, 5326392.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
71,"(5326392.0, 5401344.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
72,"(5401344.0, 5476296.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
73,"(5476296.0, 5551248.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
74,"(5551248.0, 5626200.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
75,"(5626200.0, 5701152.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
76,"(5701152.0, 5776104.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
77,"(5776104.0, 5851056.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
78,"(5851056.0, 5926008.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
79,"(5926008.0, 6000960.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
80,"(6000960.0, 6075912.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
81,"(6075912.0, 6150864.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
82,"(6150864.0, 6225816.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
83,"(6225816.0, 6300768.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
84,"(6300768.0, 6375720.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
85,"(6375720.0, 6450672.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
86,"(6450672.0, 6525624.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
87,"(6525624.0, 6600576.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
88,"(6600576.0, 6675528.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
89,"(6675528.0, 6750480.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
90,"(6750480.0, 6825432.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
91,"(6825432.0, 6900384.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
92,"(6900384.0, 6975336.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
93,"(6975336.0, 7050288.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
94,"(7050288.0, 7125240.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
95,"(7125240.0, 7200192.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
96,"(7200192.0, 7275144.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
97,"(7275144.0, 7350096.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
98,"(7350096.0, 7425048.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
99,"(7425048.0, 7500000.0]",2,1.000000,0.000021,2.0,0.0,0.000024,0.000000,inf,NaN,NaN,inf

In [158]:
# Initial examination shows that there are too few individuals with large income and too many with small income.
# Hence, we are going to have one category for more than 150K, and we are going to apply our approach to determine
# the categories of everyone with 140k or less.
df_inputs_prepr_temp = df_inputs_prepr.loc[df_inputs_prepr['annual_inc'] <= 140000, : ]
#loan_data_temp = loan_data_temp.reset_index(drop = True)
#df_inputs_prepr_temp

In [159]:
df_inputs_prepr_temp["annual_inc_factor"] = pd.cut(df_inputs_prepr_temp['annual_inc'], 50)
# Here we do fine-classing: using the 'cut' method, we split the variable into 50 categories by its values.
df_temp = woe_ordered_continuous(df_inputs_prepr_temp, 'annual_inc_factor', df_targets_prepr[df_inputs_prepr_temp.index])
# We calculate weight of evidence.
df_temp

C:\Users\Sanket\Anaconda4\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,annual_inc_factor,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,"(4664.8, 7504.0]",10,1.000000,0.000114,10.0,0.0,0.000128,0.000000,inf,NaN,NaN,inf
1,"(7504.0, 10208.0]",84,0.761905,0.000958,64.0,20.0,0.000822,0.002043,-0.911157,0.238095,inf,inf
2,"(10208.0, 12912.0]",123,0.780488,0.001403,96.0,27.0,0.001232,0.002758,-0.805796,0.018583,0.105361,inf
3,"(12912.0, 15616.0]",304,0.851974,0.003467,259.0,45.0,0.003325,0.004597,-0.324142,0.071486,0.481654,inf
4,"(15616.0, 18320.0]",383,0.827676,0.004368,317.0,66.0,0.004069,0.006743,-0.505060,0.024297,0.180919,inf
5,"(18320.0, 21024.0]",733,0.840382,0.008359,616.0,117.0,0.007907,0.011953,-0.413234,0.012706,0.091826,inf
6,"(21024.0, 23728.0]",704,0.846591,0.008028,596.0,108.0,0.007651,0.011034,-0.366198,0.006209,0.047036,inf
7,"(23728.0, 26432.0]",1785,0.861064,0.020356,1537.0,248.0,0.019730,0.025337,-0.250148,0.014474,0.116050,inf
8,"(26432.0, 29136.0]",1355,0.853137,0.015452,1156.0,199.0,0.014839,0.020331,-0.314891,0.007928,0.064743,inf
9,"(29136.0, 31840.0]",2292,0.854276,0.026137,1958.0,334.0,0.025134,0.034123,-0.305769,0.001139,0.009122,inf
10,"(31840.0, 34544.0]",2130,0.855399,0.024290,1822.0,308.0,0.023388,0.031467,-0.296717,0.001123,0.009052,inf
11,"(34544.0, 37248.0]",3525,0.853050,0.040198,3007.0,518.0,0.038599,0.052922,-0.315584,0.002349,0.018867,inf
12,"(37248.0, 39952.0]",1926,0.880582,0.021963,1696.0,230.0,0.021771,0.023498,-0.076359,0.027532,0.239226,inf
13,"(39952.0, 42656.0]",4973,0.867484,0.056710,4314.0,659.0,0.055377,0.067327,-0.195410,0.013097,0.119051,inf
14,"(42656.0, 45360.0]",4038,0.875929,0.046048,3537.0,501.0,0.045403,0.051185,-0.119879,0.008444,0.075531,inf
15,"(45360.0, 48064.0]",3015,0.880597,0.034382,2655.0,360.0,0.034081,0.036780,-0.076211,0.004668,0.043668,inf
16,"(48064.0, 50768.0]",4397,0.878326,0.050142,3862.0,535.0,0.049574,0.054659,-0.097634,0.002271,0.021422,inf
17,"(50768.0, 53472.0]",2898,0.885783,0.033048,2567.0,331.0,0.032951,0.033817,-0.025933,0.007457,0.071701,inf
18,"(53472.0, 56176.0]",4143,0.873280,0.047245,3618.0,525.0,0.046442,0.053637,-0.144029,0.012503,0.118096,inf
19,"(56176.0, 58880.0]",1810,0.883425,0.020641,1599.0,211.0,0.020526,0.021557,-0.049032,0.010145,0.094997,inf
20,"(58880.0, 61584.0]",4726,0.881083,0.053894,4164.0,562.0,0.053451,0.057417,-0.071578,0.002342,0.022546,inf
21,"(61584.0, 64288.0]",2246,0.895815,0.025613,2012.0,234.0,0.025827,0.023907,0.077256,0.014731,0.148834,inf
22,"(64288.0, 66992.0]",3455,0.895803,0.039400,3095.0,360.0,0.039729,0.036780,0.077132,0.000012,0.000124,inf
23,"(66992.0, 69696.0]",1965,0.907379,0.022408,1783.0,182.0,0.022887,0.018594,0.207739,0.011576,0.130607,inf
24,"(69696.0, 72400.0]",4096,0.899902,0.046709,3686.0,410.0,0.047315,0.041888,0.121833,0.007477,0.085906,inf
25,"(72400.0, 75104.0]",3495,0.897854,0.039856,3138.0,357.0,0.040281,0.036473,0.099298,0.002048,0.022535,inf
26,"(75104.0, 77808.0]",967,0.915202,0.011027,885.0,82.0,0.011360,0.008378,0.304561,0.017348,0.205263,inf
27,"(77808.0, 80512.0]",3571,0.901988,0.040723,3221.0,350.0,0.041346,0.035758,0.145207,0.013213,0.159354,inf
28,"(80512.0, 83216.0]",1319,0.924185,0.015041,1219.0,100.0,0.015648,0.010217,0.426309,0.022197,0.281102,inf
29,"(83216.0, 85920.0]",2274,0.899736,0.025932,2046.0,228.0,0.026263,0.023294,0.119989,0.024449,0.306320,inf
30,"(85920.0, 88624.0]",1144,0.905594,0.013046,1036.0,108.0,0.013299,0.011034,0.186684,0.005858,0.066695,inf
31,"(88624.0, 91328.0]",2425,0.924536,0.027654,2242.0,183.0,0.028779,0.018696,0.431330,0.018942,0.244646,inf
32,"(91328.0, 94032.0]",1141,0.911481,0.013012,1040.0,101.0,0.013350,0.010319,0.257548,0.013055,0.173782,inf
33,"(94032.0, 96736.0]",1562,0.913572,0.017813,1427.0,135.0,0.018318,0.013792,0.283748,0.002091,0.026199,inf
34,"(96736.0, 99440.0]",916,0.918122,0.010446,841.0,75.0,0.010795,0.007662,0.342796,0.004550,0.059049,inf
35,"(99440.0, 102144.0]",2307,0.902904,0.026308,2083.0,224.0,0.026738,0.022885,0.155611,0.015218,0.187185,inf
36,"(102144.0, 104848.0]",552,0.898551,0.006295,496.0,56.0,0.006367,0.005721,0.106917,0.004353,0.048694,inf
37,"(104848.0, 107552.0]",1094,0.932358,0.012476,1020.0,74.0,0.013093,0.007560,0.549185,0.033808,0.442269,inf
38,"(107552.0, 110256.0]",1562,0.915493,0.017813,1430.0,132.0,0.018356,0.013486,0.308320,0.016865,0.240865,inf
39,"(110256.0, 112960.0]",295,0.908475,0.003364,268.0,27.0,0.003440,0.002758,0.220843,0.007018,0.087478,inf
40,"(112960.0, 115664.0]",790,0.911392,0.009009,720.0,70.0,0.009242,0.007152,0.256449,0.002918,0.035606,inf
41,"(115664.0, 118368.0]",358,0.935754,0.004083,335.0,23.0,0.004300,0.002350,0.604329,0.024362,0.347880,inf
42,"(118368.0, 121072.0]",1473,0.918534,0.016798,1353.0,120.0,0.017368,0.012260,0.348281,0.017221,0.256048,inf
43,"(121072.0, 123776.0]",204,0.936275,0.002326,191.0,13.0,0.002452,0.001328,0.613017,0.017741,0.264736,inf
44,"(123776.0, 126480.0]",870,0.928736,0.009921,808.0,62.0,0.010372,0.006334,0.493120,0.007539,0.119896,inf
45,"(126480.0, 129184.0]",239,0.933054,0.002725,223.0,16.0,0.002863,0.001635,0.560276,0.004319,0.067155,inf
46,"(129184.0, 131888.0]",734,0.927793,0.008370,681.0,53.0,0.008742,0.005415,0.478963,0.005261,0.081313,inf
47,"(131888.0, 134592.0]",207,0.932367,0.002361,193.0,14.0,0.002477,0.001430,0.549326,0.004574,0.070362,inf
48,"(134592.0, 137296.0]",449,0.915367,0.005120,411.0,38.0,0.005276,0.003882,0.306700,0.017000,0.242626,inf
49,"(137296.0, 140000.0]",627,0.909091,0.007150,570.0,57.0,0.007317,0.005823,0.228278,0.006277,0.078422,inf

In [160]:
plot_by_woe(df_temp, 90)
# We plot the weight of evidence values.

C:\Users\Sanket\Anaconda4\lib\site-packages\matplotlib\pyplot.py:523: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)

In [161]:
# WoE is monotonically decreasing with income, so we split income in 10 equal categories, each with width of 15k.
df_inputs_prepr['annual_inc:<20K'] = np.where((df_inputs_prepr['annual_inc'] <= 20000), 1, 0)
df_inputs_prepr['annual_inc:20K-30K'] = np.where((df_inputs_prepr['annual_inc'] > 20000) & (df_inputs_prepr['annual_inc'] <= 30000), 1, 0)
df_inputs_prepr['annual_inc:30K-40K'] = np.where((df_inputs_prepr['annual_inc'] > 30000) & (df_inputs_prepr['annual_inc'] <= 40000), 1, 0)
df_inputs_prepr['annual_inc:40K-50K'] = np.where((df_inputs_prepr['annual_inc'] > 40000) & (df_inputs_prepr['annual_inc'] <= 50000), 1, 0)
df_inputs_prepr['annual_inc:50K-60K'] = np.where((df_inputs_prepr['annual_inc'] > 50000) & (df_inputs_prepr['annual_inc'] <= 60000), 1, 0)
df_inputs_prepr['annual_inc:60K-70K'] = np.where((df_inputs_prepr['annual_inc'] > 60000) & (df_inputs_prepr['annual_inc'] <= 70000), 1, 0)
df_inputs_prepr['annual_inc:70K-80K'] = np.where((df_inputs_prepr['annual_inc'] > 70000) & (df_inputs_prepr['annual_inc'] <= 80000), 1, 0)
df_inputs_prepr['annual_inc:80K-90K'] = np.where((df_inputs_prepr['annual_inc'] > 80000) & (df_inputs_prepr['annual_inc'] <= 90000), 1, 0)
df_inputs_prepr['annual_inc:90K-100K'] = np.where((df_inputs_prepr['annual_inc'] > 90000) & (df_inputs_prepr['annual_inc'] <= 100000), 1, 0)
df_inputs_prepr['annual_inc:100K-120K'] = np.where((df_inputs_prepr['annual_inc'] > 100000) & (df_inputs_prepr['annual_inc'] <= 120000), 1, 0)
df_inputs_prepr['annual_inc:120K-140K'] = np.where((df_inputs_prepr['annual_inc'] > 120000) & (df_inputs_prepr['annual_inc'] <= 140000), 1, 0)
df_inputs_prepr['annual_inc:>140K'] = np.where((df_inputs_prepr['annual_inc'] > 140000), 1, 0)

In [162]:
# mths_since_last_delinq
# We have to create one category for missing values and do fine and coarse classing for the rest.
df_inputs_prepr_temp = df_inputs_prepr[pd.notnull(df_inputs_prepr['mths_since_last_delinq'])]
df_inputs_prepr_temp['mths_since_last_delinq_factor'] = pd.cut(df_inputs_prepr_temp['mths_since_last_delinq'], 50)
df_temp = woe_ordered_continuous(df_inputs_prepr_temp, 'mths_since_last_delinq_factor', df_targets_prepr[df_inputs_prepr_temp.index])
# We calculate weight of evidence.
df_temp

C:\Users\Sanket\Anaconda4\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Sanket\Anaconda4\lib\site-packages\pandas\core\algorithms.py:1926: RuntimeWarning: invalid value encountered in subtract
  out_arr[res_indexer] = arr[res_indexer] - arr[lag_indexer]

,mths_since_last_delinq_factor,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,"(-0.17, 3.4]",1348,0.868694,0.031283,1171.0,177.0,0.030501,0.037668,-0.211036,NaN,NaN,inf
1,"(3.4, 6.8]",1890,0.880423,0.043861,1664.0,226.0,0.043342,0.048095,-0.104055,0.011729,0.106981,inf
2,"(6.8, 10.2]",3373,0.887044,0.078276,2992.0,381.0,0.077933,0.081081,-0.039601,0.006621,0.064453,inf
3,"(10.2, 13.6]",2496,0.895833,0.057924,2236.0,260.0,0.058241,0.055331,0.051263,0.008789,0.090864,inf
4,"(13.6, 17.0]",3165,0.884044,0.073449,2798.0,367.0,0.072880,0.078102,-0.069201,0.011789,0.120464,inf
5,"(17.0, 20.4]",2282,0.893076,0.052958,2038.0,244.0,0.053084,0.051926,0.022057,0.009032,0.091258,inf
6,"(20.4, 23.8]",2115,0.898345,0.049082,1900.0,215.0,0.049489,0.045754,0.078472,0.005269,0.056415,inf
7,"(23.8, 27.2]",2755,0.895463,0.063934,2467.0,288.0,0.064258,0.061290,0.047298,0.002882,0.031174,inf
8,"(27.2, 30.6]",1929,0.896319,0.044766,1729.0,200.0,0.045035,0.042562,0.056482,0.000857,0.009183,inf
9,"(30.6, 34.0]",2453,0.891969,0.056926,2188.0,265.0,0.056991,0.056395,0.010514,0.004350,0.045968,inf
10,"(34.0, 37.4]",1786,0.904255,0.041447,1615.0,171.0,0.042066,0.036391,0.144927,0.012286,0.134413,inf
11,"(37.4, 40.8]",1765,0.887819,0.040960,1567.0,198.0,0.040816,0.042137,-0.031848,0.016437,0.176775,inf
12,"(40.8, 44.2]",2270,0.876211,0.052679,1989.0,281.0,0.051808,0.059800,-0.143467,0.011607,0.111619,inf
13,"(44.2, 47.6]",1664,0.899038,0.038616,1496.0,168.0,0.038966,0.035752,0.086087,0.022827,0.229554,inf
14,"(47.6, 51.0]",1739,0.888442,0.040356,1545.0,194.0,0.040243,0.041285,-0.025578,0.010597,0.111665,inf
15,"(51.0, 54.4]",1158,0.887737,0.026873,1028.0,130.0,0.026776,0.027665,-0.032663,0.000704,0.007085,inf
16,"(54.4, 57.8]",1130,0.911504,0.026224,1030.0,100.0,0.026829,0.021281,0.231645,0.023767,0.264308,inf
17,"(57.8, 61.2]",1423,0.895994,0.033023,1275.0,148.0,0.033210,0.031496,0.052990,0.015510,0.178655,inf
18,"(61.2, 64.6]",1015,0.887685,0.023555,901.0,114.0,0.023468,0.024260,-0.033193,0.008310,0.086182,inf
19,"(64.6, 68.0]",1342,0.891952,0.031143,1197.0,145.0,0.031178,0.030858,0.010341,0.004268,0.043533,inf
20,"(68.0, 71.4]",930,0.884946,0.021582,823.0,107.0,0.021437,0.022771,-0.060372,0.007006,0.070713,inf
21,"(71.4, 74.8]",928,0.889009,0.021536,825.0,103.0,0.021489,0.021920,-0.019845,0.004062,0.040527,inf
22,"(74.8, 78.2]",1195,0.907950,0.027732,1085.0,110.0,0.028261,0.023409,0.188356,0.018941,0.208201,inf
23,"(78.2, 81.6]",768,0.880208,0.017823,676.0,92.0,0.017608,0.019579,-0.106095,0.027741,0.294450,inf
24,"(81.6, 85.0]",136,0.897059,0.003156,122.0,14.0,0.003178,0.002979,0.064464,0.016850,0.170559,inf
25,"(85.0, 88.4]",10,1.000000,0.000232,10.0,0.0,0.000260,0.000000,inf,0.102941,inf,inf
26,"(88.4, 91.8]",1,1.000000,0.000023,1.0,0.0,0.000026,0.000000,inf,0.000000,NaN,inf
27,"(91.8, 95.2]",2,1.000000,0.000046,2.0,0.0,0.000052,0.000000,inf,0.000000,NaN,inf
28,"(95.2, 98.6]",3,0.666667,0.000070,2.0,1.0,0.000052,0.000213,-1.407352,0.333333,inf,inf
29,"(98.6, 102.0]",4,1.000000,0.000093,4.0,0.0,0.000104,0.000000,inf,0.333333,inf,inf
30,"(102.0, 105.4]",2,1.000000,0.000046,2.0,0.0,0.000052,0.000000,inf,0.000000,NaN,inf
31,"(105.4, 108.8]",3,1.000000,0.000070,3.0,0.0,0.000078,0.000000,inf,0.000000,NaN,inf
32,"(108.8, 112.2]",1,1.000000,0.000023,1.0,0.0,0.000026,0.000000,inf,0.000000,NaN,inf
33,"(112.2, 115.6]",1,1.000000,0.000023,1.0,0.0,0.000026,0.000000,inf,0.000000,NaN,inf
34,"(115.6, 119.0]",2,1.000000,0.000046,2.0,0.0,0.000052,0.000000,inf,0.000000,NaN,inf
35,"(119.0, 122.4]",2,1.000000,0.000046,2.0,0.0,0.000052,0.000000,inf,0.000000,NaN,inf
36,"(122.4, 125.8]",1,1.000000,0.000023,1.0,0.0,0.000026,0.000000,inf,0.000000,NaN,inf
37,"(125.8, 129.2]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
38,"(129.2, 132.6]",1,1.000000,0.000023,1.0,0.0,0.000026,0.000000,inf,NaN,NaN,inf
39,"(132.6, 136.0]",1,1.000000,0.000023,1.0,0.0,0.000026,0.000000,inf,0.000000,NaN,inf
40,"(136.0, 139.4]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
41,"(139.4, 142.8]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
42,"(142.8, 146.2]",1,1.000000,0.000023,1.0,0.0,0.000026,0.000000,inf,NaN,NaN,inf
43,"(146.2, 149.6]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
44,"(149.6, 153.0]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
45,"(153.0, 156.4]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
46,"(156.4, 159.8]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
47,"(159.8, 163.2]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
48,"(163.2, 166.6]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
49,"(166.6, 170.0]",1,1.000000,0.000023,1.0,0.0,0.000026,0.000000,inf,NaN,NaN,inf

In [163]:
plot_by_woe(df_temp, 90)
# We plot the weight of evidence values.

C:\Users\Sanket\Anaconda4\lib\site-packages\matplotlib\pyplot.py:523: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)

In [164]:
# Categories: Missing, 0-3, 4-30, 31-56, >=57
df_inputs_prepr['mths_since_last_delinq:Missing'] = np.where((df_inputs_prepr['mths_since_last_delinq'].isnull()), 1, 0)
df_inputs_prepr['mths_since_last_delinq:0-3'] = np.where((df_inputs_prepr['mths_since_last_delinq'] >= 0) & (df_inputs_prepr['mths_since_last_delinq'] <= 3), 1, 0)
df_inputs_prepr['mths_since_last_delinq:4-30'] = np.where((df_inputs_prepr['mths_since_last_delinq'] >= 4) & (df_inputs_prepr['mths_since_last_delinq'] <= 30), 1, 0)
df_inputs_prepr['mths_since_last_delinq:31-56'] = np.where((df_inputs_prepr['mths_since_last_delinq'] >= 31) & (df_inputs_prepr['mths_since_last_delinq'] <= 56), 1, 0)
df_inputs_prepr['mths_since_last_delinq:>=57'] = np.where((df_inputs_prepr['mths_since_last_delinq'] >= 57), 1, 0)

### Preprocessing Continuous Variables: Creating Dummy Variables, Part 3: Homework

In [165]:
# dti
df_inputs_prepr['dti_factor'] = pd.cut(df_inputs_prepr['dti'], 100)
# Here we do fine-classing: using the 'cut' method, we split the variable into 100 categories by its values.
df_temp = woe_ordered_continuous(df_inputs_prepr, 'dti_factor', df_targets_prepr)
# We calculate weight of evidence.
df_temp

,dti_factor,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,"(-0.04, 0.4]",187,0.893048,0.002005,167.0,20.0,0.002010,0.001963,0.024021,NaN,NaN,0.038146
1,"(0.4, 0.8]",184,0.880435,0.001973,162.0,22.0,0.001950,0.002159,-0.101687,0.012613,0.125708,0.038146
2,"(0.8, 1.2]",223,0.892377,0.002391,199.0,24.0,0.002396,0.002355,0.017010,0.011942,0.118697,0.038146
3,"(1.2, 1.6]",255,0.905882,0.002734,231.0,24.0,0.002781,0.002355,0.166123,0.013506,0.149113,0.038146
4,"(1.6, 2.0]",315,0.892063,0.003378,281.0,34.0,0.003383,0.003337,0.013753,0.013819,0.152370,0.038146
5,"(2.0, 2.399]",324,0.913580,0.003474,296.0,28.0,0.003563,0.002748,0.259914,0.021517,0.246161,0.038146
6,"(2.399, 2.799]",366,0.918033,0.003925,336.0,30.0,0.004045,0.002944,0.317673,0.004453,0.057759,0.038146
7,"(2.799, 3.199]",442,0.907240,0.004740,401.0,41.0,0.004827,0.004024,0.182149,0.010793,0.135524,0.038146
8,"(3.199, 3.599]",484,0.933884,0.005190,452.0,32.0,0.005441,0.003140,0.549706,0.026644,0.367557,0.038146
9,"(3.599, 3.999]",563,0.902309,0.006037,508.0,55.0,0.006116,0.005397,0.124908,0.031575,0.424798,0.038146
10,"(3.999, 4.399]",599,0.919866,0.006423,551.0,48.0,0.006633,0.004711,0.342293,0.017557,0.217386,0.038146
11,"(4.399, 4.799]",661,0.906203,0.007088,599.0,62.0,0.007211,0.006084,0.169887,0.013664,0.172407,0.038146
12,"(4.799, 5.199]",706,0.907932,0.007570,641.0,65.0,0.007717,0.006379,0.190402,0.001729,0.020515,0.038146
13,"(5.199, 5.599]",821,0.917174,0.008804,753.0,68.0,0.009065,0.006673,0.306317,0.009242,0.115915,0.038146
14,"(5.599, 5.999]",841,0.897741,0.009018,755.0,86.0,0.009089,0.008440,0.074130,0.019433,0.232187,0.038146
15,"(5.999, 6.398]",889,0.912261,0.009533,811.0,78.0,0.009763,0.007655,0.243319,0.014520,0.169189,0.038146
16,"(6.398, 6.798]",978,0.936605,0.010487,916.0,62.0,0.011027,0.006084,0.594641,0.024344,0.351323,0.038146
17,"(6.798, 7.198]",1021,0.904016,0.010948,923.0,98.0,0.011112,0.009617,0.144421,0.032590,0.450220,0.038146
18,"(7.198, 7.598]",1057,0.905393,0.011334,957.0,100.0,0.011521,0.009814,0.160393,0.001377,0.015971,0.038146
19,"(7.598, 7.998]",1170,0.911966,0.012546,1067.0,103.0,0.012845,0.010108,0.239637,0.006573,0.079244,0.038146
20,"(7.998, 8.398]",1172,0.907850,0.012567,1064.0,108.0,0.012809,0.010599,0.189419,0.004116,0.050218,0.038146
21,"(8.398, 8.798]",1127,0.911269,0.012085,1027.0,100.0,0.012364,0.009814,0.230986,0.003419,0.041568,0.038146
22,"(8.798, 9.198]",1281,0.913349,0.013736,1170.0,111.0,0.014085,0.010893,0.256988,0.002080,0.026002,0.038146
23,"(9.198, 9.598]",1309,0.901451,0.014036,1180.0,129.0,0.014205,0.012659,0.115217,0.011897,0.141772,0.038146
24,"(9.598, 9.998]",1371,0.912473,0.014701,1251.0,120.0,0.015060,0.011776,0.245966,0.011021,0.130749,0.038146
25,"(9.998, 10.397]",1429,0.911826,0.015323,1303.0,126.0,0.015686,0.012365,0.237902,0.000646,0.008064,0.038146
26,"(10.397, 10.797]",1521,0.906640,0.016310,1379.0,142.0,0.016601,0.013935,0.175046,0.005186,0.062856,0.038146
27,"(10.797, 11.197]",1555,0.908682,0.016674,1413.0,142.0,0.017010,0.013935,0.199403,0.002041,0.024357,0.038146
28,"(11.197, 11.597]",1597,0.898560,0.017125,1435.0,162.0,0.017275,0.015898,0.083083,0.010122,0.116320,0.038146
29,"(11.597, 11.997]",1554,0.907979,0.016664,1411.0,143.0,0.016986,0.014033,0.190969,0.009420,0.107886,0.038146
30,"(11.997, 12.397]",1607,0.896702,0.017232,1441.0,166.0,0.017347,0.016290,0.062864,0.011277,0.128105,0.038146
31,"(12.397, 12.797]",1719,0.905759,0.018433,1557.0,162.0,0.018744,0.015898,0.164679,0.009057,0.101815,0.038146
32,"(12.797, 13.197]",1614,0.915118,0.017307,1477.0,137.0,0.017781,0.013445,0.279547,0.009359,0.114868,0.038146
33,"(13.197, 13.597]",1717,0.905067,0.018411,1554.0,163.0,0.018708,0.015996,0.156597,0.010051,0.122950,0.038146
34,"(13.597, 13.997]",1707,0.892209,0.018304,1523.0,184.0,0.018335,0.018057,0.015261,0.012858,0.141336,0.038146
35,"(13.997, 14.396]",1724,0.901972,0.018487,1555.0,169.0,0.018720,0.016585,0.121091,0.009764,0.105831,0.038146
36,"(14.396, 14.796]",1773,0.894529,0.019012,1586.0,187.0,0.019093,0.018351,0.039621,0.007443,0.081470,0.038146
37,"(14.796, 15.196]",1755,0.898006,0.018819,1576.0,179.0,0.018973,0.017566,0.077019,0.003477,0.037398,0.038146
38,"(15.196, 15.596]",1695,0.896755,0.018176,1520.0,175.0,0.018298,0.017174,0.063439,0.001251,0.013580,0.038146
39,"(15.596, 15.996]",1752,0.901826,0.018787,1580.0,172.0,0.019021,0.016879,0.119445,0.005071,0.056006,0.038146
40,"(15.996, 16.396]",1653,0.901391,0.017725,1490.0,163.0,0.017937,0.015996,0.114541,0.000435,0.004904,0.038146
41,"(16.396, 16.796]",1689,0.893428,0.018111,1509.0,180.0,0.018166,0.017664,0.028005,0.007963,0.086536,0.038146
42,"(16.796, 17.196]",1770,0.897740,0.018980,1589.0,181.0,0.019129,0.017763,0.074122,0.004312,0.046118,0.038146
43,"(17.196, 17.596]",1708,0.882904,0.018315,1508.0,200.0,0.018154,0.019627,-0.078018,0.014836,0.152141,0.038146
44,"(17.596, 17.996]",1680,0.899405,0.018015,1511.0,169.0,0.018190,0.016585,0.092388,0.016501,0.170406,0.038146
45,"(17.996, 18.395]",1671,0.900060,0.017918,1504.0,167.0,0.018106,0.016389,0.099649,0.000655,0.007261,0.038146
46,"(18.395, 18.795]",1638,0.901709,0.017564,1477.0,161.0,0.017781,0.015800,0.118123,0.001650,0.018474,0.038146
47,"(18.795, 19.195]",1628,0.880835,0.017457,1434.0,194.0,0.017263,0.019038,-0.097876,0.020874,0.215999,0.038146
48,"(19.195, 19.595]",1606,0.887298,0.017221,1425.0,181.0,0.017155,0.017763,-0.034811,0.006462,0.063065,0.038146
49,"(19.595, 19.995]",1603,0.882720,0.017189,1415.0,188.0,0.017034,0.018449,-0.079798,0.004578,0.044987,0.038146
50,"(19.995, 20.395]",1512,0.887566,0.016213,1342.0,170.0,0.016156,0.016683,-0.032123,0.004846,0.047675,0.038146
51,"(20.395, 20.795]",1656,0.880435,0.017757,1458.0,198.0,0.017552,0.019431,-0.101687,0.007131,0.069564,0.038146
52,"(20.795, 21.195]",1505,0.884385,0.016138,1331.0,174.0,0.016023,0.017076,-0.063610,0.003951,0.038077,0.038146
53,"(21.195, 21.595]",1455,0.879038,0.015602,1279.0,176.0,0.015397,0.017272,-0.114891,0.005348,0.051281,0.038146
54,"(21.595, 21.995]",1452,0.882920,0.015570,1282.0,170.0,0.015433,0.016683,-0.077862,0.003882,0.037028,0.038146
55,"(21.995, 22.394]",1394,0.868006,0.014948,1210.0,184.0,0.014567,0.018057,-0.214801,0.014914,0.136938,0.038146
56,"(22.394, 22.794]",1309,0.858671,0.014036,1124.0,185.0,0.013531,0.018155,-0.293947,0.009335,0.079147,0.038146
57,"(22.794, 23.194]",1328,0.875000,0.014240,1162.0,166.0,0.013989,0.016290,-0.152331,0.016329,0.141617,0.038146
58,"(23.194, 23.594]",1335,0.878652,0.014315,1173.0,162.0,0.014121,0.015898,-0.118517,0.003652,0.033813,0.038146
59,"(23.594, 23.994]",1230,0.863415,0.013189,1062.0,168.0,0.012785,0.016487,-0.254295,0.015237,0.135778,0.038146
60,"(23.994, 24.394]",1209,0.878412,0.012964,1062.0,147.0,0.012785,0.014426,-0.120764,0.014997,0.133531,0.038146
61,"(24.394, 24.794]",1120,0.867857,0.012010,972.0,148.0,0.011701,0.014524,-0.216097,0.010555,0.095333,0.038146
62,"(24.794, 25.194]",1116,0.866487,0.011967,967.0,149.0,0.011641,0.014622,-0.227988,0.001370,0.011891,0.038146
63,"(25.194, 25.594]",990,0.863636,0.010616,855.0,135.0,0.010293,0.013248,-0.252414,0.002851,0.024425,0.038146
64,"(25.594, 25.994]",978,0.870143,0.010487,851.0,127.0,0.010245,0.012463,-0.196016,0.006507,0.056398,0.038146
65,"(25.994, 26.393]",979,0.853933,0.010498,836.0,143.0,0.010064,0.014033,-0.332457,0.016211,0.136441,0.038146
66,"(26.393, 26.793]",919,0.862894,0.009854,793.0,126.0,0.009547,0.012365,-0.258699,0.008962,0.073757,0.038146
67,"(26.793, 27.193]",866,0.870670,0.009286,754.0,112.0,0.009077,0.010991,-0.191347,0.007775,0.067352,0.038146
68,"(27.193, 27.593]",873,0.859107,0.009361,750.0,123.0,0.009029,0.012071,-0.290352,0.011563,0.099005,0.038146
69,"(27.593, 27.993]",880,0.882955,0.009436,777.0,103.0,0.009354,0.010108,-0.077529,0.023848,0.212823,0.038146
70,"(27.993, 28.393]",845,0.855621,0.009061,723.0,122.0,0.008704,0.011973,-0.318852,0.027333,0.241323,0.038146
71,"(28.393, 28.793]",730,0.869863,0.007828,635.0,95.0,0.007644,0.009323,-0.198493,0.014242,0.120360,0.038146
72,"(28.793, 29.193]",781,0.879641,0.008375,687.0,94.0,0.008270,0.009225,-0.109201,0.009778,0.089291,0.038146
73,"(29.193, 29.593]",711,0.852321,0.007624,606.0,105.0,0.007295,0.010304,-0.345321,0.027321,0.236120,0.038146
74,"(29.593, 29.993]",694,0.853026,0.007442,592.0,102.0,0.007127,0.010010,-0.339707,0.000705,0.005614,0.038146
75,"(29.993, 30.392]",509,0.864440,0.005458,440.0,69.0,0.005297,0.006771,-0.245572,0.011414,0.094134,0.038146
76,"(30.392, 30.792]",471,0.859873,0.005051,405.0,66.0,0.004876,0.006477,-0.284008,0.004567,0.038436,0.038146
77,"(30.792, 31.192]",460,0.865217,0.004933,398.0,62.0,0.004791,0.006084,-0.238923,0.005345,0.045085,0.038146
78,"(31.192, 31.592]",434,0.843318,0.004654,366.0,68.0,0.004406,0.006673,-0.415115,0.021899,0.176192,0.038146
79,"(31.592, 31.992]",440,0.881818,0.004718,388.0,52.0,0.004671,0.005103,-0.088479,0.038500,0.326636,0.038146
80,"(31.992, 32.392]",409,0.875306,0.004386,358.0,51.0,0.004310,0.005005,-0.149533,0.006513,0.061054,0.038146
81,"(32.392, 32.792]",388,0.835052,0.004161,324.0,64.0,0.003900,0.006281,-0.476380,0.040254,0.326847,0.038146
82,"(32.792, 33.192]",374,0.855615,0.004010,320.0,54.0,0.003852,0.005299,-0.318904,0.020563,0.157477,0.038146
83,"(33.192, 33.592]",344,0.869186,0.003689,299.0,45.0,0.003600,0.004416,-0.204460,0.013571,0.114444,0.038146
84,"(33.592, 33.992]",390,0.853846,0.004182,333.0,57.0,0.004009,0.005594,-0.333149,0.015340,0.128690,0.038146
85,"(33.992, 34.391]",314,0.866242,0.003367,272.0,42.0,0.003274,0.004122,-0.230108,0.012396,0.103041,0.038146
86,"(34.391, 34.791]",309,0.870550,0.003313,269.0,40.0,0.003238,0.003925,-0.192409,0.004308,0.037699,0.038146
87,"(34.791, 35.191]",162,0.876543,0.001737,142.0,20.0,0.001709,0.001963,-0.138146,0.005993,0.054263,0.038146
88,"(35.191, 35.591]",72,0.944444,0.000772,68.0,4.0,0.000819,0.000393,0.734973,0.067901,0.873119,0.038146
89,"(35.591, 35.991]",76,0.881579,0.000815,67.0,9.0,0.000807,0.000883,-0.090773,0.062865,0.825745,0.038146
90,"(35.991, 36.391]",69,0.884058,0.000740,61.0,8.0,0.000734,0.000785,-0.066808,0.002479,0.023964,0.038146
91,"(36.391, 36.791]",66,0.848485,0.000708,56.0,10.0,0.000674,0.000981,-0.375474,0.035573,0.308666,0.038146
92,"(36.791, 37.191]",60,0.916667,0.000643,55.0,5.0,0.000662,0.000491,0.299655,0.068182,0.675129,0.038146
93,"(37.191, 37.591]",50,0.960000,0.000536,48.0,2.0,0.000578,0.000196,1.079813,0.043333,0.780159,0.038146
94,"(37.591, 37.991]",45,0.844444,0.000483,38.0,7.0,0.000457,0.000687,-0.406565,0.115556,1.486378,0.038146
95,"(37.991, 38.39]",54,0.888889,0.000579,48.0,6.0,0.000578,0.000589,-0.018799,0.044444,0.387766,0.038146
96,"(38.39, 38.79]",37,0.837838,0.000397,31.0,6.0,0.000373,0.000589,-0.456013,0.051051,0.437214,0.038146
97,"(38.79, 39.19]",45,0.844444,0.000483,38.0,7.0,0.000457,0.000687,-0.406565,0.006607,0.049448,0.038146
98,"(39.19, 39.59]",44,0.931818,0.000472,41.0,3.0,0.000494,0.000294,0.516719,0.087374,0.923284,0.038146
99,"(39.59, 39.99]",57,0.859649,0.000611,49.0,8.0,0.000590,0.000785,-0.285862,0.072169,0.802581,0.038146

In [166]:
plot_by_woe(df_temp, 90)
# We plot the weight of evidence values.

C:\Users\Sanket\Anaconda4\lib\site-packages\matplotlib\pyplot.py:523: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)

In [167]:
# Similarly to income, initial examination shows that most values are lower than 200.
# Hence, we are going to have one category for more than 35, and we are going to apply our approach to determine
# the categories of everyone with 150k or less.
df_inputs_prepr_temp = df_inputs_prepr.loc[df_inputs_prepr['dti'] <= 35, : ]

In [168]:
df_inputs_prepr_temp['dti_factor'] = pd.cut(df_inputs_prepr_temp['dti'], 50)
# Here we do fine-classing: using the 'cut' method, we split the variable into 50 categories by its values.
df_temp = woe_ordered_continuous(df_inputs_prepr_temp, 'dti_factor', df_targets_prepr[df_inputs_prepr_temp.index])
# We calculate weight of evidence.
df_temp

C:\Users\Sanket\Anaconda4\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,dti_factor,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,"(-0.035, 0.7]",328,0.884146,0.003544,290.0,38.0,0.003518,0.003758,-0.066005,NaN,NaN,0.033919
1,"(0.7, 1.4]",393,0.903308,0.004246,355.0,38.0,0.004306,0.003758,0.136232,0.019162,0.202237,0.033919
2,"(1.4, 2.1]",536,0.895522,0.005792,480.0,56.0,0.005823,0.005538,0.050135,0.007785,0.086097,0.033919
3,"(2.1, 2.8]",607,0.915980,0.006559,556.0,51.0,0.006745,0.005044,0.290643,0.020458,0.240508,0.033919
4,"(2.8, 3.5]",811,0.924784,0.008763,750.0,61.0,0.009098,0.006032,0.410900,0.008804,0.120257,0.033919
5,"(3.5, 4.2]",970,0.903093,0.010481,876.0,94.0,0.010626,0.009296,0.133772,0.021691,0.277128,0.033919
6,"(4.2, 4.9]",1140,0.913158,0.012318,1041.0,99.0,0.012628,0.009790,0.254518,0.010065,0.120746,0.033919
7,"(4.9, 5.6]",1370,0.911679,0.014803,1249.0,121.0,0.015151,0.011966,0.236009,0.001479,0.018509,0.033919
8,"(5.6, 6.3]",1491,0.904762,0.016111,1349.0,142.0,0.016364,0.014043,0.152992,0.006917,0.083016,0.033919
9,"(6.3, 7.0]",1722,0.926829,0.018607,1596.0,126.0,0.019360,0.012460,0.440674,0.022067,0.287682,0.033919
10,"(7.0, 7.7]",1846,0.904117,0.019946,1669.0,177.0,0.020246,0.017504,0.145531,0.022712,0.295144,0.033919
11,"(7.7, 8.4]",2044,0.909491,0.022086,1859.0,185.0,0.022551,0.018295,0.209139,0.005374,0.063608,0.033919
12,"(8.4, 9.1]",2097,0.910348,0.022659,1909.0,188.0,0.023157,0.018592,0.219593,0.000857,0.010455,0.033919
13,"(9.1, 9.8]",2319,0.908150,0.025057,2106.0,213.0,0.025547,0.021064,0.192954,0.002198,0.026639,0.033919
14,"(9.8, 10.5]",2519,0.909885,0.027218,2292.0,227.0,0.027803,0.022449,0.213931,0.001735,0.020977,0.033919
15,"(10.5, 11.2]",2694,0.908315,0.029109,2447.0,247.0,0.029684,0.024426,0.194930,0.001570,0.019000,0.033919
16,"(11.2, 11.9]",2748,0.901747,0.029693,2478.0,270.0,0.030060,0.026701,0.118486,0.006568,0.076445,0.033919
17,"(11.9, 12.6]",2844,0.903657,0.030730,2570.0,274.0,0.031176,0.027097,0.140234,0.001910,0.021748,0.033919
18,"(12.6, 13.3]",2886,0.908870,0.031184,2623.0,263.0,0.031819,0.026009,0.201621,0.005214,0.061387,0.033919
19,"(13.3, 14.0]",3056,0.898233,0.033021,2745.0,311.0,0.033299,0.030756,0.079444,0.010637,0.122177,0.033919
20,"(14.0, 14.7]",3068,0.898305,0.033150,2756.0,312.0,0.033432,0.030854,0.080233,0.000072,0.000789,0.033919
21,"(14.7, 15.4]",2954,0.898104,0.031919,2653.0,301.0,0.032183,0.029767,0.078037,0.000201,0.002196,0.033919
22,"(15.4, 16.1]",3050,0.900656,0.032956,2747.0,303.0,0.033323,0.029964,0.106232,0.002551,0.028196,0.033919
23,"(16.1, 16.8]",2914,0.896019,0.031486,2611.0,303.0,0.031673,0.029964,0.055456,0.004637,0.050776,0.033919
24,"(16.8, 17.5]",3078,0.886940,0.033258,2730.0,348.0,0.033117,0.034415,-0.038445,0.009080,0.093901,0.033919
25,"(17.5, 18.2]",2964,0.903171,0.032027,2677.0,287.0,0.032474,0.028382,0.134670,0.016232,0.173115,0.033919
26,"(18.2, 18.9]",2863,0.894167,0.030935,2560.0,303.0,0.031054,0.029964,0.035730,0.009004,0.098940,0.033919
27,"(18.9, 19.6]",2796,0.887339,0.030211,2481.0,315.0,0.030096,0.031151,-0.034455,0.006828,0.070185,0.033919
28,"(19.6, 20.3]",2772,0.887807,0.029952,2461.0,311.0,0.029853,0.030756,-0.029769,0.000468,0.004686,0.033919
29,"(20.3, 21.0]",2830,0.879505,0.030579,2489.0,341.0,0.030193,0.033722,-0.110546,0.008301,0.080776,0.033919
30,"(21.0, 21.7]",2517,0.883989,0.027197,2225.0,292.0,0.026991,0.028877,-0.067541,0.004484,0.043005,0.033919
31,"(21.7, 22.4]",2495,0.870541,0.026959,2172.0,323.0,0.026348,0.031942,-0.192548,0.013448,0.125007,0.033919
32,"(22.4, 23.1]",2261,0.865989,0.024431,1958.0,303.0,0.023752,0.029964,-0.232353,0.004553,0.039805,0.033919
33,"(23.1, 23.8]",2327,0.876235,0.025144,2039.0,288.0,0.024734,0.028481,-0.141045,0.010247,0.091308,0.033919
34,"(23.8, 24.5]",2127,0.870710,0.022983,1852.0,275.0,0.022466,0.027195,-0.191049,0.005526,0.050004,0.033919
35,"(24.5, 25.2]",1929,0.867807,0.020843,1674.0,255.0,0.020307,0.025218,-0.216592,0.002903,0.025543,0.033919
36,"(25.2, 25.9]",1707,0.865847,0.018444,1478.0,229.0,0.017929,0.022646,-0.233576,0.001961,0.016985,0.033919
37,"(25.9, 26.6]",1657,0.858177,0.017904,1422.0,235.0,0.017250,0.023240,-0.298065,0.007669,0.064489,0.033919
38,"(26.6, 27.3]",1553,0.867354,0.016780,1347.0,206.0,0.016340,0.020372,-0.220540,0.009176,0.077525,0.033919
39,"(27.3, 28.0]",1559,0.873637,0.016845,1362.0,197.0,0.016522,0.019482,-0.164794,0.006283,0.055747,0.033919
40,"(28.0, 28.7]",1390,0.861871,0.015019,1198.0,192.0,0.014532,0.018987,-0.267386,0.011766,0.102592,0.033919
41,"(28.7, 29.4]",1341,0.869500,0.014490,1166.0,175.0,0.014144,0.017306,-0.201751,0.007630,0.065635,0.033919
42,"(29.4, 30.1]",1147,0.851787,0.012394,977.0,170.0,0.011852,0.016812,-0.349611,0.017713,0.147860,0.033919
43,"(30.1, 30.8]",838,0.862768,0.009055,723.0,115.0,0.008770,0.011373,-0.259822,0.010981,0.089789,0.033919
44,"(30.8, 31.5]",798,0.859649,0.008623,686.0,112.0,0.008322,0.011076,-0.285921,0.003119,0.026098,0.033919
45,"(31.5, 32.2]",734,0.877384,0.007931,644.0,90.0,0.007812,0.008900,-0.130410,0.017735,0.155510,0.033919
46,"(32.2, 32.9]",696,0.849138,0.007520,591.0,105.0,0.007169,0.010384,-0.370444,0.028246,0.240033,0.033919
47,"(32.9, 33.6]",621,0.856683,0.006710,532.0,89.0,0.006453,0.008801,-0.310292,0.007545,0.060151,0.033919
48,"(33.6, 34.3]",634,0.859621,0.006850,545.0,89.0,0.006611,0.008801,-0.286150,0.002939,0.024142,0.033919
49,"(34.3, 35.0]",507,0.867850,0.005478,440.0,67.0,0.005337,0.006626,-0.216217,0.008229,0.069933,0.033919

In [169]:
plot_by_woe(df_temp, 90)
# We plot the weight of evidence values.

C:\Users\Sanket\Anaconda4\lib\site-packages\matplotlib\pyplot.py:523: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)

In [170]:
# Categories:
df_inputs_prepr['dti:<=1.4'] = np.where((df_inputs_prepr['dti'] <= 1.4), 1, 0)
df_inputs_prepr['dti:1.4-3.5'] = np.where((df_inputs_prepr['dti'] > 1.4) & (df_inputs_prepr['dti'] <= 3.5), 1, 0)
df_inputs_prepr['dti:3.5-7.7'] = np.where((df_inputs_prepr['dti'] > 3.5) & (df_inputs_prepr['dti'] <= 7.7), 1, 0)
df_inputs_prepr['dti:7.7-10.5'] = np.where((df_inputs_prepr['dti'] > 7.7) & (df_inputs_prepr['dti'] <= 10.5), 1, 0)
df_inputs_prepr['dti:10.5-16.1'] = np.where((df_inputs_prepr['dti'] > 10.5) & (df_inputs_prepr['dti'] <= 16.1), 1, 0)
df_inputs_prepr['dti:16.1-20.3'] = np.where((df_inputs_prepr['dti'] > 16.1) & (df_inputs_prepr['dti'] <= 20.3), 1, 0)
df_inputs_prepr['dti:20.3-21.7'] = np.where((df_inputs_prepr['dti'] > 20.3) & (df_inputs_prepr['dti'] <= 21.7), 1, 0)
df_inputs_prepr['dti:21.7-22.4'] = np.where((df_inputs_prepr['dti'] > 21.7) & (df_inputs_prepr['dti'] <= 22.4), 1, 0)
df_inputs_prepr['dti:22.4-35'] = np.where((df_inputs_prepr['dti'] > 22.4) & (df_inputs_prepr['dti'] <= 35), 1, 0)
df_inputs_prepr['dti:>35'] = np.where((df_inputs_prepr['dti'] > 35), 1, 0)

In [171]:
# mths_since_last_record
# We have to create one category for missing values and do fine and coarse classing for the rest.
df_inputs_prepr_temp = df_inputs_prepr[pd.notnull(df_inputs_prepr['mths_since_last_record'])]
#sum(loan_data_temp['mths_since_last_record'].isnull())
df_inputs_prepr_temp['mths_since_last_record_factor'] = pd.cut(df_inputs_prepr_temp['mths_since_last_record'], 50)
# Here we do fine-classing: using the 'cut' method, we split the variable into 50 categories by its values.
df_temp = woe_ordered_continuous(df_inputs_prepr_temp, 'mths_since_last_record_factor', df_targets_prepr[df_inputs_prepr_temp.index])
# We calculate weight of evidence.
df_temp

C:\Users\Sanket\Anaconda4\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Sanket\Anaconda4\lib\site-packages\pandas\core\series.py:679: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

,mths_since_last_record_factor,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,"(-0.129, 2.58]",244,0.741803,0.019410,181.0,63.0,0.016036,0.049065,-1.118309,NaN,NaN,inf
1,"(2.58, 5.16]",36,0.888889,0.002864,32.0,4.0,0.002835,0.003115,-0.094230,0.147086,1.024079,inf
2,"(5.16, 7.74]",39,0.923077,0.003102,36.0,3.0,0.003190,0.002336,0.311235,0.034188,0.405465,inf
3,"(7.74, 10.32]",66,0.939394,0.005250,62.0,4.0,0.005493,0.003115,0.567169,0.016317,0.255933,inf
4,"(10.32, 12.9]",42,0.833333,0.003341,35.0,7.0,0.003101,0.005452,-0.564234,0.106061,1.131402,inf
5,"(12.9, 15.48]",69,0.869565,0.005489,60.0,9.0,0.005316,0.007009,-0.276551,0.036232,0.287682,inf
6,"(15.48, 18.06]",95,0.863158,0.007557,82.0,13.0,0.007265,0.010125,-0.331902,0.006407,0.055350,inf
7,"(18.06, 20.64]",58,0.965517,0.004614,56.0,2.0,0.004961,0.001558,1.158533,0.102359,1.490435,inf
8,"(20.64, 23.22]",101,0.891089,0.008034,90.0,11.0,0.007974,0.008567,-0.071757,0.074428,1.230290,inf
9,"(23.22, 25.8]",94,0.946809,0.007478,89.0,5.0,0.007885,0.003894,0.705527,0.055719,0.777284,inf
10,"(25.8, 28.38]",135,0.896296,0.010739,121.0,14.0,0.010720,0.010903,-0.016938,0.050512,0.722465,inf
11,"(28.38, 30.96]",103,0.922330,0.008193,95.0,8.0,0.008417,0.006231,0.300764,0.026034,0.317702,inf
12,"(30.96, 33.54]",196,0.923469,0.015591,181.0,15.0,0.016036,0.011682,0.316775,0.001139,0.016011,inf
13,"(33.54, 36.12]",195,0.907692,0.015512,177.0,18.0,0.015682,0.014019,0.112107,0.015777,0.204669,inf
14,"(36.12, 38.7]",166,0.909639,0.013205,151.0,15.0,0.013378,0.011682,0.135558,0.001946,0.023452,inf
15,"(38.7, 41.28]",234,0.905983,0.018614,212.0,22.0,0.018783,0.017134,0.091872,0.003656,0.043686,inf
16,"(41.28, 43.86]",194,0.896907,0.015432,174.0,20.0,0.015416,0.015576,-0.010348,0.009076,0.102221,inf
17,"(43.86, 46.44]",328,0.917683,0.026092,301.0,27.0,0.026668,0.021028,0.237602,0.020776,0.247950,inf
18,"(46.44, 49.02]",367,0.920981,0.029194,338.0,29.0,0.029946,0.022586,0.282079,0.003298,0.044477,inf
19,"(49.02, 51.6]",231,0.943723,0.018376,218.0,13.0,0.019314,0.010125,0.645874,0.022742,0.363796,inf
20,"(51.6, 54.18]",447,0.926174,0.035558,414.0,33.0,0.036679,0.025701,0.355687,0.017548,0.290187,inf
21,"(54.18, 56.76]",264,0.897727,0.021001,237.0,27.0,0.020998,0.021028,-0.001448,0.028447,0.357135,inf
22,"(56.76, 59.34]",393,0.928753,0.031262,365.0,28.0,0.032338,0.021807,0.394021,0.031026,0.395470,inf
23,"(59.34, 61.92]",287,0.909408,0.022830,261.0,26.0,0.023124,0.020249,0.132752,0.019346,0.261269,inf
24,"(61.92, 64.5]",405,0.920988,0.032217,373.0,32.0,0.033047,0.024922,0.282171,0.011580,0.149419,inf
25,"(64.5, 67.08]",394,0.961929,0.031342,379.0,15.0,0.033578,0.011682,1.055815,0.040941,0.773643,inf
26,"(67.08, 69.66]",272,0.893382,0.021637,243.0,29.0,0.021529,0.022586,-0.047906,0.068547,1.103720,inf
27,"(69.66, 72.24]",366,0.912568,0.029115,334.0,32.0,0.029592,0.024922,0.171734,0.019186,0.219639,inf
28,"(72.24, 74.82]",231,0.922078,0.018376,213.0,18.0,0.018871,0.014019,0.297249,0.009510,0.125515,inf
29,"(74.82, 77.4]",350,0.920000,0.027842,322.0,28.0,0.028528,0.021807,0.268676,0.002078,0.028573,inf
30,"(77.4, 79.98]",228,0.903509,0.018137,206.0,22.0,0.018251,0.017134,0.063162,0.016491,0.205513,inf
31,"(79.98, 82.56]",355,0.895775,0.028240,318.0,37.0,0.028174,0.028816,-0.022538,0.007734,0.085700,inf
32,"(82.56, 85.14]",288,0.916667,0.022910,264.0,24.0,0.023390,0.018692,0.224224,0.020892,0.246762,inf
33,"(85.14, 87.72]",251,0.816733,0.019967,205.0,46.0,0.018162,0.035826,-0.679303,0.099934,0.903527,inf
34,"(87.72, 90.3]",345,0.889855,0.027444,307.0,38.0,0.027199,0.029595,-0.084410,0.073122,0.594893,inf
35,"(90.3, 92.88]",249,0.843373,0.019807,210.0,39.0,0.018605,0.030374,-0.490126,0.046482,0.405716,inf
36,"(92.88, 95.46]",385,0.862338,0.030626,332.0,53.0,0.029414,0.041277,-0.338828,0.018964,0.151297,inf
37,"(95.46, 98.04]",401,0.877805,0.031899,352.0,49.0,0.031186,0.038162,-0.201861,0.015468,0.136968,inf
38,"(98.04, 100.62]",327,0.871560,0.026012,285.0,42.0,0.025250,0.032710,-0.258852,0.006246,0.056991,inf
39,"(100.62, 103.2]",526,0.884030,0.041842,465.0,61.0,0.041198,0.047508,-0.142508,0.012471,0.116344,inf
40,"(103.2, 105.78]",396,0.891414,0.031501,353.0,43.0,0.031275,0.033489,-0.068403,0.007384,0.074104,inf
41,"(105.78, 108.36]",565,0.886726,0.044945,501.0,64.0,0.044387,0.049844,-0.115948,0.004688,0.047545,inf
42,"(108.36, 110.94]",407,0.911548,0.032376,371.0,36.0,0.032870,0.028037,0.159012,0.024822,0.274960,inf
43,"(110.94, 113.52]",524,0.883588,0.041683,463.0,61.0,0.041021,0.047508,-0.146818,0.027960,0.305830,inf
44,"(113.52, 116.1]",515,0.908738,0.040967,468.0,47.0,0.041464,0.036604,0.124649,0.025150,0.271468,inf
45,"(116.1, 118.68]",314,0.882166,0.024978,277.0,37.0,0.024542,0.028816,-0.160572,0.026572,0.285221,inf
46,"(118.68, 121.26]",92,0.847826,0.007318,78.0,14.0,0.006911,0.010903,-0.456020,0.034340,0.295448,inf
47,"(121.26, 123.84]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
48,"(123.84, 126.42]",0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,inf
49,"(126.42, 129.0]",1,0.000000,0.000080,0.0,1.0,0.000000,0.000779,-inf,NaN,NaN,inf

In [172]:
plot_by_woe(df_temp, 90)
# We plot the weight of evidence values.

C:\Users\Sanket\Anaconda4\lib\site-packages\matplotlib\pyplot.py:523: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)

In [173]:
# Categories: 'Missing', '0-2', '3-20', '21-31', '32-80', '81-86', '>86'
df_inputs_prepr['mths_since_last_record:Missing'] = np.where((df_inputs_prepr['mths_since_last_record'].isnull()), 1, 0)
df_inputs_prepr['mths_since_last_record:0-2'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 0) & (df_inputs_prepr['mths_since_last_record'] <= 2), 1, 0)
df_inputs_prepr['mths_since_last_record:3-20'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 3) & (df_inputs_prepr['mths_since_last_record'] <= 20), 1, 0)
df_inputs_prepr['mths_since_last_record:21-31'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 21) & (df_inputs_prepr['mths_since_last_record'] <= 31), 1, 0)
df_inputs_prepr['mths_since_last_record:32-80'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 32) & (df_inputs_prepr['mths_since_last_record'] <= 80), 1, 0)
df_inputs_prepr['mths_since_last_record:81-86'] = np.where((df_inputs_prepr['mths_since_last_record'] >= 81) & (df_inputs_prepr['mths_since_last_record'] <= 86), 1, 0)
df_inputs_prepr['mths_since_last_record:>86'] = np.where((df_inputs_prepr['mths_since_last_record'] > 86), 1, 0)

### Preprocessing the Test Dataset

In [174]:
#####
#loan_data_inputs_train = df_inputs_prepr
#####
loan_data_inputs_test = df_inputs_prepr

In [175]:
loan_data_inputs_train.to_csv('loan_data_inputs_train.csv')
loan_data_targets_train.to_csv('loan_data_targets_train.csv')
loan_data_inputs_test.to_csv('loan_data_inputs_test.csv')
loan_data_targets_test.to_csv('loan_data_targets_test.csv')